import type { SettingDef } from './types.js';

/** MySQL 5.7 / 8.0 catalog — filtered by live version */
export const MYSQL_SETTING_DEFS: SettingDef[] = [
  // Network
  {
    key: 'port',
    label: '埠',
    category: 'network',
    type: 'int',
    applyMode: 'restart',
    description: '伺服器監聽埠',
  },
  {
    key: 'bind_address',
    label: '綁定位址',
    category: 'network',
    type: 'string',
    applyMode: 'restart',
    confKey: 'bind-address',
    description: '監聽 IP；建議 127.0.0.1 僅本機',
  },
  {
    key: 'max_connections',
    label: '最大連線數',
    category: 'network',
    type: 'int',
    applyMode: 'runtime',
  },
  {
    key: 'max_connect_errors',
    label: '最大連線錯誤',
    category: 'network',
    type: 'int',
    applyMode: 'runtime',
  },
  {
    key: 'wait_timeout',
    label: '閒置逾時（秒）',
    category: 'network',
    type: 'duration',
    unit: 's',
    applyMode: 'runtime',
  },
  {
    key: 'interactive_timeout',
    label: '互動逾時（秒）',
    category: 'network',
    type: 'duration',
    unit: 's',
    applyMode: 'runtime',
  },
  {
    key: 'skip_name_resolve',
    label: '略過 DNS 解析',
    category: 'network',
    type: 'bool',
    applyMode: 'restart',
    description: '提升連線速度，僅用 IP 授權',
  },
  // Performance
  {
    key: 'innodb_buffer_pool_size',
    label: 'InnoDB 緩衝池',
    category: 'performance',
    type: 'bytes',
    applyMode: 'restart',
    description: '主要記憶體快取，通常為 RAM 50–70%',
  },
  {
    key: 'innodb_log_file_size',
    label: 'InnoDB 日誌檔大小',
    category: 'performance',
    type: 'bytes',
    applyMode: 'restart',
  },
  {
    key: 'innodb_flush_log_at_trx_commit',
    label: 'InnoDB 提交刷盤',
    category: 'performance',
    type: 'enum',
    enumValues: ['0', '1', '2'],
    applyMode: 'runtime',
    description: '1=最安全；2=效能較佳',
  },
  {
    key: 'tmp_table_size',
    label: '暫存表大小',
    category: 'performance',
    type: 'bytes',
    applyMode: 'runtime',
  },
  {
    key: 'max_heap_table_size',
    label: '記憶體表上限',
    category: 'performance',
    type: 'bytes',
    applyMode: 'runtime',
  },
  {
    key: 'table_open_cache',
    label: '表快取',
    category: 'performance',
    type: 'int',
    applyMode: 'runtime',
  },
  // Charset
  {
    key: 'character_set_server',
    label: '伺服器字元集',
    category: 'network',
    type: 'string',
    applyMode: 'restart',
  },
  {
    key: 'collation_server',
    label: '伺服器排序規則',
    category: 'network',
    type: 'string',
    applyMode: 'restart',
  },
  // Logging
  {
    key: 'slow_query_log',
    label: '慢查詢日誌',
    category: 'logging',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    applyMode: 'runtime',
  },
  {
    key: 'long_query_time',
    label: '慢查詢閾值（秒）',
    category: 'logging',
    type: 'duration',
    unit: 's',
    applyMode: 'runtime',
  },
  {
    key: 'log_error',
    label: '錯誤日誌路徑',
    category: 'logging',
    type: 'string',
    applyMode: 'restart',
  },
  {
    key: 'general_log',
    label: '一般查詢日誌',
    category: 'logging',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    applyMode: 'runtime',
    danger: true,
    description: '開啟會嚴重影響效能',
  },
  // Persistence / binlog
  {
    key: 'log_bin',
    label: '二進制日誌',
    category: 'persistence',
    type: 'string',
    applyMode: 'restart',
    description: '空=關閉；設路徑則開啟',
  },
  {
    key: 'binlog_format',
    label: 'Binlog 格式',
    category: 'persistence',
    type: 'enum',
    enumValues: ['ROW', 'STATEMENT', 'MIXED'],
    applyMode: 'runtime',
  },
  {
    key: 'binlog_expire_logs_seconds',
    label: 'Binlog 保留（秒）',
    category: 'persistence',
    type: 'int',
    applyMode: 'runtime',
    minVersion: '8.0',
  },
  {
    key: 'expire_logs_days',
    label: 'Binlog 保留（天）',
    category: 'persistence',
    type: 'int',
    applyMode: 'runtime',
    maxVersion: '5.7',
  },
  // Security
  {
    key: 'require_secure_transport',
    label: '強制安全傳輸',
    category: 'security',
    type: 'enum',
    enumValues: ['ON', 'OFF'],
    applyMode: 'runtime',
    minVersion: '5.7',
  },
  {
    key: 'default_authentication_plugin',
    label: '預設驗證外掛',
    category: 'security',
    type: 'string',
    applyMode: 'restart',
    minVersion: '5.7',
    maxVersion: '8.0',
  },
];

export const MARIADB_SETTING_DEFS: SettingDef[] = [
  ...MYSQL_SETTING_DEFS.filter((d) => d.key !== 'default_authentication_plugin'),
  {
    key: 'thread_handling',
    label: '執行緒模型',
    category: 'performance',
    type: 'string',
    applyMode: 'restart',
    description: 'MariaDB 特有：one-thread-per-connection / pool-of-threads',
  },
];
