import type { SettingDef } from './types.js';

export const POSTGRES_SETTING_DEFS: SettingDef[] = [
  {
    key: 'port',
    label: 'notes.port',
    category: 'network',
    type: 'int',
    applyMode: 'restart' },
  {
    key: 'listen_addresses',
    label: 'notes.auto.n1267',
    category: 'network',
    type: 'enum',
    enumValues: ['localhost', '*', '0.0.0.0', '127.0.0.1'],
    applyMode: 'restart',
    description: 'notes.auto.n0320' },
  {
    key: 'max_connections',
    label: 'notes.auto.n0040',
    category: 'network',
    type: 'int',
    applyMode: 'restart' },
  {
    key: 'password_encryption',
    label: 'notes.auto.n0661',
    category: 'security',
    type: 'enum',
    enumValues: ['scram-sha-256', 'md5'],
    applyMode: 'reload',
    minVersion: '10.0' },
  {
    key: 'shared_buffers',
    label: 'notes.auto.n0591',
    category: 'performance',
    type: 'bytes',
    applyMode: 'restart',
    description: 'notes.auto.n1467' },
  {
    key: 'work_mem',
    label: 'work_mem',
    category: 'performance',
    type: 'bytes',
    applyMode: 'reload' },
  {
    key: 'maintenance_work_mem',
    label: 'notes.auto.n1314',
    category: 'performance',
    type: 'bytes',
    applyMode: 'reload' },
  {
    key: 'effective_cache_size',
    label: 'notes.auto.n0945',
    category: 'performance',
    type: 'bytes',
    applyMode: 'reload' },
  {
    key: 'wal_level',
    label: 'notes.auto.n0200',
    category: 'persistence',
    type: 'enum',
    enumValues: ['minimal', 'replica', 'logical'],
    applyMode: 'restart' },
  {
    key: 'max_wal_size',
    label: 'notes.auto.n0935',
    category: 'persistence',
    type: 'bytes',
    applyMode: 'reload' },
  {
    key: 'checkpoint_timeout',
    label: 'notes.auto.n1026',
    category: 'persistence',
    type: 'enum',
    enumValues: ['30s', '1min', '5min', '10min', '15min'],
    applyMode: 'reload' },
  {
    key: 'archive_mode',
    label: 'notes.auto.n0679',
    category: 'persistence',
    type: 'enum',
    enumValues: ['off', 'on', 'always'],
    applyMode: 'restart' },
  {
    key: 'logging_collector',
    label: 'notes.auto.n0917',
    category: 'logging',
    type: 'bool',
    applyMode: 'restart' },
  {
    key: 'log_min_duration_statement',
    label: 'notes.auto.n0834',
    category: 'logging',
    type: 'int',
    unit: 'ms',
    applyMode: 'reload',
    description: 'notes.auto.n0057' },
  {
    key: 'log_statement',
    label: 'notes.auto.n1363',
    category: 'logging',
    type: 'enum',
    enumValues: ['none', 'ddl', 'mod', 'all'],
    applyMode: 'reload' },
  {
    key: 'autovacuum',
    label: 'notes.auto.n1328',
    category: 'performance',
    type: 'bool',
    applyMode: 'reload' },
  {
    key: 'autovacuum_max_workers',
    label: 'notes.auto.n0199',
    category: 'performance',
    type: 'int',
    applyMode: 'restart' },
  {
    key: 'ssl',
    label: 'notes.auto.n0622',
    category: 'security',
    type: 'bool',
    applyMode: 'restart' },
];
