import type { SettingDef } from './types.js';

export const POSTGRES_SETTING_DEFS: SettingDef[] = [
  {
    key: 'port',
    label: '埠',
    category: 'network',
    type: 'int',
    applyMode: 'restart',
  },
  {
    key: 'listen_addresses',
    label: '監聽位址',
    category: 'network',
    type: 'string',
    applyMode: 'restart',
    description: 'localhost 或 *',
  },
  {
    key: 'max_connections',
    label: '最大連線數',
    category: 'network',
    type: 'int',
    applyMode: 'restart',
  },
  {
    key: 'password_encryption',
    label: '密碼加密',
    category: 'security',
    type: 'enum',
    enumValues: ['scram-sha-256', 'md5'],
    applyMode: 'reload',
    minVersion: '10.0',
  },
  {
    key: 'shared_buffers',
    label: '共享緩衝',
    category: 'performance',
    type: 'bytes',
    applyMode: 'restart',
    description: '通常為 RAM 25%',
  },
  {
    key: 'work_mem',
    label: 'work_mem',
    category: 'performance',
    type: 'bytes',
    applyMode: 'reload',
  },
  {
    key: 'maintenance_work_mem',
    label: '維護記憶體',
    category: 'performance',
    type: 'bytes',
    applyMode: 'reload',
  },
  {
    key: 'effective_cache_size',
    label: '有效快取估計',
    category: 'performance',
    type: 'bytes',
    applyMode: 'reload',
  },
  {
    key: 'wal_level',
    label: 'WAL 等級',
    category: 'persistence',
    type: 'enum',
    enumValues: ['minimal', 'replica', 'logical'],
    applyMode: 'restart',
  },
  {
    key: 'max_wal_size',
    label: '最大 WAL',
    category: 'persistence',
    type: 'bytes',
    applyMode: 'reload',
  },
  {
    key: 'checkpoint_timeout',
    label: '檢查點逾時',
    category: 'persistence',
    type: 'duration',
    applyMode: 'reload',
  },
  {
    key: 'archive_mode',
    label: '封存模式',
    category: 'persistence',
    type: 'enum',
    enumValues: ['off', 'on', 'always'],
    applyMode: 'restart',
  },
  {
    key: 'logging_collector',
    label: '日誌收集器',
    category: 'logging',
    type: 'bool',
    applyMode: 'restart',
  },
  {
    key: 'log_min_duration_statement',
    label: '慢查詢閾值（ms）',
    category: 'logging',
    type: 'int',
    unit: 'ms',
    applyMode: 'reload',
    description: '-1 關閉；0 全部記錄',
  },
  {
    key: 'log_statement',
    label: '記錄語句類型',
    category: 'logging',
    type: 'enum',
    enumValues: ['none', 'ddl', 'mod', 'all'],
    applyMode: 'reload',
  },
  {
    key: 'autovacuum',
    label: '自動 VACUUM',
    category: 'performance',
    type: 'bool',
    applyMode: 'reload',
  },
  {
    key: 'autovacuum_max_workers',
    label: 'VACUUM 工作程序數',
    category: 'performance',
    type: 'int',
    applyMode: 'restart',
  },
  {
    key: 'ssl',
    label: '啟用 SSL',
    category: 'security',
    type: 'bool',
    applyMode: 'restart',
  },
];
