import type { SettingDef } from './types.js';

export const REDIS_SETTING_DEFS: SettingDef[] = [
  {
    key: 'port',
    label: '埠',
    category: 'network',
    type: 'int',
    applyMode: 'restart',
  },
  {
    key: 'bind',
    label: '綁定位址',
    category: 'network',
    type: 'string',
    applyMode: 'restart',
  },
  {
    key: 'protected-mode',
    label: '保護模式',
    category: 'security',
    type: 'enum',
    enumValues: ['yes', 'no'],
    applyMode: 'runtime',
  },
  {
    key: 'tcp-keepalive',
    label: 'TCP keepalive',
    category: 'network',
    type: 'int',
    unit: 's',
    applyMode: 'runtime',
  },
  {
    key: 'timeout',
    label: '客戶端閒置逾時',
    category: 'network',
    type: 'int',
    unit: 's',
    applyMode: 'runtime',
  },
  {
    key: 'databases',
    label: '資料庫數量',
    category: 'network',
    type: 'int',
    applyMode: 'restart',
    description: 'logical DB 0 … N-1；改後需重啟',
  },
  {
    key: 'maxclients',
    label: '最大客戶端數',
    category: 'network',
    type: 'int',
    applyMode: 'runtime',
  },
  {
    key: 'maxmemory',
    label: '最大記憶體',
    category: 'performance',
    type: 'bytes',
    applyMode: 'runtime',
    description: '0 = 不限制；可設 256mb',
  },
  {
    key: 'maxmemory-policy',
    label: '記憶體淘汰策略',
    category: 'performance',
    type: 'enum',
    enumValues: [
      'noeviction',
      'allkeys-lru',
      'volatile-lru',
      'allkeys-lfu',
      'volatile-lfu',
      'allkeys-random',
      'volatile-ttl',
    ],
    applyMode: 'runtime',
  },
  {
    key: 'appendonly',
    label: 'AOF 持久化',
    category: 'persistence',
    type: 'enum',
    enumValues: ['yes', 'no'],
    applyMode: 'runtime',
  },
  {
    key: 'appendfsync',
    label: 'AOF fsync',
    category: 'persistence',
    type: 'enum',
    enumValues: ['always', 'everysec', 'no'],
    applyMode: 'runtime',
  },
  {
    key: 'save',
    label: 'RDB 快照規則',
    category: 'persistence',
    type: 'string',
    applyMode: 'runtime',
    description: '例如 900 1 300 10；空字串關閉',
  },
  {
    key: 'dir',
    label: '資料目錄',
    category: 'persistence',
    type: 'string',
    applyMode: 'runtime',
  },
  {
    key: 'dbfilename',
    label: 'RDB 檔名',
    category: 'persistence',
    type: 'string',
    applyMode: 'runtime',
  },
  {
    key: 'requirepass',
    label: '存取密碼',
    category: 'security',
    type: 'string',
    applyMode: 'runtime',
    danger: true,
  },
  {
    key: 'loglevel',
    label: '日誌等級',
    category: 'logging',
    type: 'enum',
    enumValues: ['debug', 'verbose', 'notice', 'warning'],
    applyMode: 'runtime',
  },
  {
    key: 'logfile',
    label: '日誌檔',
    category: 'logging',
    type: 'string',
    applyMode: 'restart',
  },
];
