import type { SettingDef } from './types.js';

export const REDIS_SETTING_DEFS: SettingDef[] = [
  {
    key: 'port',
    label: 'notes.port',
    category: 'network',
    type: 'int',
    applyMode: 'restart' },
  {
    key: 'bind',
    label: 'notes.auto.n0041',
    category: 'network',
    type: 'enum',
    enumValues: ['127.0.0.1', '0.0.0.0', '::1', '127.0.0.1 -::1'],
    applyMode: 'restart' },
  {
    key: 'protected-mode',
    label: 'notes.auto.n0558',
    category: 'security',
    type: 'enum',
    enumValues: ['yes', 'no'],
    applyMode: 'runtime' },
  {
    key: 'tcp-keepalive',
    label: 'TCP keepalive',
    category: 'network',
    type: 'int',
    unit: 's',
    applyMode: 'runtime' },
  {
    key: 'timeout',
    label: 'notes.auto.n0660',
    category: 'network',
    type: 'int',
    unit: 's',
    applyMode: 'runtime' },
  {
    key: 'databases',
    label: 'notes.auto.n1451',
    category: 'network',
    type: 'int',
    applyMode: 'restart',
    description: 'notes.auto.n0321' },
  {
    key: 'maxclients',
    label: 'notes.auto.n0936',
    category: 'network',
    type: 'int',
    applyMode: 'runtime' },
  {
    key: 'maxmemory',
    label: 'notes.auto.n0937',
    category: 'performance',
    type: 'bytes',
    applyMode: 'runtime',
    description: 'notes.auto.n0060' },
  {
    key: 'maxmemory-policy',
    label: 'notes.auto.n1359',
    category: 'performance',
    type: 'enum',
    enumValues: [
      'noeviction',
      'allkeys-lru',
      'volatile-lru',
      'allkeys-lfu',
      'volatile-lfu',
      'allkeys-random',
      'volatile-ttl',
    ],
    applyMode: 'runtime' },
  {
    key: 'appendonly',
    label: 'notes.auto.n0073',
    category: 'persistence',
    type: 'enum',
    enumValues: ['yes', 'no'],
    applyMode: 'runtime' },
  {
    key: 'appendfsync',
    label: 'AOF fsync',
    category: 'persistence',
    type: 'enum',
    enumValues: ['always', 'everysec', 'no'],
    applyMode: 'runtime' },
  {
    key: 'save',
    label: 'notes.auto.n0166',
    category: 'persistence',
    type: 'enum',
    enumValues: ['', '900 1', '300 10', '60 10000', '900 1 300 10 60 10000'],
    applyMode: 'runtime',
    description: 'notes.auto.n0552' },
  {
    key: 'dir',
    label: 'notes.auto.n1454',
    category: 'persistence',
    type: 'enum',
    enumValues: ['/var/lib/redis', '/var/lib/redis/default', '/data'],
    applyMode: 'runtime' },
  {
    key: 'dbfilename',
    label: 'notes.auto.n0167',
    category: 'persistence',
    type: 'enum',
    enumValues: ['dump.rdb', 'redis.rdb'],
    applyMode: 'runtime' },
  {
    key: 'requirepass',
    label: 'notes.auto.n0648',
    category: 'security',
    type: 'string',
    applyMode: 'runtime',
    danger: true },
  {
    key: 'loglevel',
    label: 'notes.auto.n0920',
    category: 'logging',
    type: 'enum',
    enumValues: ['debug', 'verbose', 'notice', 'warning'],
    applyMode: 'runtime' },
  {
    key: 'logfile',
    label: 'notes.auto.n0918',
    category: 'logging',
    type: 'enum',
    enumValues: ['', '/var/log/redis/redis-server.log', '/var/log/redis.log'],
    applyMode: 'restart' },
];
