/**
 * Build Dovecot passwd-file / userdb snippets from managed mailboxes.
 * Format is compatible with Dovecot passwd-file scheme (not crypt(3) — document ysk-scrypt).
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { ErrorCodes, YskError, tl} from '@ysk/shared';
import type { YskDatabase } from '../db/database.js';

export interface DovecotPassdbResult {
  ok: boolean;
  domain: string;
  passwdPath: string;
  userdbPath: string;
  confSnippetPath: string;
  written: string[];
  mailboxCount: number;
  notes: string[];
}

/**
 * Rewrite Dovecot passwd-file for a domain from snapshot.mailboxes.
 * Password field: if hash present use it; else use '*' (login denied until password set).
 */
export function writeDovecotPassdb(input: {
  dataDir: string;
  db: YskDatabase;
  domain: string;
  domainId?: string;
}): DovecotPassdbResult {
  const domain = input.domain.trim().toLowerCase();
  if (!domain) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.needDomain'), { httpStatus: 400 });
  }

  const mailboxes = input.db.snapshot.mailboxes.filter((m) => {
    if (input.domainId) return m.domain_id === input.domainId;
    return String(m.domain ?? '').toLowerCase() === domain;
  });

  const dir = join(input.dataDir, 'email', domain, 'dovecot');
  mkdirSync(dir, { recursive: true });
  const passwdPath = join(dir, 'passwd');
  const userdbPath = join(dir, 'userdb');
  const confSnippetPath = join(dir, 'auth-ysk.conf.ext');

  const passwdLines: string[] = [
    '# YSK Server Dovecot passwd-file — review before production',
    '# user:password:uid:gid:gecos:home:shell:extra_fields',
  ];
  const userdbLines: string[] = ['# userdb static-style lines for mail_location'];

  for (const m of mailboxes) {
    const user = String(m.address ?? `${m.local_part}@${domain}`);
    const maildir =
      (m.maildir as string) ||
      join(input.dataDir, 'email', domain, 'mailboxes', String(m.local_part), 'Maildir');
    const hash = (m.password_hash as string) || '*';
    // uid/gid 5000 placeholder for vmail; operator should align with system vmail user
    passwdLines.push(`${user}:${hash}:5000:5000::${join(maildir, '..')}::userdb_mail=maildir:${maildir}`);
    userdbLines.push(`${user}::::::userdb_mail=maildir:${maildir}`);
  }

  writeFileSync(passwdPath, passwdLines.join('\n') + '\n', 'utf8');
  writeFileSync(userdbPath, userdbLines.join('\n') + '\n', 'utf8');
  const hasSha512 = mailboxes.some(
    (m) =>
      String(m.password_hash ?? '').includes('SHA512-CRYPT') ||
      String(m.password_hash ?? '').startsWith('$6$') ||
      m.password_scheme === 'SHA512-CRYPT',
  );
  const schemeArg = hasSha512 ? 'scheme=SHA512-CRYPT' : 'scheme=YSK-SCRYPT';

  writeFileSync(
    confSnippetPath,
    [
      '# Include from /etc/dovecot/conf.d/ — generated by YSK Server',
      'passdb {',
      '  driver = passwd-file',
      `  args = ${schemeArg} ${passwdPath}`,
      '}',
      'userdb {',
      '  driver = passwd-file',
      `  args = ${userdbPath}`,
      '}',
      '',
    ].join('\n'),
    'utf8',
  );

  const notes = [
    `passwd-file: ${passwdPath}`,
    `userdb: ${userdbPath}`,
    `auth snippet: ${confSnippetPath}`,
    hasSha512
      ? 'Passwords use {SHA512-CRYPT} (openssl) — Dovecot scheme=SHA512-CRYPT'
      : 'Passwords use YSK-SCRYPT — re-create mailboxes with openssl available for production',
    mailboxes.length === 0
      ? 'No mailboxes yet — create via email mailbox API first'
      : `${mailboxes.length} mailbox(es) exported`,
  ];

  return {
    ok: true,
    domain,
    passwdPath,
    userdbPath,
    confSnippetPath,
    written: [passwdPath, userdbPath, confSnippetPath],
    mailboxCount: mailboxes.length,
    notes };
}

/**
 * Write passdb for all domains that have mailboxes.
 */
export function writeAllDovecotPassdbs(input: {
  dataDir: string;
  db: YskDatabase;
}): { ok: boolean; domains: DovecotPassdbResult[]; notes: string[] } {
  const domains = new Set<string>();
  for (const m of input.db.snapshot.mailboxes) {
    if (m.domain) domains.add(String(m.domain).toLowerCase());
  }
  // also from email_domains
  for (const d of input.db.snapshot.email_domains) {
    if (d.domain) domains.add(String(d.domain).toLowerCase());
  }
  const results: DovecotPassdbResult[] = [];
  for (const domain of domains) {
    results.push(writeDovecotPassdb({ dataDir: input.dataDir, db: input.db, domain }));
  }
  const ok = results.every((r) => r.ok !== false);
  return {
    ok,
    domains: results,
    notes: [`Wrote passdb for ${results.length} domain(s)`] };
}

export function passdbExists(dataDir: string, domain: string): boolean {
  return existsSync(join(dataDir, 'email', domain, 'dovecot', 'passwd'));
}
