/**
 * Build Dovecot passwd-file / userdb snippets from managed mailboxes.
 * Format is compatible with Dovecot passwd-file scheme (not crypt(3) — document ysk-scrypt).
 */

import { mkdirSync, writeFileSync, existsSync, readdirSync, chmodSync } from 'node:fs';
import { join } from 'node:path';
import { ErrorCodes, YskError, tl } from '@ysk/shared';
import type { YskDatabase } from '../db/database.js';
import type { HostExecutor } from '../host/executor.js';

/** Shared vmail uid/gid used in passwd-file (create system user on apply). */
export const YSK_VMAIL_UID = 5000;
export const YSK_VMAIL_GID = 5000;
export const YSK_VMAIL_USER = 'vmail';
export const YSK_VMAIL_GROUP = 'vmail';

export interface DovecotPassdbResult {
  ok: boolean;
  domain: string;
  passwdPath: string;
  userdbPath: string;
  confSnippetPath: string;
  written: string[];
  mailboxCount: number;
  notes: string[];
}

/**
 * Rewrite Dovecot passwd-file for a domain from snapshot.mailboxes.
 * Password field: if hash present use it; else use '*' (login denied until password set).
 */
export function writeDovecotPassdb(input: {
  dataDir: string;
  db: YskDatabase;
  domain: string;
  domainId?: string;
}): DovecotPassdbResult {
  const domain = input.domain.trim().toLowerCase();
  if (!domain) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.needDomain'), { httpStatus: 400 });
  }

  const mailboxes = input.db.snapshot.mailboxes.filter((m) => {
    if (input.domainId) return m.domain_id === input.domainId;
    return String(m.domain ?? '').toLowerCase() === domain;
  });

  const dir = join(input.dataDir, 'email', domain, 'dovecot');
  mkdirSync(dir, { recursive: true });
  const passwdPath = join(dir, 'passwd');
  const userdbPath = join(dir, 'userdb');
  const confSnippetPath = join(dir, 'auth-ysk.conf.ext');

  const passwdLines: string[] = [
    '# YSK Server Dovecot passwd-file — review before production',
    '# user:password:uid:gid:gecos:home:shell:extra_fields',
  ];
  const userdbLines: string[] = ['# userdb lines for virtual mail (uid/gid/home/mail)'];

  for (const m of mailboxes) {
    const user = String(m.address ?? `${m.local_part}@${domain}`);
    const maildir =
      (m.maildir as string) ||
      join(input.dataDir, 'email', domain, 'mailboxes', String(m.local_part), 'Maildir');
    const home = join(maildir, '..');
    let hash = (m.password_hash as string) || '*';
    // Ensure Dovecot scheme prefix when raw $6$ crypt is stored
    if (hash.startsWith('$6$') && !hash.includes('{SHA512-CRYPT}')) {
      hash = `{SHA512-CRYPT}${hash}`;
    }
    // uid/gid/home in classic passwd fields; mail= extra field (passwd-file userdb)
    passwdLines.push(
      `${user}:${hash}:${YSK_VMAIL_UID}:${YSK_VMAIL_GID}::${home}::mail=maildir:${maildir}`,
    );
    userdbLines.push(
      `${user}::${YSK_VMAIL_UID}:${YSK_VMAIL_GID}::${home}::mail=maildir:${maildir}`,
    );
  }

  writeFileSync(passwdPath, passwdLines.join('\n') + '\n', 'utf8');
  writeFileSync(userdbPath, userdbLines.join('\n') + '\n', 'utf8');
  try {
    chmodSync(passwdPath, 0o640);
    chmodSync(userdbPath, 0o640);
  } catch {
    /* best-effort */
  }
  const hasSha512 = mailboxes.some(
    (m) =>
      String(m.password_hash ?? '').includes('SHA512-CRYPT') ||
      String(m.password_hash ?? '').startsWith('$6$') ||
      m.password_scheme === 'SHA512-CRYPT',
  );
  // Prefer scheme in the password field ({SHA512-CRYPT}$6$…) — omit default scheme to avoid double-prefix bugs
  const argsLine = hasSha512 ? `args = ${passwdPath}` : `args = scheme=YSK-SCRYPT ${passwdPath}`;

  writeFileSync(
    confSnippetPath,
    [
      '# Include from /etc/dovecot/conf.d/ — generated by YSK Server',
      'passdb {',
      '  driver = passwd-file',
      `  ${argsLine}`,
      '}',
      'userdb {',
      '  driver = passwd-file',
      `  args = ${userdbPath}`,
      '}',
      '',
    ].join('\n'),
    'utf8',
  );

  const notes = [
    `passwd-file: ${passwdPath}`,
    `userdb: ${userdbPath}`,
    `auth snippet: ${confSnippetPath}`,
    hasSha512
      ? 'Passwords use {SHA512-CRYPT} (openssl) — Dovecot reads scheme from hash prefix'
      : 'Passwords use YSK-SCRYPT — re-create mailboxes with openssl available for production',
    mailboxes.length === 0
      ? 'No mailboxes yet — create via email mailbox API first'
      : `${mailboxes.length} mailbox(es) exported`,
  ];

  return {
    ok: true,
    domain,
    passwdPath,
    userdbPath,
    confSnippetPath,
    written: [passwdPath, userdbPath, confSnippetPath],
    mailboxCount: mailboxes.length,
    notes,
  };
}

/**
 * Write passdb for all domains that have mailboxes.
 */
export function writeAllDovecotPassdbs(input: {
  dataDir: string;
  db: YskDatabase;
}): { ok: boolean; domains: DovecotPassdbResult[]; notes: string[] } {
  const domains = new Set<string>();
  for (const m of input.db.snapshot.mailboxes) {
    if (m.domain) domains.add(String(m.domain).toLowerCase());
  }
  // also from email_domains
  for (const d of input.db.snapshot.email_domains) {
    if (d.domain) domains.add(String(d.domain).toLowerCase());
  }
  const results: DovecotPassdbResult[] = [];
  for (const domain of domains) {
    results.push(writeDovecotPassdb({ dataDir: input.dataDir, db: input.db, domain }));
  }
  const ok = results.every((r) => r.ok !== false);
  return {
    ok,
    domains: results,
    notes: [`Wrote passdb for ${results.length} domain(s)`],
  };
}

export function passdbExists(dataDir: string, domain: string): boolean {
  return existsSync(join(dataDir, 'email', domain, 'dovecot', 'passwd'));
}

/**
 * Install YSK virtual-mail auth into live Dovecot + ensure vmail user + maildir ownership.
 * Without this step, Roundcube login always fails (Dovecot still uses PAM/system users only).
 */
export async function applyDovecotPassdbToSystem(input: {
  dataDir: string;
  host: HostExecutor;
  /** Re-write all domain passdbs first (default true) */
  rewritePassdbs?: boolean;
  db?: YskDatabase;
}): Promise<{ ok: boolean; notes: string[]; written: string[] }> {
  const notes: string[] = [];
  const written: string[] = [];
  if (!input.host.executeEnabled() || !input.host.isRoot()) {
    return {
      ok: false,
      notes: [tl('notes.email.dovecotApplyNeedRoot')],
      written,
    };
  }
  if (!input.host.pathExists('/usr/sbin/dovecot') && !input.host.pathExists('/usr/bin/doveconf')) {
    return {
      ok: false,
      notes: [tl('notes.email.dovecotNotInstalled')],
      written,
    };
  }

  if (input.rewritePassdbs !== false && input.db) {
    const all = writeAllDovecotPassdbs({ dataDir: input.dataDir, db: input.db });
    for (const r of all.domains) written.push(...r.written);
    notes.push(...all.notes);
  }

  const emailRoot = join(input.dataDir, 'email');
  const confd = '/etc/dovecot/conf.d';
  const authConf = join(confd, '99-ysk-virtual-mail.conf');
  const mailConf = join(confd, '99-ysk-virtual-mail-location.conf');

  // Build include list of domain auth snippets
  const includes: string[] = [];
  if (existsSync(emailRoot)) {
    for (const d of readdirSync(emailRoot)) {
      const snip = join(emailRoot, d, 'dovecot', 'auth-ysk.conf.ext');
      if (existsSync(snip)) includes.push(snip);
    }
  }
  if (includes.length === 0) {
    notes.push(tl('notes.email.dovecotNoPassdbSnippets'));
  }

  const authBody = [
    '# Generated by YSK Server — virtual mailbox auth (passwd-file)',
    '# Included after defaults; PAM remains as fallback for system users.',
    ...includes.map((p) => `!include ${p}`),
    '',
  ].join('\n');
  writeFileSync(authConf, authBody, 'utf8');
  written.push(authConf);

  const mailBody = [
    '# Generated by YSK Server — virtual mail defaults',
    `mail_uid = ${YSK_VMAIL_UID}`,
    `mail_gid = ${YSK_VMAIL_GID}`,
    `first_valid_uid = ${YSK_VMAIL_UID}`,
    'last_valid_uid = 60000',
    'mail_privileged_group = mail',
    // Prefer userdb mail=; keep a safe default
    'mail_location = maildir:~/Maildir',
    '',
  ].join('\n');
  writeFileSync(mailConf, mailBody, 'utf8');
  written.push(mailConf);

  // Create vmail user + chown maildirs + reload
  const script = [
    'set -euo pipefail',
    `groupadd -g ${YSK_VMAIL_GID} ${YSK_VMAIL_GROUP} 2>/dev/null || true`,
    `id -u ${YSK_VMAIL_USER} >/dev/null 2>&1 || useradd -u ${YSK_VMAIL_UID} -g ${YSK_VMAIL_GID} -d ${JSON.stringify(join(input.dataDir, 'email'))} -s /usr/sbin/nologin ${YSK_VMAIL_USER}`,
    `if [ "$(id -u ${YSK_VMAIL_USER} 2>/dev/null || echo x)" != "${YSK_VMAIL_UID}" ]; then echo "WARN: ${YSK_VMAIL_USER} uid mismatch"; fi`,
    `chown root:dovecot ${JSON.stringify(authConf)} ${JSON.stringify(mailConf)} 2>/dev/null || true`,
    `chmod 644 ${JSON.stringify(authConf)} ${JSON.stringify(mailConf)}`,
    // passwd files readable by dovecot
    `find ${JSON.stringify(emailRoot)} \\( -path '*/dovecot/passwd' -o -path '*/dovecot/userdb' \\) 2>/dev/null | while read -r f; do chown root:dovecot "$f" 2>/dev/null || true; chmod 640 "$f"; done`,
    // maildirs owned by vmail
    `if [ -d ${JSON.stringify(emailRoot)} ]; then`,
    `  find ${JSON.stringify(emailRoot)} -type d -name Maildir -print0 | xargs -0 -r chown -R ${YSK_VMAIL_UID}:${YSK_VMAIL_GID}`,
    `  find ${JSON.stringify(emailRoot)} -type d -path '*/mailboxes/*' -print0 | xargs -0 -r chown ${YSK_VMAIL_UID}:${YSK_VMAIL_GID} 2>/dev/null || true`,
    `fi`,
    'doveconf -n >/dev/null',
    'systemctl reload dovecot 2>/dev/null || service dovecot reload 2>/dev/null || doveadm reload 2>/dev/null || true',
  ].join('\n');

  const r = await input.host.runCommand(['bash', '-c', script], { timeoutMs: 60_000 });
  if (r.exitCode !== 0) {
    notes.push(
      tl('notes.email.dovecotApplyFailed', {
        detail: (r.stderr || r.stdout || '').slice(0, 300),
      }),
    );
    return { ok: false, notes, written };
  }
  notes.push(tl('notes.email.dovecotApplyOk', { conf: authConf, count: includes.length }));
  notes.push(...(r.stdout || '').split('\n').filter(Boolean).slice(0, 5));
  return { ok: true, notes, written };
}
