/**
 * Roundcube webmail managed install plan + config under dataDir.
 * Never fakes success: package download/install needs YSK_EXECUTE (+ root for system paths).
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { ErrorCodes, YskError } from '@ysk/shared';
import type { HostExecutor } from '../host/executor.js';
import { renderNginxProxy } from '../hosting/nginx-ssl.js';
import { writeManagedNginxConf } from '../hosting/nginx-sync.js';

export interface WebmailApplyResult {
  ok: boolean;
  domain: string;
  webRoot: string;
  configPath: string;
  nginxPath?: string;
  written: string[];
  notes: string[];
  commandResults: Array<{ argv: string[]; exitCode: number; stderr: string }>;
  requiresExecute: boolean;
  requiresRoot: boolean;
  mode: 'plan' | 'downloaded' | 'refused';
}

/**
 * Write Roundcube config skeleton + nginx proxy to PHP built-in or FPM later.
 * Optional: download Roundcube tarball when execute + network.
 */
export async function applyWebmail(input: {
  dataDir: string;
  host: HostExecutor;
  /** Public hostname for webmail e.g. webmail.example.com */
  domain: string;
  /** IMAP host (default mail.<parent domain or localhost>) */
  imapHost?: string;
  smtpHost?: string;
  /** When true, curl Roundcube release into dataDir (needs EXECUTE) */
  download?: boolean;
  /** Prefer system /var/www path when root+EXECUTE after download */
  systemInstall?: boolean;
}): Promise<WebmailApplyResult> {
  const domain = input.domain.trim().toLowerCase();
  if (!domain || domain.includes('..')) {
    throw new YskError(ErrorCodes.VALIDATION, 'Invalid webmail domain', { httpStatus: 400 });
  }

  const notes: string[] = [];
  const written: string[] = [];
  const commandResults: WebmailApplyResult['commandResults'] = [];
  const base = join(input.dataDir, 'email', 'webmail', domain);
  const webRoot = join(base, 'public');
  const configDir = join(base, 'config');
  mkdirSync(webRoot, { recursive: true });
  mkdirSync(configDir, { recursive: true });

  const imapHost = input.imapHost ?? `mail.${domain.replace(/^webmail\./, '')}`;
  const smtpHost = input.smtpHost ?? imapHost;

  const configPath = join(configDir, 'config.inc.php');
  writeFileSync(
    configPath,
    [
      '<?php',
      '// Generated by YSK Server — Roundcube config skeleton (review before production)',
      "$config = [];",
      "$config['db_dsnw'] = 'sqlite:////' . __DIR__ . '/../db/roundcube.db?mode=0646';",
      `$config['default_host'] = 'ssl://${imapHost}';`,
      "$config['default_port'] = 993;",
      `$config['smtp_server'] = 'tls://${smtpHost}';`,
      "$config['smtp_port'] = 587;",
      "$config['smtp_user'] = '%u';",
      "$config['smtp_pass'] = '%p';",
      "$config['support_url'] = '';",
      "$config['product_name'] = 'YSK Webmail';",
      `$config['des_key'] = '${randomDesKey()}';`,
      "$config['plugins'] = ['archive', 'zipdownload'];",
      "$config['skin'] = 'elastic';",
      '',
    ].join('\n'),
    'utf8',
  );
  written.push(configPath);

  // placeholder index until Roundcube downloaded
  const indexPath = join(webRoot, 'index.php');
  if (!existsSync(indexPath)) {
    writeFileSync(
      indexPath,
      `<?php
// YSK Webmail placeholder — download Roundcube (applyWebmail download:true) or copy release here
header('Content-Type: text/plain; charset=utf-8');
echo "YSK Webmail for ${domain}\\n";
echo "Config: ${configPath}\\n";
echo "IMAP: ${imapHost}:993  SMTP: ${smtpHost}:587\\n";
`,
      'utf8',
    );
    written.push(indexPath);
  }

  const installScript = join(base, 'install-roundcube.sh');
  writeFileSync(
    installScript,
    [
      '#!/usr/bin/env bash',
      `# YSK Server — install Roundcube for ${domain}`,
      'set -euo pipefail',
      `ROOT=${JSON.stringify(webRoot)}`,
      `CFG=${JSON.stringify(configPath)}`,
      'TMP=$(mktemp -d)',
      'cd "$TMP"',
      'VER=${ROUNDCUBE_VERSION:-1.6.9}',
      'curl -fsSL -o rc.tar.gz "https://github.com/roundcube/roundcubemail/releases/download/${VER}/roundcubemail-${VER}-complete.tar.gz"',
      'tar -xzf rc.tar.gz',
      'rm -rf "$ROOT"/*',
      'cp -a roundcubemail-*/. "$ROOT/"',
      'mkdir -p "$(dirname "$CFG")"',
      'cp -n "$CFG" "$ROOT/config/config.inc.php" 2>/dev/null || cp "$CFG" "$ROOT/config/config.inc.php"',
      'mkdir -p "$ROOT/../db"',
      'chown -R www-data:www-data "$ROOT" 2>/dev/null || true',
      'echo "Roundcube extracted to $ROOT"',
      '',
    ].join('\n'),
    'utf8',
  );
  written.push(installScript);
  notes.push(`Web root: ${webRoot}`, `Config: ${configPath}`, `Install helper: ${installScript}`);

  // nginx reverse proxy to local php -S or upstream
  const nginxPath = writeManagedNginxConf(
    input.dataDir,
    `webmail-${domain.replace(/\./g, '-')}.conf`,
    renderNginxProxy({
      serverName: domain,
      upstream: 'http://127.0.0.1:8088',
      ssl: false,
      cloudflareRealIp: true,
    }),
  );
  written.push(nginxPath);
  notes.push(`已寫入 Nginx 設定：${nginxPath}`);

  const readme = join(base, 'README.txt');
  writeFileSync(
    readme,
    [
      `YSK Webmail (Roundcube) for ${domain}`,
      `IMAP ${imapHost}:993  SMTP ${smtpHost}:587`,
      'Install and publish via admin panel (Webmail 安裝).',
      '',
    ].join('\n'),
    'utf8',
  );
  written.push(readme);

  // Panel defaults to download/install unless explicitly dry-run
  const wantDl = input.download !== false;
  const can = wantDl && input.host.executeEnabled();
  if (wantDl && !can) {
    notes.push('伺服器未開啟系統變更權限，無法在管理面板下載安裝 Webmail');
    return {
      ok: false,
      domain,
      webRoot,
      configPath,
      nginxPath,
      written,
      notes,
      commandResults,
      requiresExecute: true,
      requiresRoot: !input.host.isRoot(),
      mode: 'refused',
    };
  }

  if (can) {
    const r = await input.host.runCommand(['bash', installScript], { timeoutMs: 300_000 });
    commandResults.push({
      argv: ['bash', installScript],
      exitCode: r.exitCode,
      stderr: r.stderr,
    });
    if (r.exitCode !== 0) {
      notes.push(`Webmail 下載安裝失敗：${r.stderr || r.stdout}`);
      return {
        ok: false,
        domain,
        webRoot,
        configPath,
        nginxPath,
        written,
        notes,
        commandResults,
        requiresExecute: false,
        requiresRoot: !input.host.isRoot(),
        mode: 'refused',
      };
    }
    notes.push('已下載並解壓 Roundcube');
    if (input.systemInstall && input.host.isRoot()) {
      const dest = `/var/www/ysk-webmail/${domain}`;
      const cp = await input.host.runCommand(['bash', '-c', `mkdir -p ${dest} && cp -a ${webRoot}/. ${dest}/`], {
        timeoutMs: 60_000,
      });
      commandResults.push({
        argv: ['cp', '-a', webRoot, dest],
        exitCode: cp.exitCode,
        stderr: cp.stderr,
      });
      notes.push(cp.exitCode === 0 ? `已部署至 ${dest}` : `系統部署失敗：${cp.stderr}`);
    }
    return {
      ok: true,
      domain,
      webRoot,
      configPath,
      nginxPath,
      written,
      notes,
      commandResults,
      requiresExecute: false,
      requiresRoot: !input.host.isRoot(),
      mode: 'downloaded',
    };
  }

  return {
    ok: true,
    domain,
    webRoot,
    configPath,
    nginxPath,
    written,
    notes: [...notes, '已寫入設定檔（未下載套件）'],
    commandResults,
    requiresExecute: !input.host.executeEnabled(),
    requiresRoot: !input.host.isRoot(),
    mode: 'plan',
  };
}

function randomDesKey(): string {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let s = '';
  for (let i = 0; i < 24; i++) s += chars[Math.floor(Math.random() * chars.length)];
  return s;
}
