/**
 * UFW "Cloudflare only" profile — origin only accepts CF edge ranges + SSH.
 * Static IPv4 list from https://www.cloudflare.com/ips-v4 (refresh periodically).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { HostExecutor } from '../../host/executor.js';

/** Cloudflare published IPv4 ranges (origin-facing). */
export const CLOUDFLARE_IPV4_RANGES = [
  '173.245.48.0/20',
  '103.21.244.0/22',
  '103.22.200.0/22',
  '103.31.4.0/22',
  '141.101.64.0/18',
  '108.162.192.0/18',
  '190.93.240.0/20',
  '188.114.96.0/20',
  '197.234.240.0/22',
  '198.41.128.0/17',
  '162.158.0.0/15',
  '104.16.0.0/13',
  '104.24.0.0/14',
  '172.64.0.0/13',
  '131.0.72.0/22',
] as const;

export function renderCfOnlyUfwScript(opts?: {
  keepTcpPorts?: number[];
}): string {
  const ports = (opts?.keepTcpPorts?.length ? opts.keepTcpPorts : [22]).filter(
    (p) => Number.isInteger(p) && p > 0 && p < 65536,
  );
  const lines = [
    '#!/usr/bin/env bash',
    '# Generated by YSK Defense — Cloudflare-only origin profile',
    '# Review before running. Keeps SSH + CF edge ranges; denies other WAN ingress.',
    'set -euo pipefail',
    'ufw --force reset || true',
    'ufw default deny incoming',
    'ufw default allow outgoing',
    ...ports.map((p) => `ufw allow ${p}/tcp comment 'ysk-keep'`),
    ...CLOUDFLARE_IPV4_RANGES.flatMap((cidr) => [
      `ufw allow from ${cidr} to any port 80 proto tcp comment 'ysk-cf-80'`,
      `ufw allow from ${cidr} to any port 443 proto tcp comment 'ysk-cf-443'`,
    ]),
    'ufw --force enable',
    'ufw status numbered || true',
    '',
  ];
  return lines.join('\n');
}

/**
 * Write managed script under dataDir; optionally run when EXECUTE+root.
 */
export async function writeAndMaybeApplyCfOnlyUfw(input: {
  dataDir: string;
  host: HostExecutor;
  keepTcpPorts?: number[];
  apply: boolean;
}): Promise<{ ok: boolean; written: string[]; notes: string[]; blocked?: boolean }> {
  const dir = join(input.dataDir, 'firewall');
  mkdirSync(dir, { recursive: true });
  const scriptPath = join(dir, 'ufw-cf-only.sh');
  const body = renderCfOnlyUfwScript({ keepTcpPorts: input.keepTcpPorts });
  writeFileSync(scriptPath, body, 'utf8');
  const notes = [
    `已寫 CF-only UFW 腳本：${scriptPath}`,
    `保留埠：${(input.keepTcpPorts ?? [22]).join(',')}`,
    `CF IPv4 段：${CLOUDFLARE_IPV4_RANGES.length} 個`,
  ];
  if (!input.apply) {
    return {
      ok: true,
      written: [scriptPath],
      notes: [...notes, '未套用到系統（apply=false 或無權限）'],
      blocked: true,
    };
  }
  if (!input.host.executeEnabled()) {
    return {
      ok: false,
      written: [scriptPath],
      notes: [...notes, '需 YSK_EXECUTE 先可 ufw apply'],
      blocked: true,
    };
  }
  if (!input.host.isRoot()) {
    return {
      ok: false,
      written: [scriptPath],
      notes: [...notes, '需 root 先可改 UFW'],
      blocked: true,
    };
  }
  const r = await input.host.runCommand(['bash', scriptPath], { timeoutMs: 60_000 });
  const ok = r.exitCode === 0;
  notes.push(
    ok
      ? '已套用 CF-only UFW（origin 只收 CF + 保留埠）'
      : `ufw 腳本失敗：${(r.stderr || r.stdout || '').slice(0, 300)}`,
  );
  return { ok, written: [scriptPath], notes };
}
