import { tl } from '@ysk/shared';
/**
 * Generate nginx limit_req / limit_conn drop-in for defense presets.
 * Zones → http conf.d; server limits → .inc + inject into managed vhosts.
 */

import {
  mkdirSync,
  writeFileSync,
  existsSync,
  readFileSync,
  readdirSync,
} from 'node:fs';
import { join } from 'node:path';
import type { NginxLimitSpec } from './types.js';

const BEGIN = '# BEGIN YSK_DEFENSE';
const END = '# END YSK_DEFENSE';

export function defenseNginxConfPath(dataDir: string): string {
  return join(dataDir, 'nginx', 'conf.d', '00-ysk-defense.conf');
}

export function defenseLimitsIncludePath(dataDir: string): string {
  return join(dataDir, 'nginx', 'conf.d', 'ysk-defense-limits.inc');
}

export function sanitizeRate(rate: string): string {
  return rate.replace(/[^0-9a-zA-Z/]/g, '') || '10r/s';
}

export function renderDefenseNginxConf(spec: NginxLimitSpec): string {
  const rate = sanitizeRate(spec.reqRate);
  return `# Generated by YSK Defense Center — do not hand-edit
# limit zones (http context via conf.d include on many setups)
# Note: limit_req_zone must be in http{} — if conf.d is server-only, use include from nginx.conf
limit_req_zone $binary_remote_addr zone=ysk_req:10m rate=${rate};
limit_conn_zone $binary_remote_addr zone=ysk_conn:10m;

# Server-context limits live in ysk-defense-limits.inc (burst/conn from preset).
# Dual write: zone file + limit include for managed vhosts.
`;
}

/** Server-context snippet included by managed vhosts (after zones exist). */
export function renderDefenseLimitsInclude(spec: NginxLimitSpec): string {
  const burst = Math.max(1, Math.min(500, Math.floor(spec.burst)));
  const conn = Math.max(1, Math.min(1000, Math.floor(spec.connLimit)));
  return `# YSK Defense limits (server context)
limit_req zone=ysk_req burst=${burst} nodelay;
limit_conn ysk_conn ${conn};
limit_req_status 429;
`;
}

/**
 * Marker block inside each managed server { }.
 * Uses relative include so re-applying a preset only rewrites the .inc.
 */
export function renderDefenseLimitsMarkerBlock(_spec?: NginxLimitSpec): string {
  return `${BEGIN}
  include ysk-defense-limits.inc;
${END}`;
}

/**
 * Insert or replace YSK_DEFENSE marker block after first `server_name` line.
 * Skips zone conf and non-server files.
 */
export function injectDefenseLimitsIntoConf(
  content: string,
  spec?: NginxLimitSpec,
): string {
  const block = renderDefenseLimitsMarkerBlock(spec);
  const markerRe = new RegExp(
    `${BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\n?`,
    'g',
  );
  let body = content.replace(markerRe, '');
  // Insert after first server_name line inside a server block
  const sn = body.match(/^(\s*server_name\s+[^\n;]+;)/m);
  if (sn && sn.index !== undefined) {
    const insertAt = sn.index + sn[0].length;
    body = `${body.slice(0, insertAt)}\n${block}${body.slice(insertAt)}`;
  } else if (/server\s*\{/.test(body)) {
    body = body.replace(/server\s*\{/, (m) => `${m}\n${block}`);
  } else {
    // leave unchanged if not a server conf
    return content;
  }
  return body;
}

/**
 * Inject limits into all managed vhost .conf under dataDir (except zone file).
 */
export function injectDefenseLimitsIntoManagedVhosts(
  dataDir: string,
  spec: NginxLimitSpec,
): { updated: string[]; notes: string[] } {
  const confDir = join(dataDir, 'nginx', 'conf.d');
  const updated: string[] = [];
  const notes: string[] = [];
  if (!existsSync(confDir)) {
    notes.push(tl('notes.auto.n0717'));
    return { updated, notes };
  }
  const files = readdirSync(confDir).filter(
    (f) => f.endsWith('.conf') && f !== '00-ysk-defense.conf' && !f.startsWith('00-ysk-defense'),
  );
  for (const f of files) {
    const path = join(confDir, f);
    try {
      const raw = readFileSync(path, 'utf8');
      if (!/server\s*\{/.test(raw)) continue;
      const next = injectDefenseLimitsIntoConf(raw, spec);
      if (next !== raw) {
        writeFileSync(path, next, 'utf8');
        updated.push(path);
      }
    } catch (e) {
      notes.push(tl('notes.auto.t0558', { v0: (f), v1: (e instanceof Error ? e.message : String(e)) }));
    }
  }
  notes.push(
    updated.length
      ? tl('notes.auto.t0559', { v0: (updated.length) })
      : tl('notes.auto.n1089'),
  );
  return { updated, notes };
}

/**
 * Write zone drop-in, server include, and inject into managed vhosts.
 */
export function writeDefenseNginxLimits(
  dataDir: string,
  spec: NginxLimitSpec,
): { written: string[]; confPath: string; includePath: string; vhostsUpdated: string[] } {
  const confDir = join(dataDir, 'nginx', 'conf.d');
  mkdirSync(confDir, { recursive: true });
  const confPath = join(confDir, '00-ysk-defense.conf');
  const includePath = join(confDir, 'ysk-defense-limits.inc');
  const rate = sanitizeRate(spec.reqRate);
  const zoneBody = `# Generated by YSK Defense — ${new Date().toISOString()}
# http-context zones (include conf.d from nginx.conf)
limit_req_zone $binary_remote_addr zone=ysk_req:10m rate=${rate};
limit_conn_zone $binary_remote_addr zone=ysk_conn:10m;
# Server limits: ysk-defense-limits.inc + BEGIN/END YSK_DEFENSE in each vhost
`;
  writeFileSync(confPath, zoneBody, 'utf8');
  writeFileSync(includePath, renderDefenseLimitsInclude(spec), 'utf8');
  const inj = injectDefenseLimitsIntoManagedVhosts(dataDir, spec);
  return {
    written: [confPath, includePath, ...inj.updated],
    confPath,
    includePath,
    vhostsUpdated: inj.updated,
  };
}

export function readActiveNginxLimitNotes(dataDir: string): {
  exists: boolean;
  confPath: string;
  snippet?: string;
} {
  const confPath = defenseNginxConfPath(dataDir);
  if (!existsSync(confPath)) return { exists: false, confPath };
  try {
    return { exists: true, confPath, snippet: readFileSync(confPath, 'utf8').slice(0, 400) };
  } catch {
    return { exists: true, confPath };
  }
}
