/**
 * Real backup (tar) and cron job management under dataDir.
 */

import { existsSync, mkdirSync, readdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { ErrorCodes, YskError } from '@ysk/shared';
import type { HostExecutor } from '../host/executor.js';
import type { YskDatabase } from '../db/database.js';
import { planCronJob } from './extras.js';

export interface BackupResult {
  ok: boolean;
  archivePath?: string;
  bytes?: number;
  notes: string[];
  commandResults: Array<{ argv: string[]; exitCode: number; stderr: string }>;
}

/**
 * Create tar.gz of project home into dataDir/backups/<projectId>/.
 */
export async function backupProject(input: {
  host: HostExecutor;
  dataDir: string;
  projectId: string;
  homeDir: string;
  extraSources?: string[];
}): Promise<BackupResult> {
  if (!existsSync(input.homeDir)) {
    throw new YskError(ErrorCodes.NOT_FOUND, `Project home missing: ${input.homeDir}`, {
      httpStatus: 404,
    });
  }
  const destDir = join(input.dataDir, 'backups', input.projectId);
  mkdirSync(destDir, { recursive: true });
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const archivePath = join(destDir, `backup-${stamp}.tar.gz`);
  const sources = [input.homeDir, ...(input.extraSources ?? [])];
  // tar from parent with relative paths when possible
  const r = await input.host.runCommand(
    ['tar', '-czf', archivePath, '-C', '/', ...sources.map((s) => s.replace(/^\//, ''))],
    { timeoutMs: 120_000 },
  );
  if (r.exitCode !== 0) {
    // fallback: tar with absolute paths
    const r2 = await input.host.runCommand(['tar', '-czf', archivePath, ...sources], {
      timeoutMs: 120_000,
    });
    if (r2.exitCode !== 0) {
      return {
        ok: false,
        notes: [`tar failed: ${r2.stderr || r.stderr}`],
        commandResults: [
          { argv: ['tar', '...'], exitCode: r.exitCode, stderr: r.stderr },
          { argv: ['tar', '...'], exitCode: r2.exitCode, stderr: r2.stderr },
        ],
      };
    }
  }
  let bytes = 0;
  try {
    bytes = Buffer.byteLength(readFileSync(archivePath));
  } catch {
    /* ignore */
  }
  // retention: keep last 10
  const files = readdirSync(destDir)
    .filter((f) => f.endsWith('.tar.gz'))
    .sort()
    .reverse();
  for (const old of files.slice(10)) {
    try {
      const { unlinkSync } = await import('node:fs');
      unlinkSync(join(destDir, old));
    } catch {
      /* ignore */
    }
  }
  return {
    ok: true,
    archivePath,
    bytes,
    notes: [`Backup written ${archivePath}`, `Retention: keep last 10 archives`],
    commandResults: [{ argv: ['tar', '-czf', archivePath], exitCode: 0, stderr: '' }],
  };
}

export interface CronJobRecord {
  id: string;
  project_id?: string;
  user: string;
  schedule: string;
  command: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
  last_install?: Record<string, unknown>;
}

export class CronJobService {
  constructor(
    private readonly db: YskDatabase,
    private readonly host: HostExecutor,
    private readonly dataDir: string,
  ) {}

  list(projectId?: string): CronJobRecord[] {
    const all = cronRows(this.db);
    if (!projectId) return all.map((j) => ({ ...j }));
    return all.filter((j) => j.project_id === projectId).map((j) => ({ ...j }));
  }

  create(input: {
    projectId?: string;
    user: string;
    schedule: string;
    command: string;
    actor: string;
  }): CronJobRecord {
    planCronJob({
      user: input.user,
      schedule: input.schedule,
      command: input.command,
    });
    const now = new Date().toISOString();
    const row: CronJobRecord = {
      id: randomUUID(),
      project_id: input.projectId,
      user: input.user,
      schedule: input.schedule,
      command: input.command,
      enabled: true,
      created_at: now,
      updated_at: now,
    };
    this.db.snapshot.cron_jobs.unshift(row as unknown as Record<string, unknown>);
    this.db.persist();
    this.writeManagedCrontab();
    void input.actor;
    return { ...row };
  }

  delete(id: string): boolean {
    const before = this.db.snapshot.cron_jobs.length;
    this.db.snapshot.cron_jobs = this.db.snapshot.cron_jobs.filter((j) => j.id !== id);
    this.db.persist();
    this.writeManagedCrontab();
    return this.db.snapshot.cron_jobs.length < before;
  }

  /** Write all enabled jobs to dataDir/cron/ysk.crontab */
  writeManagedCrontab(): string {
    const dir = join(this.dataDir, 'cron');
    mkdirSync(dir, { recursive: true });
    const path = join(dir, 'ysk.crontab');
    const lines = [
      '# Generated by YSK Server — install with: crontab dataDir/cron/ysk.crontab',
      ...this.list()
        .filter((j) => j.enabled)
        .map((j) => `${j.schedule} ${j.command} # ysk:${j.id}`),
      '',
    ];
    writeFileSync(path, lines.join('\n'), 'utf8');
    return path;
  }

  /**
   * Install managed crontab for current user when EXECUTE.
   * Never fakes success.
   */
  async installCrontab(actor: string): Promise<{
    ok: boolean;
    path: string;
    requiresExecute: boolean;
    notes: string[];
  }> {
    const path = this.writeManagedCrontab();
    const notes = [`Managed crontab at ${path}`];
    if (!this.host.executeEnabled()) {
      return {
        ok: false,
        path,
        requiresExecute: true,
        notes: [...notes, 'Set YSK_EXECUTE=1 to run crontab install'],
      };
    }
    const r = await this.host.runCommand(['crontab', path], { timeoutMs: 10_000 });
    const ok = r.exitCode === 0;
    notes.push(ok ? 'crontab installed for current user' : `crontab failed: ${r.stderr}`);
    // stamp jobs
    for (const j of this.db.snapshot.cron_jobs) {
      j.last_install = { ok, at: new Date().toISOString(), actor };
    }
    this.db.persist();
    return { ok, path, requiresExecute: false, notes };
  }
}

function cronRows(db: YskDatabase): CronJobRecord[] {
  return (db.snapshot.cron_jobs ?? []) as unknown as CronJobRecord[];
}
