import { describe, expect, it, vi } from 'vitest';
import {
  classifyCronSource,
  cronHostUserSlots,
  extractYskManagedId,
  parseCrontabText,
  CronJobService,
} from './backup-cron.js';
import type { HostExecutor } from '../host/executor.js';
import type { YskDatabase } from '../db/database.js';

describe('cron host scan parsers', () => {
  it('extracts ysk managed id and source', () => {
    expect(extractYskManagedId('0 3 * * * true # ysk:abc-def-12')).toBe('abc-def-12');
    expect(classifyCronSource('0 3 * * * true # ysk:x')).toBe('ysk');
    expect(classifyCronSource('0 * * * * /usr/bin/php')).toBe('host');
    expect(classifyCronSource('# Generated by YSK Server')).toBe('ysk');
  });

  it('parses jobs, env, comments, @reboot', () => {
    const text = `
# header
MAILTO=ops@example.com
0 2 * * * /usr/bin/backup # ysk:11111111-1111-1111-1111-111111111111
@reboot /usr/local/bin/start.sh
* * * * * echo hi
not-a-cron-line
`.trim();
    const lines = parseCrontabText('root', text);
    expect(lines.some((l) => l.kind === 'comment')).toBe(true);
    expect(lines.some((l) => l.kind === 'env' && l.raw.includes('MAILTO'))).toBe(true);
    const ysk = lines.find((l) => l.managedJobId?.startsWith('1111'));
    expect(ysk?.kind).toBe('job');
    expect(ysk?.source).toBe('ysk');
    expect(ysk?.schedule).toBe('0 2 * * *');
    expect(ysk?.command).toContain('/usr/bin/backup');
    expect(lines.find((l) => l.schedule === '@reboot')?.command).toContain('start.sh');
    expect(lines.find((l) => l.command === 'echo hi')).toBeTruthy();
  });

  it('builds unique user slots root + projects', () => {
    const slots = cronHostUserSlots([
      { id: 'p1', name: 'A', linuxUser: 'ysks_a' },
      { id: 'p2', name: 'B', linux_user: 'ysks_a' },
      { id: 'p3', name: 'C', linuxUser: 'ysks_c' },
      { id: 'p4', name: 'D', linuxUser: '' },
    ]);
    expect(slots[0]?.user).toBe('root');
    expect(slots.map((s) => s.user)).toEqual(['root', 'ysks_a', 'ysks_c']);
    expect(slots.find((s) => s.user === 'ysks_a')?.projectName).toBe('A');
  });
});

describe('CronJobService.listHostCrontabs', () => {
  function mockHost(map: Record<string, { exitCode: number; stdout?: string; stderr?: string }>, opts?: { root?: boolean; execute?: boolean }): HostExecutor {
    return {
      executeEnabled: () => opts?.execute !== false,
      isRoot: () => opts?.root !== false,
      runCommand: vi.fn(async (argv: string[]) => {
        const key =
          argv[0] === 'crontab' && argv[1] === '-u'
            ? argv[2]!
            : argv[0] === 'crontab'
              ? '_self'
              : argv.join(' ');
        const hit = map[key] ?? map['*'] ?? { exitCode: 1, stderr: 'no crontab for user' };
        return {
          exitCode: hit.exitCode,
          stdout: hit.stdout ?? '',
          stderr: hit.stderr ?? '',
          durationMs: 1,
        };
      }),
    } as unknown as HostExecutor;
  }

  function emptyDb(): YskDatabase {
    return {
      snapshot: { cron_jobs: [], projects: [], settings: {} },
      persist: () => undefined,
    } as unknown as YskDatabase;
  }

  it('scans root and project users when root', async () => {
    const host = mockHost({
      root: {
        exitCode: 0,
        stdout: '0 1 * * * /root/job\n0 3 * * * ysk-server backup all # ysk:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa\n',
      },
      ysks_demo: {
        exitCode: 0,
        stdout: '*/5 * * * * cd /home/ysks_demo/app && php artisan schedule:run\n',
      },
    });
    const cron = new CronJobService(emptyDb(), host, '/tmp/ysk-cron-test');
    const inv = await cron.listHostCrontabs([
      { id: 'p1', name: 'Demo', linuxUser: 'ysks_demo' },
    ]);
    expect(inv.isRoot).toBe(true);
    expect(inv.partial).toBe(false);
    expect(inv.users.map((u) => u.user)).toEqual(['root', 'ysks_demo']);
    const jobs = inv.lines.filter((l) => l.kind === 'job');
    expect(jobs.length).toBe(3);
    expect(jobs.some((j) => j.user === 'ysks_demo' && j.command?.includes('artisan'))).toBe(true);
    expect(jobs.some((j) => j.source === 'ysk')).toBe(true);
  });

  it('non-root only reads process crontab (partial)', async () => {
    const host = mockHost(
      {
        _self: { exitCode: 0, stdout: '0 0 * * * /usr/bin/true\n' },
      },
      { root: false, execute: true },
    );
    const cron = new CronJobService(emptyDb(), host, '/tmp/ysk-cron-test');
    const inv = await cron.listHostCrontabs([
      { id: 'p1', name: 'Demo', linuxUser: 'ysks_demo' },
    ]);
    expect(inv.isRoot).toBe(false);
    expect(inv.partial).toBe(true);
    expect(inv.users).toHaveLength(1);
    expect(inv.lines.filter((l) => l.kind === 'job')).toHaveLength(1);
  });

  it('reads crontab without YSK_EXECUTE', async () => {
    const host = mockHost(
      {
        root: { exitCode: 0, stdout: '0 4 * * * /usr/bin/true\n' },
      },
      { root: true, execute: false },
    );
    const cron = new CronJobService(emptyDb(), host, '/tmp/ysk-cron-test');
    const inv = await cron.listHostCrontabs([]);
    expect(inv.partial).toBe(false);
    expect(inv.lines.some((l) => l.kind === 'job' && l.command?.includes('/usr/bin/true'))).toBe(
      true,
    );
  });
});
