/**
 * Phase 3 hosting remainder: File Server, FTPS, DNS, Firewall, cron, logs, backup, monitoring.
 */

import { ErrorCodes, YskError, tl} from 'ysk-server-shared';

export interface FileServerPlan {
  publicRoot: string;
  apiPrefix: string;
  quotaMb: number;
  commands: string[];
}

export function planPublicFileServer(opts: {
  root?: string;
  quotaMb?: number;
}): FileServerPlan {
  const publicRoot = opts.root ?? '/var/lib/ysk-server/files';
  const quotaMb = opts.quotaMb ?? 1024;
  if (quotaMb < 1) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1511'), { httpStatus: 400 });
  }
  return {
    publicRoot,
    apiPrefix: '/api/v1/files',
    quotaMb,
    commands: [
      `mkdir -p ${publicRoot}`,
      `chown ysk-server:ysk-server ${publicRoot}`,
      `chmod 750 ${publicRoot}`,
    ] };
}

export interface FtpsPlan {
  pasvMin: number;
  pasvMax: number;
  sslCert: string;
  configSnippet: string;
  commands: string[];
}

export function planFtps(opts: { domain: string; pasvMin?: number; pasvMax?: number }): FtpsPlan {
  if (!opts.domain) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n0104'), { httpStatus: 400 });
  }
  const pasvMin = opts.pasvMin ?? 30000;
  const pasvMax = opts.pasvMax ?? 30100;
  const configSnippet = `
# vsftpd FTPS (generated by YSK Server)
listen=YES
ssl_enable=YES
force_local_data_ssl=YES
force_local_logins_ssl=YES
rsa_cert_file=/etc/letsencrypt/live/${opts.domain}/fullchain.pem
rsa_private_key_file=/etc/letsencrypt/live/${opts.domain}/privkey.pem
pasv_min_port=${pasvMin}
pasv_max_port=${pasvMax}
`.trim();
  return {
    pasvMin,
    pasvMax,
    sslCert: `/etc/letsencrypt/live/${opts.domain}/fullchain.pem`,
    configSnippet,
    commands: ['apt-get install -y vsftpd', 'systemctl enable --now vsftpd'] };
}

export interface DnsRecordPlan {
  records: Array<{ type: string; name: string; value: string; ttl: number }>;
  providerHints: string[];
  template: DnsZoneTemplate;
}

/** Zone seed templates (Hestia/DA-style defaults + CDN multi-A ready). */
export type DnsZoneTemplate = 'minimal' | 'web' | 'mail' | 'full' | 'cdn';

export const DNS_ZONE_TEMPLATES: Array<{
  id: DnsZoneTemplate;
  label: string;
  description: string;
}> = [
  { id: 'minimal', label: tl('notes.auto.n0939'), description: tl('notes.auto.n0564') },
  { id: 'web', label: tl('notes.auto.n1315'), description: 'apex + www' },
  { id: 'mail', label: tl('notes.readiness.email'), description: 'apex + mail + MX + SPF' },
  { id: 'full', label: tl('notes.auto.n0659'), description: 'web + mail + ftp + SPF' },
  {
    id: 'cdn',
    label: 'CDN',
    description: tl('notes.auto.n0218') },
];

export function normalizeDnsZoneTemplate(raw?: string | null): DnsZoneTemplate {
  const t = (raw ?? 'full').toLowerCase();
  if (
    t === 'minimal' ||
    t === 'web' ||
    t === 'mail' ||
    t === 'full' ||
    t === 'cdn'
  ) {
    return t;
  }
  return 'full';
}

export function planDnsZone(opts: {
  zone: string;
  serverIp: string;
  /** Optional public IPv6 → AAAA + SPF ip6: */
  serverIpv6?: string;
  mailHost?: string;
  /** minimal | web | mail | full (default full) */
  template?: DnsZoneTemplate | string;
}): DnsRecordPlan {
  if (!opts.zone || !opts.serverIp) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.dns.needZoneServerIp'), { httpStatus: 400 });
  }
  const template = normalizeDnsZoneTemplate(opts.template);
  const mail = opts.mailHost ?? `mail.${opts.zone}`;
  const ttl = 300;
  const ip = opts.serverIp;
  const ip6 = opts.serverIpv6?.trim() || undefined;
  const records: DnsRecordPlan['records'] = [];

  // Always apex A for usable zone (except we still want apex for all templates)
  records.push({ type: 'A', name: '@', value: ip, ttl });
  if (ip6) records.push({ type: 'AAAA', name: '@', value: ip6, ttl });

  if (template === 'web' || template === 'full' || template === 'cdn') {
    records.push({ type: 'A', name: 'www', value: ip, ttl });
    if (ip6) records.push({ type: 'AAAA', name: 'www', value: ip6, ttl });
  }
  if (template === 'cdn') {
    // Edge hostname placeholder — multi-A will be managed by CDN planner later
    records.push({ type: 'A', name: 'cdn', value: ip, ttl });
    if (ip6) records.push({ type: 'AAAA', name: 'cdn', value: ip6, ttl });
    records.push({
      type: 'TXT',
      name: '_ysk-cdn',
      value: 'ysk-cdn-ready v1',
      ttl });
  }
  if (template === 'mail' || template === 'full') {
    records.push({ type: 'A', name: 'mail', value: ip, ttl });
    if (ip6) records.push({ type: 'AAAA', name: 'mail', value: ip6, ttl });
    records.push({ type: 'MX', name: '@', value: `10 ${mail}.`, ttl });
    const spf = ip6
      ? `v=spf1 a mx ip4:${ip} ip6:${ip6} ~all`
      : `v=spf1 a mx ip4:${ip} ~all`;
    records.push({
      type: 'TXT',
      name: '@',
      value: spf,
      ttl });
  }
  if (template === 'full') {
    records.push({ type: 'A', name: 'ftp', value: ip, ttl });
    if (ip6) records.push({ type: 'AAAA', name: 'ftp', value: ip6, ttl });
  }

  return {
    template,
    records,
    providerHints: [
      'Managed zone file is not live until nameserver loads it',
      'External DNS: copy these records to your provider',
      ...(ip6 ? ['IPv6 AAAA records included for dual-stack'] : []),
      ...(template === 'cdn'
        ? [
            'CDN template: multi-edge IPs should be added as additional A/AAAA on @ / www / cdn',
            'Use CDN module later for health-based multi-A (managedBy=cdn)',
          ]
        : []),
    ] };
}

export interface FirewallPlan {
  rules: string[];
  fail2banJails: string[];
  commands: string[];
}

/**
 * Prefer extraPortSpecs ("21", "30000:30100") → one UFW rule per range.
 * extraTcpPorts still accepted for legacy callers (one rule per number).
 */
export function planFirewall(opts: {
  allowSsh?: boolean;
  allowHttp?: boolean;
  allowHttps?: boolean;
  allowSmtp?: boolean;
  extraTcpPorts?: number[];
  /** e.g. ["21", "990", "30000:30100"] — FTPS PASV as a single range rule */
  extraPortSpecs?: string[];
}): FirewallPlan {
  const rules: string[] = ['ufw default deny incoming', 'ufw default allow outgoing'];
  if (opts.allowSsh !== false) rules.push('ufw allow OpenSSH');
  if (opts.allowHttp !== false) rules.push('ufw allow 80/tcp');
  if (opts.allowHttps !== false) rules.push('ufw allow 443/tcp');
  if (opts.allowSmtp) {
    rules.push('ufw allow 25/tcp', 'ufw allow 587/tcp', 'ufw allow 465/tcp', 'ufw allow 993/tcp');
  }
  const specs = opts.extraPortSpecs?.length
    ? opts.extraPortSpecs
    : (opts.extraTcpPorts ?? []).map((p) => String(p));
  for (const raw of specs) {
    const s = String(raw ?? '').trim();
    if (!s) continue;
    // Validate single or range (max span 200 — same as firewallAllowPort)
    if (s.includes(':')) {
      const [a, b] = s.split(':').map((x) => Number(x.trim()));
      if (!Number.isInteger(a) || !Number.isInteger(b) || a! < 1 || b! < 1 || a! > 65535 || b! > 65535) {
        throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.t0358', { v0: s }), {
          httpStatus: 400,
        });
      }
      const lo = Math.min(a!, b!);
      const hi = Math.max(a!, b!);
      if (hi - lo > 200) {
        throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1113'), { httpStatus: 400 });
      }
      rules.push(`ufw allow ${lo}:${hi}/tcp`);
    } else {
      const p = Number(s);
      if (!Number.isInteger(p) || p < 1 || p > 65535) {
        throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.t0358', { v0: s }), {
          httpStatus: 400,
        });
      }
      rules.push(`ufw allow ${p}/tcp`);
    }
  }
  rules.push('ufw --force enable');
  // UFW only — fail2ban is a separate stack (do not couple install into firewall apply)
  return {
    rules,
    fail2banJails: [
      'sshd',
      'nginx-http-auth',
      'nginx-botsearch',
      'nginx-badbots',
      'nginx-limit-req',
      'postfix',
      'dovecot',
    ],
    commands: [...rules] };
}

/**
 * Validate standard 5-field cron schedule (minute hour dom mon dow).
 * Rejects newlines / carriage returns (crontab injection).
 */
export function assertSafeCronSchedule(schedule: string): string {
  const s = schedule.trim();
  if (!s || /[\r\n]/.test(s)) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1396'), { httpStatus: 400 });
  }
  // 5 fields: allow numbers, *, /, -, ,, ranges
  const fields = s.split(/\s+/);
  if (fields.length !== 5) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1396'), {
      httpStatus: 400,
      details: { reason: 'cron_schedule_fields', got: fields.length },
    });
  }
  for (const f of fields) {
    if (!/^[0-9*,\/\-]+$/.test(f) && !/^(sun|mon|tue|wed|thu|fri|sat)(-(sun|mon|tue|wed|thu|fri|sat))?$/i.test(f)) {
      // allow month names abbreviated
      if (!/^(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)(-(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec))?$/i.test(f)) {
        throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1396'), {
          httpStatus: 400,
          details: { reason: 'cron_schedule_field', field: f },
        });
      }
    }
  }
  return s;
}

/** Reject crontab line injection in command body. */
export function assertSafeCronCommand(command: string): string {
  const c = command.trim();
  if (!c || /[\r\n]/.test(c)) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1396'), {
      httpStatus: 400,
      details: { reason: 'cron_command_injection' },
    });
  }
  if (/(?<!\\)%/.test(c)) {
    throw new YskError(
      ErrorCodes.VALIDATION,
      'crontab treats unescaped % as a newline. Write date formats as \\%Y (or avoid %).',
      {
        httpStatus: 400,
        details: { reason: 'cron_percent_newline' },
      },
    );
  }
  if (c.length > 4000) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1396'), {
      httpStatus: 400,
      details: { reason: 'cron_command_too_long' },
    });
  }
  return c;
}

export function planCronJob(opts: {
  user: string;
  schedule: string;
  command: string;
}): { crontabLine: string; notes: string[] } {
  if (!opts.user || !opts.schedule || !opts.command) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1396'), {
      httpStatus: 400 });
  }
  const schedule = assertSafeCronSchedule(opts.schedule);
  const command = assertSafeCronCommand(opts.command);
  const user = opts.user.trim();
  if (!/^[a-zA-Z0-9_.-]+$/.test(user)) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1396'), { httpStatus: 400 });
  }
  return {
    crontabLine: `${schedule} ${command} # ysk-server`,
    notes: [tl('notes.auto.t0359', { v0: (user) }), tl('notes.auto.n0916')] };
}

export function planBackup(opts: {
  projectId: string;
  sources: string[];
  dest: string;
}): { commands: string[]; notes: string[] } {
  if (!opts.sources.length) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1405'), { httpStatus: 400 });
  }
  const stamp = '${STAMP}';
  return {
    commands: [
      `STAMP=$(date +%Y%m%d%H%M%S)`,
      `mkdir -p ${opts.dest}/${opts.projectId}`,
      `tar -czf ${opts.dest}/${opts.projectId}/backup-${stamp}.tar.gz ${opts.sources.join(' ')}`,
    ],
    notes: [tl('notes.auto.n0838'), tl('notes.auto.n1453')] };
}

export function planMonitoringChecks(projectId: string): {
  checks: Array<{ name: string; type: string; target: string }>;
} {
  return {
    checks: [
      { name: 'http', type: 'http', target: `project:${projectId}` },
      { name: 'disk', type: 'disk', target: '/' },
      { name: 'memory', type: 'memory', target: 'host' },
      { name: 'load', type: 'load', target: 'host' },
    ] };
}

export function planLogPaths(projectHome: string): { app: string; access: string; error: string } {
  return {
    app: `${projectHome}/logs/app.log`,
    access: `${projectHome}/logs/access.log`,
    error: `${projectHome}/logs/error.log` };
}
