/**
 * Phase 3 hosting remainder: File Server, FTPS, DNS, Firewall, cron, logs, backup, monitoring.
 */

import { ErrorCodes, YskError } from '@ysk/shared';

export interface FileServerPlan {
  publicRoot: string;
  apiPrefix: string;
  quotaMb: number;
  commands: string[];
}

export function planPublicFileServer(opts: {
  root?: string;
  quotaMb?: number;
}): FileServerPlan {
  const publicRoot = opts.root ?? '/var/lib/ysk-server/files';
  const quotaMb = opts.quotaMb ?? 1024;
  if (quotaMb < 1) {
    throw new YskError(ErrorCodes.VALIDATION, 'quotaMb must be >= 1', { httpStatus: 400 });
  }
  return {
    publicRoot,
    apiPrefix: '/api/v1/files',
    quotaMb,
    commands: [
      `mkdir -p ${publicRoot}`,
      `chown ysk-server:ysk-server ${publicRoot}`,
      `chmod 750 ${publicRoot}`,
    ],
  };
}

export interface FtpsPlan {
  pasvMin: number;
  pasvMax: number;
  sslCert: string;
  configSnippet: string;
  commands: string[];
}

export function planFtps(opts: { domain: string; pasvMin?: number; pasvMax?: number }): FtpsPlan {
  if (!opts.domain) {
    throw new YskError(ErrorCodes.VALIDATION, 'domain required for FTPS', { httpStatus: 400 });
  }
  const pasvMin = opts.pasvMin ?? 30000;
  const pasvMax = opts.pasvMax ?? 30100;
  const configSnippet = `
# vsftpd FTPS (generated by YSK Server)
listen=YES
ssl_enable=YES
force_local_data_ssl=YES
force_local_logins_ssl=YES
rsa_cert_file=/etc/letsencrypt/live/${opts.domain}/fullchain.pem
rsa_private_key_file=/etc/letsencrypt/live/${opts.domain}/privkey.pem
pasv_min_port=${pasvMin}
pasv_max_port=${pasvMax}
`.trim();
  return {
    pasvMin,
    pasvMax,
    sslCert: `/etc/letsencrypt/live/${opts.domain}/fullchain.pem`,
    configSnippet,
    commands: ['apt-get install -y vsftpd', 'systemctl enable --now vsftpd'],
  };
}

export interface DnsRecordPlan {
  records: Array<{ type: string; name: string; value: string; ttl: number }>;
  providerHints: string[];
}

export function planDnsZone(opts: {
  zone: string;
  serverIp: string;
  mailHost?: string;
}): DnsRecordPlan {
  if (!opts.zone || !opts.serverIp) {
    throw new YskError(ErrorCodes.VALIDATION, 'zone and serverIp required', { httpStatus: 400 });
  }
  const mail = opts.mailHost ?? `mail.${opts.zone}`;
  return {
    records: [
      { type: 'A', name: '@', value: opts.serverIp, ttl: 300 },
      { type: 'A', name: 'mail', value: opts.serverIp, ttl: 300 },
      { type: 'MX', name: '@', value: `10 ${mail}.`, ttl: 300 },
    ],
    providerHints: [
      'PowerDNS API or Cloudflare API can apply these records',
      'If using Cloudflare, set MX-related records to DNS-only (grey cloud)',
    ],
  };
}

export interface FirewallPlan {
  rules: string[];
  fail2banJails: string[];
  commands: string[];
}

export function planFirewall(opts: {
  allowSsh?: boolean;
  allowHttp?: boolean;
  allowHttps?: boolean;
  allowSmtp?: boolean;
  extraTcpPorts?: number[];
}): FirewallPlan {
  const rules: string[] = ['ufw default deny incoming', 'ufw default allow outgoing'];
  if (opts.allowSsh !== false) rules.push('ufw allow OpenSSH');
  if (opts.allowHttp !== false) rules.push('ufw allow 80/tcp');
  if (opts.allowHttps !== false) rules.push('ufw allow 443/tcp');
  if (opts.allowSmtp) {
    rules.push('ufw allow 25/tcp', 'ufw allow 587/tcp', 'ufw allow 465/tcp', 'ufw allow 993/tcp');
  }
  for (const p of opts.extraTcpPorts ?? []) {
    if (!Number.isInteger(p) || p < 1 || p > 65535) {
      throw new YskError(ErrorCodes.VALIDATION, `Invalid port ${p}`, { httpStatus: 400 });
    }
    rules.push(`ufw allow ${p}/tcp`);
  }
  rules.push('ufw --force enable');
  return {
    rules,
    fail2banJails: ['sshd', 'nginx-http-auth', 'postfix', 'dovecot'],
    commands: [...rules, 'apt-get install -y fail2ban', 'systemctl enable --now fail2ban'],
  };
}

export function planCronJob(opts: {
  user: string;
  schedule: string;
  command: string;
}): { crontabLine: string; notes: string[] } {
  if (!opts.user || !opts.schedule || !opts.command) {
    throw new YskError(ErrorCodes.VALIDATION, 'user, schedule, command required', {
      httpStatus: 400,
    });
  }
  return {
    crontabLine: `${opts.schedule} ${opts.command} # ysk-server`,
    notes: [`Install via crontab -u ${opts.user}`, 'Logs should go under project logs dir'],
  };
}

export function planBackup(opts: {
  projectId: string;
  sources: string[];
  dest: string;
}): { commands: string[]; notes: string[] } {
  if (!opts.sources.length) {
    throw new YskError(ErrorCodes.VALIDATION, 'backup sources required', { httpStatus: 400 });
  }
  const stamp = '${STAMP}';
  return {
    commands: [
      `STAMP=$(date +%Y%m%d%H%M%S)`,
      `mkdir -p ${opts.dest}/${opts.projectId}`,
      `tar -czf ${opts.dest}/${opts.projectId}/backup-${stamp}.tar.gz ${opts.sources.join(' ')}`,
    ],
    notes: ['Retention policy should prune old archives', 'DB dumps should be included separately'],
  };
}

export function planMonitoringChecks(projectId: string): {
  checks: Array<{ name: string; type: string; target: string }>;
} {
  return {
    checks: [
      { name: 'http', type: 'http', target: `project:${projectId}` },
      { name: 'disk', type: 'disk', target: '/' },
      { name: 'memory', type: 'memory', target: 'host' },
      { name: 'load', type: 'load', target: 'host' },
    ],
  };
}

export function planLogPaths(projectHome: string): { app: string; access: string; error: string } {
  return {
    app: `${projectHome}/logs/app.log`,
    access: `${projectHome}/logs/access.log`,
    error: `${projectHome}/logs/error.log`,
  };
}
