/**
 * Phase 3 hosting remainder: File Server, FTPS, DNS, Firewall, cron, logs, backup, monitoring.
 */

import { ErrorCodes, YskError } from '@ysk/shared';

export interface FileServerPlan {
  publicRoot: string;
  apiPrefix: string;
  quotaMb: number;
  commands: string[];
}

export function planPublicFileServer(opts: {
  root?: string;
  quotaMb?: number;
}): FileServerPlan {
  const publicRoot = opts.root ?? '/var/lib/ysk-server/files';
  const quotaMb = opts.quotaMb ?? 1024;
  if (quotaMb < 1) {
    throw new YskError(ErrorCodes.VALIDATION, '配額須至少 1 MiB', { httpStatus: 400 });
  }
  return {
    publicRoot,
    apiPrefix: '/api/v1/files',
    quotaMb,
    commands: [
      `mkdir -p ${publicRoot}`,
      `chown ysk-server:ysk-server ${publicRoot}`,
      `chmod 750 ${publicRoot}`,
    ],
  };
}

export interface FtpsPlan {
  pasvMin: number;
  pasvMax: number;
  sslCert: string;
  configSnippet: string;
  commands: string[];
}

export function planFtps(opts: { domain: string; pasvMin?: number; pasvMax?: number }): FtpsPlan {
  if (!opts.domain) {
    throw new YskError(ErrorCodes.VALIDATION, 'FTPS 需要域名', { httpStatus: 400 });
  }
  const pasvMin = opts.pasvMin ?? 30000;
  const pasvMax = opts.pasvMax ?? 30100;
  const configSnippet = `
# vsftpd FTPS (generated by YSK Server)
listen=YES
ssl_enable=YES
force_local_data_ssl=YES
force_local_logins_ssl=YES
rsa_cert_file=/etc/letsencrypt/live/${opts.domain}/fullchain.pem
rsa_private_key_file=/etc/letsencrypt/live/${opts.domain}/privkey.pem
pasv_min_port=${pasvMin}
pasv_max_port=${pasvMax}
`.trim();
  return {
    pasvMin,
    pasvMax,
    sslCert: `/etc/letsencrypt/live/${opts.domain}/fullchain.pem`,
    configSnippet,
    commands: ['apt-get install -y vsftpd', 'systemctl enable --now vsftpd'],
  };
}

export interface DnsRecordPlan {
  records: Array<{ type: string; name: string; value: string; ttl: number }>;
  providerHints: string[];
  template: DnsZoneTemplate;
}

/** Zone seed templates (Hestia/DA-style defaults). */
export type DnsZoneTemplate = 'minimal' | 'web' | 'mail' | 'full';

export const DNS_ZONE_TEMPLATES: Array<{
  id: DnsZoneTemplate;
  label: string;
  description: string;
}> = [
  { id: 'minimal', label: '最小', description: '僅 apex A' },
  { id: 'web', label: '網站', description: 'apex + www' },
  { id: 'mail', label: '郵件', description: 'apex + mail + MX + SPF' },
  { id: 'full', label: '完整', description: 'web + mail + ftp + SPF' },
];

export function normalizeDnsZoneTemplate(raw?: string | null): DnsZoneTemplate {
  const t = (raw ?? 'full').toLowerCase();
  if (t === 'minimal' || t === 'web' || t === 'mail' || t === 'full') return t;
  return 'full';
}

export function planDnsZone(opts: {
  zone: string;
  serverIp: string;
  mailHost?: string;
  /** minimal | web | mail | full (default full) */
  template?: DnsZoneTemplate | string;
}): DnsRecordPlan {
  if (!opts.zone || !opts.serverIp) {
    throw new YskError(ErrorCodes.VALIDATION, '請填寫 zone 與 server IP', { httpStatus: 400 });
  }
  const template = normalizeDnsZoneTemplate(opts.template);
  const mail = opts.mailHost ?? `mail.${opts.zone}`;
  const ttl = 300;
  const ip = opts.serverIp;
  const records: DnsRecordPlan['records'] = [];

  // Always apex A for usable zone (except we still want apex for all templates)
  records.push({ type: 'A', name: '@', value: ip, ttl });

  if (template === 'web' || template === 'full') {
    records.push({ type: 'A', name: 'www', value: ip, ttl });
  }
  if (template === 'mail' || template === 'full') {
    records.push({ type: 'A', name: 'mail', value: ip, ttl });
    records.push({ type: 'MX', name: '@', value: `10 ${mail}.`, ttl });
    records.push({
      type: 'TXT',
      name: '@',
      value: `v=spf1 a mx ip4:${ip} ~all`,
      ttl,
    });
  }
  if (template === 'full') {
    records.push({ type: 'A', name: 'ftp', value: ip, ttl });
  }

  return {
    template,
    records,
    providerHints: [
      'Managed zone file is not live until nameserver loads it',
      'External DNS: copy these records to your provider',
    ],
  };
}

export interface FirewallPlan {
  rules: string[];
  fail2banJails: string[];
  commands: string[];
}

export function planFirewall(opts: {
  allowSsh?: boolean;
  allowHttp?: boolean;
  allowHttps?: boolean;
  allowSmtp?: boolean;
  extraTcpPorts?: number[];
}): FirewallPlan {
  const rules: string[] = ['ufw default deny incoming', 'ufw default allow outgoing'];
  if (opts.allowSsh !== false) rules.push('ufw allow OpenSSH');
  if (opts.allowHttp !== false) rules.push('ufw allow 80/tcp');
  if (opts.allowHttps !== false) rules.push('ufw allow 443/tcp');
  if (opts.allowSmtp) {
    rules.push('ufw allow 25/tcp', 'ufw allow 587/tcp', 'ufw allow 465/tcp', 'ufw allow 993/tcp');
  }
  for (const p of opts.extraTcpPorts ?? []) {
    if (!Number.isInteger(p) || p < 1 || p > 65535) {
      throw new YskError(ErrorCodes.VALIDATION, `埠號無效：${p}`, { httpStatus: 400 });
    }
    rules.push(`ufw allow ${p}/tcp`);
  }
  rules.push('ufw --force enable');
  // UFW only — fail2ban is a separate stack (do not couple install into firewall apply)
  return {
    rules,
    fail2banJails: [
      'sshd',
      'nginx-http-auth',
      'nginx-botsearch',
      'nginx-badbots',
      'nginx-limit-req',
      'postfix',
      'dovecot',
    ],
    commands: [...rules],
  };
}

export function planCronJob(opts: {
  user: string;
  schedule: string;
  command: string;
}): { crontabLine: string; notes: string[] } {
  if (!opts.user || !opts.schedule || !opts.command) {
    throw new YskError(ErrorCodes.VALIDATION, '請填寫用戶、排程與指令', {
      httpStatus: 400,
    });
  }
  return {
    crontabLine: `${opts.schedule} ${opts.command} # ysk-server`,
    notes: [`以用戶 ${opts.user} 安裝 crontab`, '日誌建議寫入專案 logs 目錄'],
  };
}

export function planBackup(opts: {
  projectId: string;
  sources: string[];
  dest: string;
}): { commands: string[]; notes: string[] } {
  if (!opts.sources.length) {
    throw new YskError(ErrorCodes.VALIDATION, '請指定備份來源', { httpStatus: 400 });
  }
  const stamp = '${STAMP}';
  return {
    commands: [
      `STAMP=$(date +%Y%m%d%H%M%S)`,
      `mkdir -p ${opts.dest}/${opts.projectId}`,
      `tar -czf ${opts.dest}/${opts.projectId}/backup-${stamp}.tar.gz ${opts.sources.join(' ')}`,
    ],
    notes: ['應設定保留策略清理舊備份', '資料庫轉儲需另行納入'],
  };
}

export function planMonitoringChecks(projectId: string): {
  checks: Array<{ name: string; type: string; target: string }>;
} {
  return {
    checks: [
      { name: 'http', type: 'http', target: `project:${projectId}` },
      { name: 'disk', type: 'disk', target: '/' },
      { name: 'memory', type: 'memory', target: 'host' },
      { name: 'load', type: 'load', target: 'host' },
    ],
  };
}

export function planLogPaths(projectHome: string): { app: string; access: string; error: string } {
  return {
    app: `${projectHome}/logs/app.log`,
    access: `${projectHome}/logs/access.log`,
    error: `${projectHome}/logs/error.log`,
  };
}
