/**
 * fail2ban deep operations — log-driven temporary bans / jails.
 * Distinct from UFW (port policy) and Defense Center (attack orchestration).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { HostExecutor } from '../host/executor.js';
import { probeFail2banStatus, fail2banBannedIps, fail2banUnban } from './system-apply.js';

export const FAIL2BAN_JAIL_CATALOG: Array<{
  id: string;
  label: string;
  desc: string;
  group: 'ssh' | 'web' | 'mail' | 'other';
}> = [
  { id: 'sshd', label: 'SSH', desc: 'SSH 暴力破解', group: 'ssh' },
  { id: 'nginx-http-auth', label: 'Nginx Auth', desc: 'HTTP 基本認證失敗', group: 'web' },
  { id: 'nginx-botsearch', label: 'Bot 掃描', desc: '常見漏洞路徑掃描', group: 'web' },
  { id: 'nginx-badbots', label: '壞 Bot', desc: '已知惡意 UA', group: 'web' },
  { id: 'nginx-limit-req', label: '限速越界', desc: '觸發 limit_req 過多', group: 'web' },
  { id: 'postfix', label: 'Postfix', desc: 'SMTP 濫用／暴力', group: 'mail' },
  { id: 'dovecot', label: 'Dovecot', desc: 'IMAP／POP 登入失敗', group: 'mail' },
  { id: 'recidive', label: '累犯', desc: '重複被 ban 再加重', group: 'other' },
];

export type Fail2banPolicy = {
  bantime: string;
  findtime: string;
  maxretry: number;
  jails: string[];
};

export const DEFAULT_F2B_POLICY: Fail2banPolicy = {
  bantime: '1h',
  findtime: '10m',
  maxretry: 5,
  jails: ['sshd', 'nginx-http-auth', 'postfix', 'dovecot'],
};

export async function fail2banService(
  host: HostExecutor,
  action: 'start' | 'stop' | 'restart' | 'reload' | 'enable',
): Promise<{ ok: boolean; notes: string[]; blocked?: boolean }> {
  if (!host.executeEnabled()) {
    return { ok: false, blocked: true, notes: ['需 YSK_EXECUTE 才能控制 fail2ban 服務'] };
  }
  if (action === 'enable') {
    const r = await host.runCommand(['systemctl', 'enable', '--now', 'fail2ban'], {
      timeoutMs: 30_000,
    });
    return {
      ok: r.exitCode === 0,
      notes: [
        r.exitCode === 0
          ? '已 enable --now fail2ban'
          : `失敗：${(r.stderr || r.stdout || '').slice(0, 300)}`,
      ],
    };
  }
  const r = await host.runCommand(['systemctl', action, 'fail2ban'], { timeoutMs: 30_000 });
  return {
    ok: r.exitCode === 0,
    notes: [
      r.exitCode === 0
        ? `systemctl ${action} fail2ban 成功`
        : `${action} 失敗：${(r.stderr || r.stdout || '').slice(0, 300)}`,
    ],
  };
}

export async function fail2banBanIp(
  host: HostExecutor,
  jail: string,
  ip: string,
): Promise<{ ok: boolean; notes: string[]; blocked?: boolean }> {
  if (!host.executeEnabled()) {
    return { ok: false, blocked: true, notes: ['需 YSK_EXECUTE 才能 banip'] };
  }
  const safeJail = jail.replace(/[^a-zA-Z0-9._-]/g, '') || 'sshd';
  const safeIp = ip.trim();
  if (!/^(\d{1,3}\.){3}\d{1,3}$/.test(safeIp) && !safeIp.includes(':')) {
    return { ok: false, notes: ['無效 IP'] };
  }
  const r = await host.runCommand(
    ['fail2ban-client', 'set', safeJail, 'banip', safeIp],
    { timeoutMs: 10_000 },
  );
  return {
    ok: r.exitCode === 0,
    notes: [
      r.exitCode === 0
        ? `fail2ban ban ${safeIp} @ ${safeJail}（臨時，受 bantime 限制）`
        : `banip 失敗：${(r.stderr || r.stdout || '').slice(0, 300)}`,
    ],
  };
}

export function readIgnoreIpList(dataDir: string): string[] {
  const listPath = join(dataDir, 'fail2ban', 'ignoreip.txt');
  if (!existsSync(listPath)) return [];
  try {
    return readFileSync(listPath, 'utf8')
      .split(/\n/)
      .map((s) => s.trim())
      .filter(Boolean);
  } catch {
    return [];
  }
}

export function writeFail2banJailLocal(
  dataDir: string,
  policy: Fail2banPolicy,
): { path: string; body: string } {
  const dir = join(dataDir, 'fail2ban');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'jail.local');
  const jails = policy.jails.length ? policy.jails : DEFAULT_F2B_POLICY.jails;
  const bantime = sanitizeDuration(policy.bantime, '1h');
  const findtime = sanitizeDuration(policy.findtime, '10m');
  const maxretry = Math.max(1, Math.min(50, Math.floor(policy.maxretry || 5)));
  const ignore = readIgnoreIpList(dataDir);
  const ignoreLine =
    ignore.length > 0 ? `ignoreip = 127.0.0.1/8 ::1 ${ignore.join(' ')}` : 'ignoreip = 127.0.0.1/8 ::1';
  const body = [
    '# Generated by YSK Server — fail2ban jail.local',
    '[DEFAULT]',
    `bantime = ${bantime}`,
    `findtime = ${findtime}`,
    `maxretry = ${maxretry}`,
    ignoreLine,
    'backend = systemd',
    '',
    ...jails.flatMap((j) => {
      const safe = j.replace(/[^a-zA-Z0-9._-]/g, '');
      return safe ? [`[${safe}]`, 'enabled = true', ''] : [];
    }),
  ].join('\n');
  writeFileSync(path, body, 'utf8');
  return { path, body };
}

function sanitizeDuration(v: string, fallback: string): string {
  const s = (v || '').trim();
  if (/^\d+[smhdw]?$/i.test(s)) return s;
  return fallback;
}

/**
 * Apply policy to management jail.local; optional system copy + reload.
 */
export async function applyFail2banPolicy(input: {
  dataDir: string;
  host: HostExecutor;
  policy: Fail2banPolicy;
  apply: boolean;
}): Promise<{
  ok: boolean;
  blocked?: boolean;
  written: string[];
  notes: string[];
  requiresExecute?: boolean;
  requiresRoot?: boolean;
  apply_status: 'written' | 'applied' | 'blocked' | 'failed';
}> {
  const { path } = writeFail2banJailLocal(input.dataDir, input.policy);
  const notes = [
    `已寫 ${path}`,
    `jails: ${input.policy.jails.join(', ') || '(無)'}`,
    `bantime=${input.policy.bantime} findtime=${input.policy.findtime} maxretry=${input.policy.maxretry}`,
    `ignoreip 來源：dataDir/fail2ban/ignoreip.txt`,
  ];
  const written = [path];
  if (!input.apply) {
    return {
      ok: true,
      written,
      notes: [...notes, '狀態：written（預覽／只寫管理檔）'],
      apply_status: 'written',
    };
  }
  const can = input.host.executeEnabled() && input.host.isRoot();
  if (!can) {
    return {
      ok: false,
      blocked: true,
      written,
      notes: [...notes, '未套用到系統：需 YSK_EXECUTE + root'],
      requiresExecute: !input.host.executeEnabled(),
      requiresRoot: !input.host.isRoot(),
      apply_status: 'blocked',
    };
  }
  // ensure package
  const install = await input.host.runCommand(
    [
      'bash',
      '-c',
      'command -v fail2ban-client >/dev/null || (DEBIAN_FRONTEND=noninteractive apt-get install -y fail2ban)',
    ],
    { timeoutMs: 180_000 },
  );
  if (install.exitCode !== 0) {
    notes.push(`安裝檢查：${(install.stderr || install.stdout || '').slice(0, 200)}`);
  }
  const cp = await input.host.runCommand(['cp', path, '/etc/fail2ban/jail.local'], {
    timeoutMs: 10_000,
  });
  notes.push(cp.exitCode === 0 ? '已複製到 /etc/fail2ban/jail.local' : '複製 jail.local 失敗');
  const en = await input.host.runCommand(['systemctl', 'enable', '--now', 'fail2ban'], {
    timeoutMs: 30_000,
  });
  notes.push(en.exitCode === 0 ? 'fail2ban enable --now' : 'enable 失敗');
  const rel = await input.host.runCommand(['systemctl', 'reload', 'fail2ban'], {
    timeoutMs: 15_000,
  });
  // reload may fail if never started — try restart
  if (rel.exitCode !== 0) {
    const rst = await input.host.runCommand(['systemctl', 'restart', 'fail2ban'], {
      timeoutMs: 30_000,
    });
    notes.push(rst.exitCode === 0 ? '已 restart fail2ban' : 'reload/restart 失敗');
    const ok = cp.exitCode === 0 && (en.exitCode === 0 || rst.exitCode === 0);
    return {
      ok,
      written,
      notes: [...notes, ok ? '狀態：applied' : '狀態：failed'],
      apply_status: ok ? 'applied' : 'failed',
    };
  }
  notes.push('已 reload fail2ban');
  const ok = cp.exitCode === 0;
  return {
    ok,
    written,
    notes: [...notes, ok ? '狀態：applied' : '狀態：failed'],
    apply_status: ok ? 'applied' : 'failed',
  };
}

export async function getFail2banDeepStatus(input: {
  host: HostExecutor;
  dataDir: string;
}): Promise<{
  installed: boolean;
  active: string;
  enabled: string;
  activeLabel: string;
  jails: Array<{ name: string; currentlyBanned?: number; totalBanned?: number }>;
  banned: Array<{ jail: string; ip: string }>;
  ignoreIps: string[];
  catalog: typeof FAIL2BAN_JAIL_CATALOG;
  executeEnabled: boolean;
  isRoot: boolean;
  notes: string[];
}> {
  const st = await probeFail2banStatus(input.host);
  const ignoreIps = readIgnoreIpList(input.dataDir);
  let banned: Array<{ jail: string; ip: string }> = [];
  const notes: string[] = [];
  try {
    // Prefer read even without execute — client often works for status
    if (st.installed) {
      const r = await fail2banBannedIps(input.host);
      banned = r.items ?? [];
      if (r.blocked) notes.push(...(r.notes ?? []));
    }
  } catch {
    notes.push('讀取 banned 列表失敗');
  }
  const activeLabel =
    !st.installed
      ? '未安裝'
      : st.active === 'active'
        ? '運作中'
        : st.active === 'inactive'
          ? '未運行'
          : st.active || '未知';

  return {
    installed: st.installed,
    active: st.active,
    enabled: st.enabled,
    activeLabel,
    jails: st.jails,
    banned,
    ignoreIps,
    catalog: FAIL2BAN_JAIL_CATALOG,
    executeEnabled: st.executeEnabled,
    isRoot: st.isRoot,
    notes,
  };
}

export { fail2banBannedIps, fail2banUnban, probeFail2banStatus };
