import { tl } from '@ysk/shared';
/**
 * fail2ban deep operations — log-driven temporary bans / jails.
 * Distinct from UFW (port policy) and Defense Center (attack orchestration).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { HostExecutor } from '../host/executor.js';
import { probeFail2banStatus, fail2banBannedIps, fail2banUnban } from './system-apply.js';
import { shellEnsureAptPackage } from './software-probe/index.js';

export const FAIL2BAN_JAIL_CATALOG: Array<{
  id: string;
  label: string;
  desc: string;
  group: 'ssh' | 'web' | 'mail' | 'other';
}> = [
  { id: 'sshd', label: 'SSH', desc: tl('notes.auto.n0185'), group: 'ssh' },
  { id: 'nginx-http-auth', label: 'Nginx Auth', desc: tl('notes.auto.n0115'), group: 'web' },
  { id: 'nginx-botsearch', label: tl('notes.auto.n0084'), desc: tl('notes.auto.n0817'), group: 'web' },
  { id: 'nginx-badbots', label: tl('notes.auto.n0637'), desc: tl('notes.auto.n0793'), group: 'web' },
  { id: 'nginx-limit-req', label: tl('notes.auto.n1532'), desc: tl('notes.auto.n1352'), group: 'web' },
  { id: 'postfix', label: 'Postfix', desc: tl('notes.auto.n0182'), group: 'mail' },
  { id: 'dovecot', label: 'Dovecot', desc: tl('notes.auto.n0117'), group: 'mail' },
  { id: 'recidive', label: tl('notes.auto.n1313'), desc: tl('notes.auto.n1513'), group: 'other' },
];

export type Fail2banPolicy = {
  bantime: string;
  findtime: string;
  maxretry: number;
  jails: string[];
};

export const DEFAULT_F2B_POLICY: Fail2banPolicy = {
  bantime: '1h',
  findtime: '10m',
  maxretry: 5,
  jails: ['sshd', 'nginx-http-auth', 'postfix', 'dovecot'] };

export async function fail2banService(
  host: HostExecutor,
  action: 'start' | 'stop' | 'restart' | 'reload' | 'enable',
): Promise<{ ok: boolean; notes: string[]; blocked?: boolean }> {
  if (!host.executeEnabled()) {
    return { ok: false, blocked: true, notes: [tl('notes.auto.n1542')] };
  }
  if (action === 'enable') {
    const r = await host.runCommand(['systemctl', 'enable', '--now', 'fail2ban'], {
      timeoutMs: 30_000 });
    return {
      ok: r.exitCode === 0,
      notes: [
        r.exitCode === 0
          ? tl('notes.auto.n0723')
          : tl('notes.tpl.failedDetail', { detail: (r.stderr || r.stdout || '').slice(0, 300) }),
      ] };
  }
  const r = await host.runCommand(['systemctl', action, 'fail2ban'], { timeoutMs: 30_000 });
  return {
    ok: r.exitCode === 0,
    notes: [
      r.exitCode === 0
        ? tl('notes.auto.t0295', { v0: (action) })
        : tl('notes.auto.t0296', { v0: (action), v1: ((r.stderr || r.stdout || '').slice(0, 300)) }),
    ] };
}

export async function fail2banBanIp(
  host: HostExecutor,
  jail: string,
  ip: string,
): Promise<{ ok: boolean; notes: string[]; blocked?: boolean }> {
  if (!host.executeEnabled()) {
    return { ok: false, blocked: true, notes: [tl('notes.auto.n1541')] };
  }
  const safeJail = jail.replace(/[^a-zA-Z0-9._-]/g, '') || 'sshd';
  const safeIp = ip.trim();
  if (!/^(\d{1,3}\.){3}\d{1,3}$/.test(safeIp) && !safeIp.includes(':')) {
    return { ok: false, notes: [tl('notes.invalidIp')] };
  }
  const r = await host.runCommand(
    ['fail2ban-client', 'set', safeJail, 'banip', safeIp],
    { timeoutMs: 10_000 },
  );
  return {
    ok: r.exitCode === 0,
    notes: [
      r.exitCode === 0
        ? tl('notes.auto.t0297', { v0: (safeIp), v1: (safeJail) })
        : tl('notes.auto.t0298', { v0: ((r.stderr || r.stdout || '').slice(0, 300)) }),
    ] };
}

export function readIgnoreIpList(dataDir: string): string[] {
  const listPath = join(dataDir, 'fail2ban', 'ignoreip.txt');
  if (!existsSync(listPath)) return [];
  try {
    return readFileSync(listPath, 'utf8')
      .split(/\n/)
      .map((s) => s.trim())
      .filter(Boolean);
  } catch {
    return [];
  }
}

export function writeFail2banJailLocal(
  dataDir: string,
  policy: Fail2banPolicy,
): { path: string; body: string } {
  const dir = join(dataDir, 'fail2ban');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'jail.local');
  const jails = policy.jails.length ? policy.jails : DEFAULT_F2B_POLICY.jails;
  const bantime = sanitizeDuration(policy.bantime, '1h');
  const findtime = sanitizeDuration(policy.findtime, '10m');
  const maxretry = Math.max(1, Math.min(50, Math.floor(policy.maxretry || 5)));
  const ignore = readIgnoreIpList(dataDir);
  const ignoreLine =
    ignore.length > 0 ? `ignoreip = 127.0.0.1/8 ::1 ${ignore.join(' ')}` : 'ignoreip = 127.0.0.1/8 ::1';
  const body = [
    '# Generated by YSK Server — fail2ban jail.local',
    '[DEFAULT]',
    `bantime = ${bantime}`,
    `findtime = ${findtime}`,
    `maxretry = ${maxretry}`,
    ignoreLine,
    'backend = systemd',
    '',
    ...jails.flatMap((j) => {
      const safe = j.replace(/[^a-zA-Z0-9._-]/g, '');
      return safe ? [`[${safe}]`, 'enabled = true', ''] : [];
    }),
  ].join('\n');
  writeFileSync(path, body, 'utf8');
  return { path, body };
}

function sanitizeDuration(v: string, fallback: string): string {
  const s = (v || '').trim();
  if (/^\d+[smhdw]?$/i.test(s)) return s;
  return fallback;
}

/**
 * Apply policy to management jail.local; optional system copy + reload.
 */
export async function applyFail2banPolicy(input: {
  dataDir: string;
  host: HostExecutor;
  policy: Fail2banPolicy;
  apply: boolean;
}): Promise<{
  ok: boolean;
  blocked?: boolean;
  written: string[];
  notes: string[];
  requiresExecute?: boolean;
  requiresRoot?: boolean;
  apply_status: 'written' | 'applied' | 'blocked' | 'failed';
}> {
  const { path } = writeFail2banJailLocal(input.dataDir, input.policy);
  const notes = [
    tl('notes.tpl.wrote', { path: path }),
    tl('notes.auto.t0299', { v0: (input.policy.jails.join(', ') || tl('notes.tpl.noParen')) }),
    `bantime=${input.policy.bantime} findtime=${input.policy.findtime} maxretry=${input.policy.maxretry}`,
    tl('notes.auto.t0300'),
  ];
  const written = [path];
  if (!input.apply) {
    return {
      ok: true,
      written,
      notes: [...notes, tl('notes.auto.n1235')],
      apply_status: 'written' };
  }
  const can = input.host.executeEnabled() && input.host.isRoot();
  if (!can) {
    return {
      ok: false,
      blocked: true,
      written,
      notes: [...notes, tl('notes.auto.n0954')],
      requiresExecute: !input.host.executeEnabled(),
      requiresRoot: !input.host.isRoot(),
      apply_status: 'blocked' };
  }
  // ensure package
  const install = await input.host.runCommand(
    ['bash', '-c', shellEnsureAptPackage('fail2ban-client', 'fail2ban')],
    { timeoutMs: 180_000 },
  );
  if (install.exitCode !== 0) {
    notes.push(tl('notes.auto.t0301', { v0: ((install.stderr || install.stdout || '').slice(0, 200)) }));
  }
  const cp = await input.host.runCommand(['cp', path, '/etc/fail2ban/jail.local'], {
    timeoutMs: 10_000 });
  notes.push(cp.exitCode === 0 ? tl('notes.auto.n0800') : tl('notes.auto.n1349'));
  const en = await input.host.runCommand(['systemctl', 'enable', '--now', 'fail2ban'], {
    timeoutMs: 30_000 });
  notes.push(en.exitCode === 0 ? 'fail2ban enable --now' : tl('notes.auto.n0278'));
  const rel = await input.host.runCommand(['systemctl', 'reload', 'fail2ban'], {
    timeoutMs: 15_000 });
  // reload may fail if never started — try restart
  if (rel.exitCode !== 0) {
    const rst = await input.host.runCommand(['systemctl', 'restart', 'fail2ban'], {
      timeoutMs: 30_000 });
    notes.push(rst.exitCode === 0 ? tl('notes.auto.n0727') : tl('notes.auto.n0405'));
    const ok = cp.exitCode === 0 && (en.exitCode === 0 || rst.exitCode === 0);
    return {
      ok,
      written,
      notes: [...notes, ok ? tl('notes.auto.n0001') : tl('notes.auto.n0012')],
      apply_status: ok ? 'applied' : 'failed' };
  }
  notes.push(tl('notes.auto.n0725'));
  const ok = cp.exitCode === 0;
  return {
    ok,
    written,
    notes: [...notes, ok ? tl('notes.auto.n0001') : tl('notes.auto.n0012')],
    apply_status: ok ? 'applied' : 'failed' };
}

export async function getFail2banDeepStatus(input: {
  host: HostExecutor;
  dataDir: string;
}): Promise<{
  installed: boolean;
  active: string;
  enabled: string;
  activeLabel: string;
  jails: Array<{ name: string; currentlyBanned?: number; totalBanned?: number }>;
  banned: Array<{ jail: string; ip: string }>;
  ignoreIps: string[];
  catalog: typeof FAIL2BAN_JAIL_CATALOG;
  executeEnabled: boolean;
  isRoot: boolean;
  notes: string[];
}> {
  const st = await probeFail2banStatus(input.host);
  const ignoreIps = readIgnoreIpList(input.dataDir);
  let banned: Array<{ jail: string; ip: string }> = [];
  const notes: string[] = [];
  try {
    // Prefer read even without execute — client often works for status
    if (st.installed) {
      const r = await fail2banBannedIps(input.host);
      banned = r.items ?? [];
      if (r.blocked) notes.push(...(r.notes ?? []));
    }
  } catch {
    notes.push(tl('notes.auto.n1436'));
  }
  const activeLabel =
    !st.installed
      ? tl('notes.notInstalled')
      : st.active === 'active'
        ? tl('notes.state.active')
        : st.active === 'inactive'
          ? tl('notes.auto.n0013')
          : st.active || tl('notes.unknown');

  return {
    installed: st.installed,
    active: st.active,
    enabled: st.enabled,
    activeLabel,
    jails: st.jails,
    banned,
    ignoreIps,
    catalog: FAIL2BAN_JAIL_CATALOG,
    executeEnabled: st.executeEnabled,
    isRoot: st.isRoot,
    notes };
}

export { fail2banBannedIps, fail2banUnban, probeFail2banStatus };
