/**
 * Write / sync nginx configs managed under dataDir to optional system path.
 */

import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ErrorCodes, YskError, tl} from '@ysk-server/shared';
import type { HostExecutor } from '../host/executor.js';
import { injectDefenseLimitsIntoConf } from './defense/nginx-limits.js';

export interface NginxSyncResult {
  sourceDir: string;
  targetDir: string | null;
  files: string[];
  copied: string[];
  tested: boolean;
  testOutput?: string;
  notes: string[];
  /** false when nginx -t failed after system copy was requested */
  ok: boolean;
  blocked?: boolean;
  requiresExecute?: boolean;
}

/**
 * Ensure managed nginx conf dir exists; optionally copy to system sites and nginx -t.
 */
export async function syncNginxConfigs(opts: {
  dataDir: string;
  /** e.g. /etc/nginx/conf.d — only used when executeEnabled + writable */
  systemConfDir?: string;
  host: HostExecutor;
  dryRun?: boolean;
}): Promise<NginxSyncResult> {
  const sourceDir = join(opts.dataDir, 'nginx', 'conf.d');
  mkdirSync(sourceDir, { recursive: true });
  // always write a managed main include snippet for documentation
  const managedMain = join(opts.dataDir, 'nginx', 'ysk-managed.conf');
  writeFileSync(
    managedMain,
    `# Generated by YSK Server — include from main nginx.conf:\n# include ${sourceDir}/*.conf;\n`,
    'utf8',
  );

  const files = existsSync(sourceDir)
    ? readdirSync(sourceDir).filter((f) => f.endsWith('.conf'))
    : [];
  const includes = existsSync(sourceDir)
    ? readdirSync(sourceDir).filter((f) => f.endsWith('.inc'))
    : [];
  const notes: string[] = [
    tl('notes.nginx.managedDir', { path: sourceDir }),
    tl('notes.nginx.includeHint', { path: sourceDir }),
  ];
  const copied: string[] = [];
  const targetDir = opts.systemConfDir ?? null;

  if (opts.dryRun) {
    return {
      sourceDir,
      targetDir,
      files,
      copied: [],
      tested: false,
      notes: [...notes, tl('notes.auto.n1014')],
      ok: true };
  }

  let blocked = false;
  if (targetDir && opts.host.executeEnabled()) {
    mkdirSync(targetDir, { recursive: true });
    for (const f of files) {
      const src = join(sourceDir, f);
      const dest = join(targetDir, `ysk-${f}`);
      copyFileSync(src, dest);
      copied.push(dest);
    }
    // Defense / shared includes (server-context snippets)
    for (const f of includes) {
      const src = join(sourceDir, f);
      // Keep stable name for ysk-defense-limits.inc so vhosts can include it
      const dest = join(targetDir, f.startsWith('ysk-') ? f : `ysk-${f}`);
      copyFileSync(src, dest);
      copied.push(dest);
    }
    // Drop orphan project vhosts left after delete/recreate (same server_name → 502)
    try {
      const managedSet = new Set(files.map((f) => `ysk-${f}`));
      for (const f of readdirSync(targetDir)) {
        // Only project linux_user confs: ysk-ysks_xxxxxxxx.conf
        if (!/^ysk-ysks_[a-z0-9]+\.conf$/i.test(f)) continue;
        if (managedSet.has(f)) continue;
        const orphan = join(targetDir, f);
        unlinkSync(orphan);
        notes.push(tl('notes.nginx.removedOrphan', { path: orphan }));
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      notes.push(tl('notes.nginx.orphanCleanupFailed', { detail: msg.slice(0, 120) }));
    }
    notes.push(tl('notes.auto.t0427', { v0: (copied.length) }));
  } else if (targetDir) {
    notes.push(tl('notes.auto.n1148'));
    blocked = true;
  }

  let tested = false;
  let testOutput: string | undefined;
  if (opts.host.executeEnabled() && opts.host.pathExists('/usr/sbin/nginx')) {
    const r = await opts.host.runCommand(['nginx', '-t'], { timeoutMs: 10_000 });
    tested = r.exitCode === 0;
    testOutput = `${r.stdout}\n${r.stderr}`.trim();
    notes.push(
      tested ? tl('notes.nginx.configOk') : tl('notes.tpl.nginxConfigFailed', { detail: testOutput || tl('notes.tpl.unknownError') }),
    );
  } else {
    notes.push(tl('notes.auto.n0791'));
  }

  // ok: managed write always succeeds; system path blocked or nginx -t fail → not ok
  const ok = blocked
    ? false
    : copied.length > 0
      ? tested || !opts.host.pathExists('/usr/sbin/nginx')
      : true;

  return {
    sourceDir,
    targetDir,
    files,
    copied,
    tested,
    testOutput,
    notes,
    ok,
    blocked: blocked || undefined,
    requiresExecute: blocked || undefined };
}

/**
 * Write a single server block into managed conf.d.
 * If Defense Center limits are active, inject YSK_DEFENSE include marker.
 */
export function writeManagedNginxConf(dataDir: string, filename: string, content: string): string {
  if (!filename.endsWith('.conf')) {
    throw new YskError(ErrorCodes.VALIDATION, tl('notes.auto.n1017'), { httpStatus: 400 });
  }
  const dir = join(dataDir, 'nginx', 'conf.d');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, filename);
  let body = content;
  const limitsInc = join(dir, 'ysk-defense-limits.inc');
  if (existsSync(limitsInc) && /server\s*\{/.test(body) && !body.includes('BEGIN YSK_DEFENSE')) {
    body = injectDefenseLimitsIntoConf(body);
  }
  writeFileSync(path, body, 'utf8');
  return path;
}

export function listManagedNginxConfs(dataDir: string): Array<{ name: string; path: string; bytes: number }> {
  const dir = join(dataDir, 'nginx', 'conf.d');
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.conf'))
    .map((name) => {
      const path = join(dir, name);
      return { name, path, bytes: Buffer.byteLength(readFileSync(path)) };
    });
}
