/**
 * Write / sync nginx configs managed under dataDir to optional system path.
 */

import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ErrorCodes, YskError } from '@ysk/shared';
import type { HostExecutor } from '../host/executor.js';

export interface NginxSyncResult {
  sourceDir: string;
  targetDir: string | null;
  files: string[];
  copied: string[];
  tested: boolean;
  testOutput?: string;
  notes: string[];
}

/**
 * Ensure managed nginx conf dir exists; optionally copy to system sites and nginx -t.
 */
export async function syncNginxConfigs(opts: {
  dataDir: string;
  /** e.g. /etc/nginx/conf.d — only used when executeEnabled + writable */
  systemConfDir?: string;
  host: HostExecutor;
  dryRun?: boolean;
}): Promise<NginxSyncResult> {
  const sourceDir = join(opts.dataDir, 'nginx', 'conf.d');
  mkdirSync(sourceDir, { recursive: true });
  // always write a managed main include snippet for documentation
  const managedMain = join(opts.dataDir, 'nginx', 'ysk-managed.conf');
  writeFileSync(
    managedMain,
    `# Generated by YSK Server — include from main nginx.conf:\n# include ${sourceDir}/*.conf;\n`,
    'utf8',
  );

  const files = existsSync(sourceDir)
    ? readdirSync(sourceDir).filter((f) => f.endsWith('.conf'))
    : [];
  const notes: string[] = [
    `Managed configs live in ${sourceDir}`,
    `Include them from nginx: include ${sourceDir}/*.conf;`,
  ];
  const copied: string[] = [];
  const targetDir = opts.systemConfDir ?? null;

  if (opts.dryRun) {
    return {
      sourceDir,
      targetDir,
      files,
      copied: [],
      tested: false,
      notes: [...notes, 'dry-run: no copy performed'],
    };
  }

  if (targetDir && opts.host.executeEnabled()) {
    mkdirSync(targetDir, { recursive: true });
    for (const f of files) {
      const src = join(sourceDir, f);
      const dest = join(targetDir, `ysk-${f}`);
      copyFileSync(src, dest);
      copied.push(dest);
    }
    notes.push(`Copied ${copied.length} file(s) to ${targetDir}`);
  } else if (targetDir) {
    notes.push('無法同步到系統 Nginx：需要系統變更權限');
  }

  let tested = false;
  let testOutput: string | undefined;
  if (opts.host.executeEnabled() && opts.host.pathExists('/usr/sbin/nginx')) {
    const r = await opts.host.runCommand(['nginx', '-t'], { timeoutMs: 10_000 });
    tested = r.exitCode === 0;
    testOutput = `${r.stdout}\n${r.stderr}`.trim();
    notes.push(tested ? 'nginx -t OK' : `nginx -t failed: ${testOutput}`);
  } else {
    notes.push('nginx -t skipped (binary missing or execute disabled)');
  }

  return { sourceDir, targetDir, files, copied, tested, testOutput, notes };
}

/**
 * Write a single server block into managed conf.d.
 */
export function writeManagedNginxConf(dataDir: string, filename: string, content: string): string {
  if (!filename.endsWith('.conf')) {
    throw new YskError(ErrorCodes.VALIDATION, 'filename must end with .conf', { httpStatus: 400 });
  }
  const dir = join(dataDir, 'nginx', 'conf.d');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, filename);
  writeFileSync(path, content, 'utf8');
  return path;
}

export function listManagedNginxConfs(dataDir: string): Array<{ name: string; path: string; bytes: number }> {
  const dir = join(dataDir, 'nginx', 'conf.d');
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.conf'))
    .map((name) => {
      const path = join(dir, name);
      return { name, path, bytes: Buffer.byteLength(readFileSync(path)) };
    });
}
