import { tl } from '@ysk/shared';
/**
 * Apply Node.js hosting artifacts under dataDir (real files).
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { selectNodeRuntime, renderNodeProcessUnit } from './runtime.js';
import type { HostExecutor } from '../host/executor.js';

export interface NodeApplyResult {
  envPath: string;
  unitPath: string;
  appDir: string;
  runtime: ReturnType<typeof selectNodeRuntime>;
  enabled: boolean;
  notes: string[];
}

/**
 * Write env file + systemd unit for a project under dataDir.
 */
export async function applyNodeHosting(input: {
  dataDir: string;
  projectId: string;
  projectName: string;
  linuxUser: string;
  homeDir: string;
  nodeVersion: string;
  entry?: string;
  port?: number;
  env?: Record<string, string>;
  host: HostExecutor;
  enableService?: boolean;
  /** Override binary (defaults to runtime plan path; use process.execPath for real spawn) */
  nodeBinary?: string;
  memoryMax?: string;
  cpuQuotaPercent?: number;
  limitNOFILE?: number;
}): Promise<NodeApplyResult> {
  const runtime = selectNodeRuntime(input.nodeVersion);
  const nodeBinary = input.nodeBinary ?? runtime.binaryPath;
  const appDir = join(input.homeDir, 'app');
  mkdirSync(appDir, { recursive: true });
  mkdirSync(join(input.homeDir, 'logs'), { recursive: true });

  const envPath = join(input.homeDir, 'app', '.env');
  const envLines = Object.entries({
    NODE_ENV: 'production',
    PORT: String(input.port ?? 3000),
    HOST: '127.0.0.1',
    ...(input.env ?? {}),
  }).map(([k, v]) => `${k}=${v}`);
  writeFileSync(envPath, envLines.join('\n') + '\n', 'utf8');

  const unitsDir = join(input.dataDir, 'systemd');
  mkdirSync(unitsDir, { recursive: true });
  const unitName = `ysk-project-${input.linuxUser}.service`;
  const unitPath = join(unitsDir, unitName);
  const unit = renderNodeProcessUnit({
    projectName: input.projectName,
    linuxUser: input.linuxUser,
    appDir,
    nodeBinary,
    entry: input.entry ?? 'server.js',
    port: input.port ?? 3000,
    memoryMax: input.memoryMax,
    cpuQuotaPercent: input.cpuQuotaPercent,
    limitNOFILE: input.limitNOFILE,
    env: input.env,
  });
  writeFileSync(unitPath, unit, 'utf8');

  // default entry stub if missing — bind 127.0.0.1 so deploy health is local-only
  const entryPath = join(appDir, input.entry ?? 'server.js');
  if (!existsSync(entryPath)) {
    writeFileSync(
      entryPath,
      `// Generated by YSK Server — real HTTP listen for health checks
const http = require('http');
const port = Number(process.env.PORT || 3000);
const host = process.env.HOST || '127.0.0.1';
const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.end('ok ' + port + ' ' + (req.url || '/'));
});
server.listen(port, host, () => {
  process.stdout.write('ysk-app listening on ' + host + ':' + port + '\\n');
});
`,
      'utf8',
    );
  }

  const notes = [
    `Unit written to ${unitPath}`,
    `Env written to ${envPath}`,
    `Node major ${runtime.version} binary: ${nodeBinary}`,
  ];
  let enabled = false;
  if (input.enableService && input.host.executeEnabled() && input.host.isRoot()) {
    const r1 = await input.host.runCommand(['cp', unitPath, `/etc/systemd/system/${unitName}`]);
    const r2 = await input.host.runCommand(['systemctl', 'daemon-reload']);
    const r3 = await input.host.runCommand(['systemctl', 'enable', '--now', unitName]);
    enabled = r1.exitCode === 0 && r2.exitCode === 0 && r3.exitCode === 0;
    notes.push(enabled ? tl('notes.auto.n0749') : tl('notes.auto.n1153'));
  } else {
    notes.push(tl('notes.auto.n1154'));
  }

  return { envPath, unitPath, appDir, runtime, enabled, notes };
}
