/**
 * Apply Node.js hosting artifacts under dataDir (real files).
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { selectNodeRuntime, renderNodeProcessUnit } from './runtime.js';
import type { HostExecutor } from '../host/executor.js';

export interface NodeApplyResult {
  envPath: string;
  unitPath: string;
  appDir: string;
  runtime: ReturnType<typeof selectNodeRuntime>;
  enabled: boolean;
  notes: string[];
}

/**
 * Write env file + systemd unit for a project under dataDir.
 */
export async function applyNodeHosting(input: {
  dataDir: string;
  projectId: string;
  projectName: string;
  linuxUser: string;
  homeDir: string;
  nodeVersion: string;
  entry?: string;
  port?: number;
  env?: Record<string, string>;
  host: HostExecutor;
  enableService?: boolean;
}): Promise<NodeApplyResult> {
  const runtime = selectNodeRuntime(input.nodeVersion);
  const appDir = join(input.homeDir, 'app');
  mkdirSync(appDir, { recursive: true });
  mkdirSync(join(input.homeDir, 'logs'), { recursive: true });

  const envPath = join(input.homeDir, 'app', '.env');
  const envLines = Object.entries({
    NODE_ENV: 'production',
    PORT: String(input.port ?? 3000),
    ...(input.env ?? {}),
  }).map(([k, v]) => `${k}=${v}`);
  writeFileSync(envPath, envLines.join('\n') + '\n', 'utf8');

  const unitsDir = join(input.dataDir, 'systemd');
  mkdirSync(unitsDir, { recursive: true });
  const unitName = `ysk-project-${input.linuxUser}.service`;
  const unitPath = join(unitsDir, unitName);
  const unit = renderNodeProcessUnit({
    projectName: input.projectName,
    linuxUser: input.linuxUser,
    appDir,
    nodeBinary: runtime.binaryPath,
    entry: input.entry ?? 'server.js',
    port: input.port ?? 3000,
  });
  writeFileSync(unitPath, unit, 'utf8');

  // default entry stub if missing
  const entryPath = join(appDir, input.entry ?? 'server.js');
  if (!existsSync(entryPath)) {
    writeFileSync(
      entryPath,
      `// Generated by YSK Server\nconst http=require('http');\nconst port=process.env.PORT||3000;\nhttp.createServer((q,s)=>s.end('ok '+port)).listen(port);\n`,
      'utf8',
    );
  }

  const notes = [
    `Unit written to ${unitPath}`,
    `Env written to ${envPath}`,
    `Node major ${runtime.version} binary hint: ${runtime.binaryPath}`,
  ];
  let enabled = false;
  if (input.enableService && input.host.executeEnabled() && input.host.isRoot()) {
    const r1 = await input.host.runCommand(['cp', unitPath, `/etc/systemd/system/${unitName}`]);
    const r2 = await input.host.runCommand(['systemctl', 'daemon-reload']);
    const r3 = await input.host.runCommand(['systemctl', 'enable', '--now', unitName]);
    enabled = r1.exitCode === 0 && r2.exitCode === 0 && r3.exitCode === 0;
    notes.push(enabled ? 'systemd enabled' : 'systemd enable failed — check privileges');
  } else {
    notes.push('systemd enable skipped (need root + YSK_EXECUTE=1)');
  }

  return { envPath, unitPath, appDir, runtime, enabled, notes };
}
