/**
 * PHP ini settings: load/save managed files, render drop-in + FPM php_admin_value.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { HostExecutor } from '../host/executor.js';
import {
  allPhpIniKeys,
  defaultPhpIniValues,
  listPhpIniCatalog,
} from './php-ini-catalog.js';
import { selectPhpRuntime } from './runtime.js';

export interface PhpIniSettings {
  version: string;
  values: Record<string, string | number | boolean>;
  extra: Record<string, string>;
  rawAppend?: string;
  updatedAt?: string;
}

export interface PhpIniGetResult {
  version: string;
  catalog: ReturnType<typeof listPhpIniCatalog>;
  settings: PhpIniSettings;
  managedIniPath: string;
  notes: string[];
}

function settingsPath(dataDir: string, version: string): string {
  return join(dataDir, 'php', version, 'panel-ini.json');
}

function managedIniPath(dataDir: string, version: string): string {
  return join(dataDir, 'php', version, 'conf.d', 'ysk-panel.ini');
}

function projectSettingsPath(dataDir: string, projectId: string): string {
  return join(dataDir, 'php', 'projects', `${projectId}.json`);
}

export function loadPhpIniSettings(dataDir: string, version: string): PhpIniSettings {
  const v = selectPhpRuntime(version).version;
  const p = settingsPath(dataDir, v);
  if (!existsSync(p)) {
    return {
      version: v,
      values: defaultPhpIniValues(),
      extra: {},
      rawAppend: '',
    };
  }
  try {
    const raw = JSON.parse(readFileSync(p, 'utf8')) as PhpIniSettings;
    return {
      version: v,
      values: { ...defaultPhpIniValues(), ...(raw.values ?? {}) },
      extra: raw.extra ?? {},
      rawAppend: raw.rawAppend ?? '',
      updatedAt: raw.updatedAt,
    };
  } catch {
    return {
      version: v,
      values: defaultPhpIniValues(),
      extra: {},
      rawAppend: '',
    };
  }
}

export function loadProjectPhpIni(
  dataDir: string,
  projectId: string,
  version: string,
): PhpIniSettings {
  const v = selectPhpRuntime(version).version;
  const p = projectSettingsPath(dataDir, projectId);
  if (!existsSync(p)) {
    return {
      version: v,
      values: {},
      extra: {},
      rawAppend: '',
    };
  }
  try {
    const raw = JSON.parse(readFileSync(p, 'utf8')) as PhpIniSettings;
    return {
      version: v,
      values: raw.values ?? {},
      extra: raw.extra ?? {},
      rawAppend: raw.rawAppend ?? '',
      updatedAt: raw.updatedAt,
    };
  } catch {
    return { version: v, values: {}, extra: {}, rawAppend: '' };
  }
}

export function formatIniValue(v: string | number | boolean): string {
  if (typeof v === 'boolean') return v ? '1' : '0';
  return String(v);
}

/** Merge catalog values + extra + raw into ini file body */
export function renderPhpIniFile(settings: PhpIniSettings, title = 'YSK panel'): string {
  const lines: string[] = [
    `; Generated by YSK Server — ${title}`,
    `; Do not edit by hand; use admin panel`,
    '',
  ];
  const known = new Set(allPhpIniKeys());
  for (const [k, v] of Object.entries(settings.values)) {
    if (v === '' || v === undefined || v === null) continue;
    if (k === 'error_log' && String(v).trim() === '') continue;
    if (k === 'open_basedir' && String(v).trim() === '') continue;
    lines.push(`${k} = ${formatIniValue(v)}`);
  }
  const extraKeys = Object.keys(settings.extra ?? {}).filter(
    (k) => k && !known.has(k) && String(settings.extra[k] ?? '').length >= 0,
  );
  if (extraKeys.length) {
    lines.push('', '; --- advanced extra ---');
    for (const k of extraKeys.sort()) {
      const val = settings.extra[k];
      if (val === undefined) continue;
      lines.push(`${k} = ${val}`);
    }
  }
  if (settings.rawAppend?.trim()) {
    lines.push('', '; --- raw append ---', settings.rawAppend.trim(), '');
  }
  lines.push('');
  return lines.join('\n');
}

/** Keys known as PHP boolean flags (php_admin_flag). Others use php_admin_value. */
function phpIniFlagKeys(): Set<string> {
  const s = new Set<string>();
  for (const g of listPhpIniCatalog()) {
    for (const f of g.fields) {
      if (f.type === 'bool') s.add(f.key);
    }
  }
  return s;
}

/** FPM pool php_admin_value / php_admin_flag lines */
export function renderPhpAdminValueLines(settings: PhpIniSettings): string[] {
  const lines: string[] = [];
  const flags = phpIniFlagKeys();
  const emit = (k: string, v: string | number | boolean) => {
    if (v === '' || v === undefined || v === null) return;
    if (k === 'error_log' && String(v).trim() === '') return;
    if (k === 'open_basedir' && String(v).trim() === '') return;
    // Only catalog bools (or explicit boolean) use php_admin_flag — never int 0/1
    if (flags.has(k) || typeof v === 'boolean') {
      const on = v === true || v === 1 || v === '1';
      lines.push(`php_admin_flag[${k}] = ${on ? 'on' : 'off'}`);
    } else {
      const s = String(v).replace(/"/g, '\\"');
      lines.push(`php_admin_value[${k}] = ${s}`);
    }
  };
  for (const [k, v] of Object.entries(settings.values)) emit(k, v);
  for (const [k, v] of Object.entries(settings.extra ?? {})) {
    if (v !== undefined) emit(k, v);
  }
  return lines;
}

/**
 * Effective project settings = global defaults overridden by project non-empty values.
 */
export function mergePhpIni(
  global: PhpIniSettings,
  project: PhpIniSettings,
): PhpIniSettings {
  const values = { ...global.values };
  for (const [k, v] of Object.entries(project.values)) {
    if (v === '' || v === undefined) continue;
    values[k] = v;
  }
  const extra = { ...global.extra, ...project.extra };
  const rawParts = [global.rawAppend, project.rawAppend].filter((s) => s?.trim());
  return {
    version: project.version || global.version,
    values,
    extra,
    rawAppend: rawParts.join('\n'),
    updatedAt: project.updatedAt || global.updatedAt,
  };
}

export function savePhpIniSettings(
  dataDir: string,
  settings: PhpIniSettings,
): { settings: PhpIniSettings; managedIniPath: string; written: string[] } {
  const v = selectPhpRuntime(settings.version).version;
  const dir = join(dataDir, 'php', v);
  mkdirSync(join(dir, 'conf.d'), { recursive: true });
  const next: PhpIniSettings = {
    ...settings,
    version: v,
    values: { ...defaultPhpIniValues(), ...settings.values },
    extra: settings.extra ?? {},
    rawAppend: settings.rawAppend ?? '',
    updatedAt: new Date().toISOString(),
  };
  const jsonPath = settingsPath(dataDir, v);
  writeFileSync(jsonPath, JSON.stringify(next, null, 2), 'utf8');
  const iniPath = managedIniPath(dataDir, v);
  writeFileSync(iniPath, renderPhpIniFile(next, `global PHP ${v}`), 'utf8');
  return {
    settings: next,
    managedIniPath: iniPath,
    written: [jsonPath, iniPath],
  };
}

export function saveProjectPhpIni(
  dataDir: string,
  projectId: string,
  settings: PhpIniSettings,
): { settings: PhpIniSettings; written: string[] } {
  const v = selectPhpRuntime(settings.version || '8.2').version;
  const dir = join(dataDir, 'php', 'projects');
  mkdirSync(dir, { recursive: true });
  const next: PhpIniSettings = {
    version: v,
    values: settings.values ?? {},
    extra: settings.extra ?? {},
    rawAppend: settings.rawAppend ?? '',
    updatedAt: new Date().toISOString(),
  };
  const p = projectSettingsPath(dataDir, projectId);
  writeFileSync(p, JSON.stringify(next, null, 2), 'utf8');
  return { settings: next, written: [p] };
}

export function getPhpIni(dataDir: string, version: string): PhpIniGetResult {
  const v = selectPhpRuntime(version).version;
  const settings = loadPhpIniSettings(dataDir, v);
  return {
    version: v,
    catalog: listPhpIniCatalog(),
    settings,
    managedIniPath: managedIniPath(dataDir, v),
    notes: [
      '變更會寫入管理檔；「套用到系統」才會進 /etc/php/.../conf.d 並 reload FPM',
    ],
  };
}

/**
 * Copy managed ysk-panel.ini into system conf.d and reload php-fpm.
 */
export async function applyPhpIniSystem(input: {
  dataDir: string;
  version: string;
  host: HostExecutor;
}): Promise<{
  ok: boolean;
  written: string[];
  notes: string[];
  applied: boolean;
  blocked: boolean;
  requiresRoot: boolean;
  requiresExecute: boolean;
}> {
  const v = selectPhpRuntime(input.version).version;
  const managed = managedIniPath(input.dataDir, v);
  const notes: string[] = [];
  const written: string[] = [];
  if (!existsSync(managed)) {
    // ensure file from defaults
    savePhpIniSettings(input.dataDir, loadPhpIniSettings(input.dataDir, v));
  }
  notes.push(`管理 ini：${managed}`);
  written.push(managed);

  if (!input.host.executeEnabled() || !input.host.isRoot()) {
    return {
      ok: false,
      written,
      notes: [...notes, '無法套用到系統：需要 YSK_EXECUTE + root'],
      applied: false,
      blocked: true,
      requiresRoot: !input.host.isRoot(),
      requiresExecute: !input.host.executeEnabled(),
    };
  }

  const destDir = `/etc/php/${v}/fpm/conf.d`;
  const dest = `${destDir}/99-ysk-panel.ini`;
  if (!existsSync(`/etc/php/${v}/fpm`)) {
    return {
      ok: false,
      written,
      notes: [...notes, `/etc/php/${v}/fpm 不存在 — 請先安裝 php${v}-fpm`],
      applied: false,
      blocked: false,
      requiresRoot: false,
      requiresExecute: false,
    };
  }
  await input.host.runCommand(['mkdir', '-p', destDir], { timeoutMs: 5_000 });
  const cp = await input.host.runCommand(['cp', managed, dest], { timeoutMs: 10_000 });
  if (cp.exitCode !== 0) {
    notes.push(`複製失敗：${cp.stderr || cp.stdout}`);
    return {
      ok: false,
      written,
      notes,
      applied: false,
      blocked: false,
      requiresRoot: false,
      requiresExecute: false,
    };
  }
  written.push(dest);
  // Also CLI conf.d if present
  const cliDir = `/etc/php/${v}/cli/conf.d`;
  if (existsSync(`/etc/php/${v}/cli`)) {
    await input.host.runCommand(['mkdir', '-p', cliDir], { timeoutMs: 5_000 });
    await input.host.runCommand(['cp', managed, `${cliDir}/99-ysk-panel.ini`], {
      timeoutMs: 10_000,
    });
  }
  const rel = await input.host.runCommand(['systemctl', 'reload', `php${v}-fpm`], {
    timeoutMs: 30_000,
  });
  const applied = rel.exitCode === 0;
  notes.push(
    applied
      ? `已套用 ${dest} 並 reload php${v}-fpm`
      : `已複製 ini；reload 失敗：${rel.stderr || rel.stdout}`,
  );
  return {
    ok: applied,
    written,
    notes,
    applied,
    blocked: false,
    requiresRoot: false,
    requiresExecute: false,
  };
}
