/**
 * PM2 process manager artifacts + optional start/stop (Spec § PM2 / fleet).
 * Never fakes success: without YSK_EXECUTE, only writes ecosystem config.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { HostExecutor } from '../host/executor.js';

export interface Pm2EcosystemResult {
  ecosystemPath: string;
  appName: string;
  notes: string[];
}

export interface Pm2StartResult {
  ok: boolean;
  appName: string;
  ecosystemPath: string;
  pid?: number;
  notes: string[];
  commandResults: Array<{ argv: string[]; exitCode: number; stderr: string }>;
  requiresExecute: boolean;
  pm2Available: boolean;
}

export function pm2AppName(linuxUser: string): string {
  return `ysk-${linuxUser}`;
}

/**
 * Write ecosystem.config.cjs under project home (always safe).
 */
export function writePm2Ecosystem(input: {
  homeDir: string;
  linuxUser: string;
  appDir: string;
  entry: string;
  port: number;
  nodeBinary: string;
  instances?: number | 'max';
  /** Extra env from panel runtime tuning */
  env?: Record<string, string>;
}): Pm2EcosystemResult {
  const appName = pm2AppName(input.linuxUser);
  const notes: string[] = [];
  mkdirSync(join(input.homeDir, 'logs'), { recursive: true });
  const ecosystemPath = join(input.homeDir, 'ecosystem.config.cjs');
  const instances = input.instances ?? 1;
  const envObj: Record<string, string> = {
    NODE_ENV: 'production',
    PORT: String(input.port),
    HOST: '127.0.0.1',
    ...(input.env ?? {}),
  };
  const content = `/** Generated by YSK Server — PM2 ecosystem (do not claim running until pm2 start) */
module.exports = {
  apps: [
    {
      name: ${JSON.stringify(appName)},
      script: ${JSON.stringify(input.entry)},
      cwd: ${JSON.stringify(input.appDir)},
      interpreter: ${JSON.stringify(input.nodeBinary)},
      instances: ${JSON.stringify(instances)},
      exec_mode: 'fork',
      autorestart: true,
      max_memory_restart: '512M',
      env: ${JSON.stringify(envObj, null, 8).replace(/\n/g, '\n      ')},
      out_file: ${JSON.stringify(join(input.homeDir, 'logs', 'pm2-out.log'))},
      error_file: ${JSON.stringify(join(input.homeDir, 'logs', 'pm2-err.log'))},
      merge_logs: true,
    },
  ],
};
`;
  writeFileSync(ecosystemPath, content, 'utf8');
  notes.push(`PM2 ecosystem written: ${ecosystemPath}`);
  notes.push(`App name: ${appName}`);
  return { ecosystemPath, appName, notes };
}

/**
 * Detect pm2 on PATH.
 */
export async function probePm2(host: HostExecutor): Promise<{ available: boolean; path?: string }> {
  const r = await host.runCommand(['bash', '-c', 'command -v pm2 || true'], { timeoutMs: 5_000 });
  const path = r.stdout.trim() || undefined;
  return { available: Boolean(path), path };
}

/**
 * Start (or restart) app via pm2. Requires executeEnabled — never fakes ok.
 */
export async function applyPm2Start(input: {
  host: HostExecutor;
  homeDir: string;
  linuxUser: string;
  appDir: string;
  entry: string;
  port: number;
  nodeBinary: string;
  /** When false, only write ecosystem */
  execute?: boolean;
  env?: Record<string, string>;
}): Promise<Pm2StartResult> {
  const eco = writePm2Ecosystem({
    homeDir: input.homeDir,
    linuxUser: input.linuxUser,
    appDir: input.appDir,
    entry: input.entry,
    port: input.port,
    nodeBinary: input.nodeBinary,
    env: input.env,
  });
  const notes = [...eco.notes];
  const commandResults: Pm2StartResult['commandResults'] = [];
  const want = Boolean(input.execute);
  const can = want && input.host.executeEnabled();
  const probe = await probePm2(input.host);

  if (!probe.available) {
    notes.push('pm2 找不到 on PATH — install: npm i -g pm2');
    return {
      ok: false,
      appName: eco.appName,
      ecosystemPath: eco.ecosystemPath,
      notes,
      commandResults,
      requiresExecute: !input.host.executeEnabled(),
      pm2Available: false,
    };
  }
  notes.push(`pm2 binary: ${probe.path}`);

  if (want && !can) {
    notes.push('無法啟動 PM2：伺服器未開啟系統變更權限');
    return {
      ok: false,
      appName: eco.appName,
      ecosystemPath: eco.ecosystemPath,
      notes,
      commandResults,
      requiresExecute: true,
      pm2Available: true,
    };
  }

  if (!can) {
    notes.push('僅寫入 PM2 設定，未啟動程序');
    return {
      ok: false,
      appName: eco.appName,
      ecosystemPath: eco.ecosystemPath,
      notes,
      commandResults,
      requiresExecute: true,
      pm2Available: true,
    };
  }

  // delete existing name if any (ignore failure)
  const del = await input.host.runCommand(['pm2', 'delete', eco.appName], { timeoutMs: 30_000 });
  commandResults.push({
    argv: ['pm2', 'delete', eco.appName],
    exitCode: del.exitCode,
    stderr: del.stderr,
  });

  const start = await input.host.runCommand(
    ['pm2', 'start', eco.ecosystemPath, '--only', eco.appName],
    { timeoutMs: 60_000 },
  );
  commandResults.push({
    argv: ['pm2', 'start', eco.ecosystemPath, '--only', eco.appName],
    exitCode: start.exitCode,
    stderr: start.stderr,
  });

  if (start.exitCode !== 0) {
    notes.push(`pm2 start 失敗：${start.stderr || start.stdout}`);
    return {
      ok: false,
      appName: eco.appName,
      ecosystemPath: eco.ecosystemPath,
      notes,
      commandResults,
      requiresExecute: false,
      pm2Available: true,
    };
  }

  notes.push(`pm2 已啟動 ${eco.appName}`);
  // best-effort pid from pm2 jlist
  let pid: number | undefined;
  const jlist = await input.host.runCommand(['pm2', 'jlist'], { timeoutMs: 15_000 });
  commandResults.push({
    argv: ['pm2', 'jlist'],
    exitCode: jlist.exitCode,
    stderr: jlist.stderr,
  });
  if (jlist.exitCode === 0 && jlist.stdout.trim()) {
    try {
      const apps = JSON.parse(jlist.stdout) as Array<{ name?: string; pid?: number }>;
      const hit = apps.find((a) => a.name === eco.appName);
      if (hit?.pid && hit.pid > 0) pid = hit.pid;
    } catch {
      notes.push('pm2 jlist parse failed — pid unknown');
    }
  }

  // Persist process list for reboot survival (best-effort)
  const save = await input.host.runCommand(['pm2', 'save'], { timeoutMs: 30_000 });
  commandResults.push({
    argv: ['pm2', 'save'],
    exitCode: save.exitCode,
    stderr: save.stderr,
  });
  if (save.exitCode === 0) notes.push('pm2 save ok');
  else notes.push(`pm2 save exit=${save.exitCode} (non-fatal)`);

  return {
    ok: true,
    appName: eco.appName,
    ecosystemPath: eco.ecosystemPath,
    pid,
    notes,
    commandResults,
    requiresExecute: false,
    pm2Available: true,
  };
}

/**
 * Stop/delete PM2 app when present.
 */
export async function applyPm2Stop(input: {
  host: HostExecutor;
  linuxUser: string;
}): Promise<{ ok: boolean; notes: string[]; requiresExecute: boolean }> {
  const appName = pm2AppName(input.linuxUser);
  const notes: string[] = [];
  if (!input.host.executeEnabled()) {
    notes.push('無法停止 PM2：伺服器未開啟系統變更權限');
    return { ok: false, notes, requiresExecute: true };
  }
  const probe = await probePm2(input.host);
  if (!probe.available) {
    notes.push('找不到 pm2 — 無法以 PM2 停止');
    return { ok: true, notes, requiresExecute: false };
  }
  const r = await input.host.runCommand(['pm2', 'delete', appName], { timeoutMs: 30_000 });
  notes.push(`pm2 delete ${appName} exit=${r.exitCode}`);
  // exit 1 when 找不到 is fine
  return { ok: true, notes, requiresExecute: false };
}
