import { tl } from 'ysk-server-shared';
/**
 * Generate sshd_config Match snippet so project Linux users can SFTP
 * with authorized_keys under their home (isolation).
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import type { JsonStore } from '../db/store.js';
import type { HostExecutor } from '../host/executor.js';

export const SSHD_SNIPPET_NAME = '99-ysk-sftp.conf';

export interface SshdSnippetResult {
  ok: boolean;
  written: string[];
  notes: string[];
  snippet: string;
  systemPath?: string;
  applied?: boolean;
  blocked?: boolean;
  requiresRoot?: boolean;
  requiresExecute?: boolean;
}

/**
 * Build Match block for YSK project users (ysks_* / ysk_*).
 * Force internal-sftp, chroot optional (default: no chroot — home is already isolated).
 */
export function buildSshdSftpSnippet(opts?: {
  /** If true, ChrootDirectory %h and ForceCommand internal-sftp */
  chroot?: boolean;
  /** Extra Match Group */
  matchGroup?: string;
}): string {
  const chroot = Boolean(opts?.chroot);
  const lines = [
    '# Generated by YSK Server — include from sshd_config:',
    `#   Include /etc/ssh/sshd_config.d/${SSHD_SNIPPET_NAME}`,
    '# Project Linux users: ysks_* (new) / ysk_* (legacy)',
    '# AuthorizedKeysFile relative to user home',
    '',
    'Match User ysks_*,ysk_*',
    '    AllowTcpForwarding no',
    '    X11Forwarding no',
    '    PermitTunnel no',
    '    AllowAgentForwarding no',
    '    PasswordAuthentication no',
    '    PubkeyAuthentication yes',
    '    AuthorizedKeysFile .ssh/authorized_keys',
  ];
  if (chroot) {
    lines.push(
      '    ChrootDirectory %h',
      '    ForceCommand internal-sftp',
    );
  } else {
    lines.push('    ForceCommand internal-sftp');
  }
  if (opts?.matchGroup) {
    lines.push(`    # also consider: Match Group ${opts.matchGroup}`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Write managed snippet under dataDir; optionally install to /etc/ssh/sshd_config.d/
 */
export async function applySshdSftpSnippet(input: {
  dataDir: string;
  host: HostExecutor;
  db?: JsonStore;
  chroot?: boolean;
  installSystem?: boolean;
}): Promise<SshdSnippetResult> {
  const notes: string[] = [];
  const written: string[] = [];
  const snippet = buildSshdSftpSnippet({ chroot: input.chroot });
  const managedDir = join(input.dataDir, 'ssh');
  mkdirSync(managedDir, { recursive: true });
  const managedPath = join(managedDir, SSHD_SNIPPET_NAME);
  writeFileSync(managedPath, snippet, 'utf8');
  written.push(managedPath);
  notes.push(tl('notes.auto.t0123', { v0: (managedPath) }));

  // Count project users for notes
  if (input.db) {
    const n = (input.db.snapshot.projects ?? []).filter((p) => p.linux_user).length;
    notes.push(tl('notes.auto.t0124', { v0: (n) }));
  }

  const want = input.installSystem !== false;
  if (!want) {
    return {
      ok: true,
      written,
      notes: [...notes, tl('notes.auto.n0983')],
      snippet,
      applied: false,
    };
  }

  if (!input.host.executeEnabled() || !input.host.isRoot()) {
    notes.push(tl('notes.auto.n1164'));
    notes.push(tl('notes.auto.t0125', { v0: (managedPath) }));
    return {
      ok: false,
      written,
      notes,
      snippet,
      blocked: true,
      requiresRoot: !input.host.isRoot(),
      requiresExecute: !input.host.executeEnabled(),
      applied: false,
    };
  }

  const systemDir = '/etc/ssh/sshd_config.d';
  const systemPath = join(systemDir, SSHD_SNIPPET_NAME);
  if (!existsSync(systemDir)) {
    await input.host.runCommand(['mkdir', '-p', systemDir], { timeoutMs: 5_000 });
  }
  const cp = await input.host.runCommand(['cp', managedPath, systemPath], { timeoutMs: 10_000 });
  if (cp.exitCode !== 0) {
    notes.push(tl('notes.tpl.copyFailed', { detail: cp.stderr || cp.stdout }));
    return {
      ok: false,
      written,
      notes,
      snippet,
      systemPath,
      applied: false,
      requiresRoot: false,
      requiresExecute: false,
    };
  }
  written.push(systemPath);
  // Validate and reload (ssh or sshd unit name varies)
  const test = await input.host.runCommand(['sshd', '-t'], { timeoutMs: 10_000 });
  if (test.exitCode !== 0) {
    notes.push(tl('notes.auto.t0126', { v0: (test.stderr || test.stdout) }));
    notes.push(tl('notes.auto.n1204'));
    return {
      ok: false,
      written,
      notes,
      snippet,
      systemPath,
      applied: false,
    };
  }
  let reload = await input.host.runCommand(['systemctl', 'reload', 'ssh'], { timeoutMs: 15_000 });
  if (reload.exitCode !== 0) {
    reload = await input.host.runCommand(['systemctl', 'reload', 'sshd'], { timeoutMs: 15_000 });
  }
  const applied = reload.exitCode === 0;
  notes.push(
    applied
      ? tl('notes.auto.t0127', { v0: (systemPath) })
      : tl('notes.auto.t0128', { v0: (reload.stderr || reload.stdout) }),
  );
  return {
    ok: applied,
    written,
    notes,
    snippet,
    systemPath,
    applied,
  };
}
