/**
 * System-level apply orchestrators: write configs under dataDir, optionally install/copy with YSK_EXECUTE.
 */

import { mkdirSync, writeFileSync, existsSync, copyFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { HostExecutor } from '../host/executor.js';
import { planEmailStackInstall } from '../email/dns-records.js';
import { planLetsEncrypt, renderNginxProxy } from './nginx-ssl.js';
import { renderPhpVhost, selectPhpRuntime } from './runtime.js';
import { planFirewall } from './extras.js';
import { ErrorCodes, YskError } from '@ysk/shared';

export type BlockReason =
  | 'no_execute'
  | 'no_root'
  | 'missing_binary'
  | 'network'
  | 'validation'
  | 'other';

export interface ApplyResult {
  ok: boolean;
  /** True when system commands were actually run */
  executed?: boolean;
  /** True when panel action could not run due to environment */
  blocked?: boolean;
  blockReason?: BlockReason;
  /** Human message for panel — never "run this in your shell" */
  blockMessage?: string;
  written: string[];
  /** Internal only — not for user homework */
  commands: string[];
  commandResults: Array<{ argv: string[]; exitCode: number; stderr: string }>;
  notes: string[];
  steps?: Array<{ name: string; status: 'ok' | 'skipped' | 'failed' | 'blocked'; detail?: string }>;
}

export function panelBlockMessage(reason: BlockReason): string {
  switch (reason) {
    case 'no_execute':
      return '伺服器未開啟系統變更權限，無法在管理面板完成此操作';
    case 'no_root':
      return '需要系統管理員（root）權限才能完成';
    case 'missing_binary':
      return '伺服器未安裝必要元件，無法在管理面板完成此操作';
    case 'network':
      return '網路條件不足（例如網域驗證所需埠無法使用）';
    case 'validation':
      return '輸入資料無效';
    default:
      return '操作無法完成';
  }
}

async function runAll(
  host: HostExecutor,
  commands: string[][],
  execute: boolean,
): Promise<ApplyResult['commandResults']> {
  const out: ApplyResult['commandResults'] = [];
  if (!execute) return out;
  for (const argv of commands) {
    const r = await host.runCommand(argv, { timeoutMs: 180_000 });
    out.push({ argv, exitCode: r.exitCode, stderr: r.stderr });
  }
  return out;
}

/**
 * Write Postfix/Dovecot/OpenDKIM managed configs + install helper;
 * optionally apt-install when root+EXECUTE. Never fakes ok when install requested but skipped.
 */
export async function applyEmailStack(input: {
  dataDir: string;
  domain: string;
  mailHostname?: string;
  host: HostExecutor;
  installPackages?: boolean;
}): Promise<
  ApplyResult & {
    serviceStatus?: Record<string, string>;
    requiresExecute: boolean;
    requiresRoot: boolean;
  }
> {
  const domain = input.domain.trim().toLowerCase();
  if (!domain) throw new YskError(ErrorCodes.VALIDATION, '請填寫域名', { httpStatus: 400 });
  const mailHost = input.mailHostname ?? `mail.${domain}`;
  const dir = join(input.dataDir, 'email', domain);
  mkdirSync(join(dir, 'postfix'), { recursive: true });
  mkdirSync(join(dir, 'dovecot'), { recursive: true });
  mkdirSync(join(dir, 'opendkim'), { recursive: true });

  const certBase = `/etc/letsencrypt/live/${mailHost}`;
  const mainCf = [
    `# Generated by YSK Server for ${domain}`,
    `myhostname = ${mailHost}`,
    `myorigin = ${domain}`,
    'inet_interfaces = all',
    'inet_protocols = all',
    'smtpd_banner = $myhostname ESMTP YSK',
    'smtpd_tls_security_level = may',
    `smtpd_tls_cert_file = ${certBase}/fullchain.pem`,
    `smtpd_tls_key_file = ${certBase}/privkey.pem`,
    'smtp_tls_security_level = may',
    'smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination',
    'smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination',
    'mynetworks = 127.0.0.0/8 [::1]/128',
    'home_mailbox = Maildir/',
    'milter_default_action = accept',
    'milter_protocol = 6',
    'smtpd_milters = inet:localhost:8891',
    'non_smtpd_milters = inet:localhost:8891',
    '',
  ].join('\n');
  const masterCfSnippet = [
    '# YSK snippet — ensure submission/smtps (merge carefully into /etc/postfix/master.cf)',
    'submission inet n       -       y       -       -       smtpd',
    '  -o syslog_name=postfix/submission',
    '  -o smtpd_tls_security_level=encrypt',
    '  -o smtpd_sasl_auth_enable=yes',
    'smtps     inet n       -       y       -       -       smtpd',
    '  -o syslog_name=postfix/smtps',
    '  -o smtpd_tls_wrappermode=yes',
    '  -o smtpd_sasl_auth_enable=yes',
    '',
  ].join('\n');
  const dovecot = [
    '# Generated by YSK Server',
    'protocols = imap lmtp',
    'listen = *, ::',
    'mail_location = maildir:~/Maildir',
    'ssl = required',
    `ssl_cert = <${certBase}/fullchain.pem`,
    `ssl_key = <${certBase}/privkey.pem`,
    'auth_mechanisms = plain login',
    'disable_plaintext_auth = yes',
    '',
  ].join('\n');
  const opendkim = [
    'Syslog yes',
    'Mode sv',
    'Canonicalization relaxed/simple',
    `Domain ${domain}`,
    'Selector default',
    `KeyFile ${dir}/opendkim/default.private`,
    'Socket inet:8891@localhost',
    'PidFile /run/opendkim/opendkim.pid',
    '',
  ].join('\n');
  const keyTable = `default._domainkey.${domain} ${domain}:default:${dir}/opendkim/default.private\n`;
  const signingTable = `*@${domain} default._domainkey.${domain}\n`;

  const written = [
    join(dir, 'postfix', 'main.cf'),
    join(dir, 'postfix', 'master.cf.ysk-snippet'),
    join(dir, 'dovecot', 'dovecot.conf'),
    join(dir, 'opendkim', 'opendkim.conf'),
    join(dir, 'opendkim', 'KeyTable'),
    join(dir, 'opendkim', 'SigningTable'),
    join(dir, 'install-mta.sh'),
    join(dir, 'README.txt'),
  ];
  writeFileSync(written[0], mainCf, 'utf8');
  writeFileSync(written[1], masterCfSnippet, 'utf8');
  writeFileSync(written[2], dovecot, 'utf8');
  writeFileSync(written[3], opendkim, 'utf8');
  writeFileSync(written[4], keyTable, 'utf8');
  writeFileSync(written[5], signingTable, 'utf8');

  const plan = planEmailStackInstall(domain);
  const installScript = [
    '#!/usr/bin/env bash',
    `# YSK Server MTA install helper for ${domain}`,
    'set -euo pipefail',
    `DOMAIN=${JSON.stringify(domain)}`,
    `MAILHOST=${JSON.stringify(mailHost)}`,
    `DIR=${JSON.stringify(dir)}`,
    'export DEBIAN_FRONTEND=noninteractive',
    `apt-get update`,
    `apt-get install -y ${plan.packages.join(' ')}`,
    'cp "$DIR/postfix/main.cf" /etc/postfix/main.cf',
    'cp "$DIR/dovecot/dovecot.conf" /etc/dovecot/dovecot.conf',
    'cp "$DIR/opendkim/opendkim.conf" /etc/opendkim.conf || true',
    'systemctl enable --now postfix dovecot opendkim || true',
    'systemctl reload postfix || systemctl restart postfix',
    'echo "MTA configs applied for $DOMAIN — still need DNS/PTR/Port25"',
    '',
  ].join('\n');
  writeFileSync(written[6], installScript, 'utf8');
  writeFileSync(
    written[7],
    [
      `YSK Server managed mail configs for ${domain}`,
      `Mail host: ${mailHost}`,
      'Always review before copy to /etc.',
      '伺服器未開啟系統變更權限或缺少 root，無法在管理面板完成安裝',
      `Helper: ${written[6]}`,
      `Ports: ${plan.ports.join(', ')}`,
      'External: SPF/DKIM/DMARC/PTR + Port 25 or SMTP relay',
      '',
    ].join('\n'),
    'utf8',
  );

  const notes = [...plan.notes, `Configs under ${dir}`, `Install helper: ${written[6]}`];
  const commands: string[][] = [];
  if (input.installPackages) {
    commands.push(['apt-get', 'update']);
    commands.push([
      'bash',
      '-c',
      `DEBIAN_FRONTEND=noninteractive apt-get install -y ${plan.packages.join(' ')}`,
    ]);
    commands.push(['cp', written[0], '/etc/postfix/main.cf']);
    commands.push(['cp', written[2], '/etc/dovecot/dovecot.conf']);
    commands.push(['systemctl', 'enable', '--now', 'postfix']);
    commands.push(['systemctl', 'enable', '--now', 'dovecot']);
    commands.push(['systemctl', 'reload', 'postfix']);
  }

  const wantInstall = Boolean(input.installPackages);
  const execute = Boolean(wantInstall && input.host.executeEnabled() && input.host.isRoot());
  if (wantInstall && !execute) {
    notes.push('套件安裝未能執行：需要系統變更權限');
  }
  const commandResults = await runAll(input.host, commands, execute);
  const ranOk = commandResults.every((c) => c.exitCode === 0);
  const serviceStatus: Record<string, string> = {};
  for (const svc of ['postfix', 'dovecot', 'opendkim']) {
    try {
      const st = await input.host.runCommand(['systemctl', 'is-active', svc], { timeoutMs: 5_000 });
      serviceStatus[svc] = (st.stdout || st.stderr || `exit_${st.exitCode}`).trim();
    } catch {
      serviceStatus[svc] = 'unknown';
    }
  }
  notes.push(`services: ${JSON.stringify(serviceStatus)}`);
  return {
    ok: wantInstall ? execute && ranOk : true,
    written,
    commands: commands.map((a) => a.join(' ')),
    commandResults,
    notes,
    serviceStatus,
    requiresExecute: !input.host.executeEnabled(),
    requiresRoot: !input.host.isRoot(),
  };
}

/**
 * Issue / renew cert via panel: always attempts real execution when allowed.
 * Never instructs the operator to copy shell commands.
 */
export async function applyLetsEncrypt(input: {
  domain: string;
  email: string;
  host: HostExecutor;
  /** Default true — panel always tries to run */
  run?: boolean;
  /** Force dns-01 (auto when domain is wildcard) */
  challenge?: 'http-01' | 'dns-01';
}): Promise<ApplyResult> {
  const domain = input.domain.trim().toLowerCase();
  const isWildcard = domain.startsWith('*.');
  const challenge =
    input.challenge ?? (isWildcard ? 'dns-01' : 'http-01');
  const plan = planLetsEncrypt({
    domain,
    email: input.email,
    provider: 'letsencrypt',
    challenge,
  });
  const want = input.run !== false;
  const hasExecute = input.host.executeEnabled();
  const isRoot = input.host.isRoot();
  const execute = Boolean(want && hasExecute && isRoot);

  let blocked = false;
  let blockReason: BlockReason | undefined;
  let blockMessage: string | undefined;
  const notes: string[] = [];
  const steps: NonNullable<ApplyResult['steps']> = [];

  if (want && !hasExecute) {
    blocked = true;
    blockReason = 'no_execute';
    blockMessage = panelBlockMessage('no_execute');
    notes.push(blockMessage);
    steps.push({ name: '申請憑證', status: 'blocked', detail: blockMessage });
  } else if (want && !isRoot) {
    blocked = true;
    blockReason = 'no_root';
    blockMessage = panelBlockMessage('no_root');
    notes.push(blockMessage);
    steps.push({ name: '申請憑證', status: 'blocked', detail: blockMessage });
  }

  const commands = plan.commands.map((c) => ['bash', '-c', c]);
  const commandResults = await runAll(input.host, commands, execute);
  if (execute) {
    const ranOk = commandResults.length > 0 && commandResults.every((c) => c.exitCode === 0);
    if (ranOk) {
      notes.push('已在伺服器完成憑證申請流程');
      steps.push({ name: '申請憑證', status: 'ok' });
      steps.push({ name: '重載網頁服務', status: 'ok' });
    } else {
      const err = commandResults.map((c) => c.stderr).filter(Boolean).join('; ').slice(0, 400);
      notes.push(err || '憑證申請失敗');
      steps.push({ name: '申請憑證', status: 'failed', detail: err || undefined });
    }
    return {
      ok: ranOk,
      executed: true,
      blocked: false,
      written: [],
      commands: plan.commands,
      commandResults,
      notes,
      steps,
    };
  }

  return {
    ok: false,
    executed: false,
    blocked,
    blockReason,
    blockMessage,
    written: [],
    commands: plan.commands,
    commandResults,
    notes,
    steps,
  };
}

/**
 * Write PHP vhost under dataDir; optional copy to Apache sites-available.
 */
export async function applyPhpHosting(input: {
  dataDir: string;
  domain: string;
  docRoot: string;
  phpVersion: string;
  poolName: string;
  host: HostExecutor;
  enableSite?: boolean;
}): Promise<ApplyResult> {
  const rt = selectPhpRuntime(input.phpVersion);
  const dir = join(input.dataDir, 'apache', 'sites');
  mkdirSync(dir, { recursive: true });
  mkdirSync(input.docRoot, { recursive: true });
  const conf = renderPhpVhost({
    domain: input.domain,
    docRoot: input.docRoot,
    phpVersion: rt.version,
    poolName: input.poolName,
  });
  const path = join(dir, `${input.poolName}.conf`);
  writeFileSync(path, conf, 'utf8');
  const index = join(input.docRoot, 'index.php');
  if (!existsSync(index)) {
    writeFileSync(index, '<?php echo "YSK PHP OK\\n";\n', 'utf8');
  }
  const notes = [`PHP ${rt.version} vhost at ${path}`, `binary ${rt.binaryPath}`];
  const commands: string[][] = [];
  if (input.enableSite) {
    commands.push(['cp', path, `/etc/apache2/sites-available/${input.poolName}.conf`]);
    commands.push(['a2ensite', input.poolName]);
    commands.push(['systemctl', 'reload', 'apache2']);
  }
  const execute = Boolean(input.enableSite && input.host.executeEnabled() && input.host.isRoot());
  if (input.enableSite && !execute) notes.push('無法啟用 Apache 站點：需要系統變更權限');
  const commandResults = await runAll(input.host, commands, execute);
  const ranOk = commandResults.every((c) => c.exitCode === 0);
  let phpActive: string | undefined;
  if (execute) {
    const st = await input.host.runCommand(['systemctl', 'is-active', `php${rt.version}-fpm`], {
      timeoutMs: 5_000,
    });
    phpActive = (st.stdout || st.stderr || '').trim();
    notes.push(`php-fpm is-active: ${phpActive}`);
  }
  return {
    ok: execute ? ranOk : true,
    written: [path, index],
    commands: commands.map((c) => c.join(' ')),
    commandResults,
    notes: phpActive ? [...notes, `php_fpm=${phpActive}`] : notes,
  };
}

/**
 * Write FTPS (vsftpd) under dataDir; install/start when requested + privileged.
 * Prefer applyFtpsService when JsonStore is available (full panel flow).
 * Never fakes ok when install requested but skipped/failed.
 */
export async function applyFtps(input: {
  dataDir: string;
  domain: string;
  host: HostExecutor;
  install?: boolean;
  settings?: {
    pasvMin?: number;
    pasvMax?: number;
    listenPort?: number;
    sslEnable?: boolean;
    forceSsl?: boolean;
    pasvAddress?: string;
    writeEnable?: boolean;
    banner?: string;
  };
}): Promise<ApplyResult & { requiresExecute: boolean; requiresRoot: boolean }> {
  const { buildVsftpdConf, ftpsPaths, DEFAULT_FTPS_SETTINGS } = await import('./ftps-service.js');
  const paths = ftpsPaths(input.dataDir);
  mkdirSync(paths.root, { recursive: true });
  const settings = {
    ...DEFAULT_FTPS_SETTINGS,
    sslDomain: input.domain,
    ...(input.settings ?? {}),
  };
  const confBody = buildVsftpdConf({ dataDir: input.dataDir, settings });
  writeFileSync(paths.conf, confBody, 'utf8');
  const notes = [
    `已寫入設定 ${paths.conf}`,
    `PASV ${settings.pasvMin}-${settings.pasvMax}`,
  ];
  const steps: NonNullable<ApplyResult['steps']> = [
    { name: '寫入 vsftpd 設定', status: 'ok', detail: paths.conf },
  ];
  // install only when explicitly requested (never default true)
  const want = input.install === true;
  const execute = Boolean(want && input.host.executeEnabled() && input.host.isRoot());
  if (want && !execute) {
    const reason: BlockReason = !input.host.executeEnabled() ? 'no_execute' : 'no_root';
    const blockMessage = panelBlockMessage(reason);
    notes.push(blockMessage);
    steps.push({ name: '啟動 vsftpd', status: 'blocked', detail: blockMessage });
    return {
      ok: false,
      executed: false,
      blocked: true,
      blockReason: reason,
      blockMessage,
      written: [paths.conf],
      commands: [],
      commandResults: [],
      notes,
      steps,
      requiresExecute: !input.host.executeEnabled(),
      requiresRoot: !input.host.isRoot(),
    };
  }
  if (!want) {
    notes.push('已儲存設定（未要求套用系統）');
    return {
      ok: true,
      executed: false,
      written: [paths.conf],
      commands: [],
      commandResults: [],
      notes,
      steps,
      requiresExecute: !input.host.executeEnabled(),
      requiresRoot: !input.host.isRoot(),
    };
  }
  const commands: string[][] = [
    [
      'bash',
      '-c',
      'export DEBIAN_FRONTEND=noninteractive; command -v vsftpd >/dev/null || (apt-get update && apt-get install -y vsftpd db-util)',
    ],
    ['cp', paths.conf, '/etc/vsftpd.conf'],
    ['systemctl', 'enable', '--now', 'vsftpd'],
  ];
  const commandResults = await runAll(input.host, commands, true);
  const ranOk = commandResults.every((c) => c.exitCode === 0);
  if (ranOk) {
    notes.push('vsftpd 已啟動');
    steps.push({ name: '啟動 vsftpd', status: 'ok' });
  } else {
    notes.push('vsftpd 啟動失敗');
    steps.push({ name: '啟動 vsftpd', status: 'failed' });
  }
  return {
    ok: ranOk,
    executed: true,
    written: [paths.conf],
    commands: [],
    commandResults,
    notes,
    steps,
    requiresExecute: false,
    requiresRoot: false,
  };
}

/** Live ufw status for panel (honest probe, no mutation). */
export async function probeFirewallStatus(host: HostExecutor): Promise<{
  installed: boolean;
  active: string;
  statusText: string;
  numberedRules: string[];
  executeEnabled: boolean;
  isRoot: boolean;
}> {
  const installed =
    host.pathExists('/usr/sbin/ufw') ||
    host.pathExists('/usr/bin/ufw') ||
    (await host
      .runCommand(['bash', '-c', 'command -v ufw >/dev/null && echo yes || echo no'], {
        timeoutMs: 3_000,
      })
      .then((r) => (r.stdout || '').trim() === 'yes')
      .catch(() => false));

  let active = 'unknown';
  let statusText = '';
  const numberedRules: string[] = [];

  if (installed) {
    try {
      const st = await host.runCommand(['ufw', 'status'], { timeoutMs: 8_000 });
      statusText = `${st.stdout || ''}\n${st.stderr || ''}`.trim();
      const first = statusText.split('\n')[0] || '';
      if (/inactive/i.test(first)) active = 'inactive';
      else if (/active/i.test(first)) active = 'active';
      else active = first.slice(0, 40) || 'unknown';
    } catch {
      statusText = '';
      active = 'unknown';
    }
    try {
      const num = await host.runCommand(['ufw', 'status', 'numbered'], { timeoutMs: 8_000 });
      const body = `${num.stdout || ''}`.trim();
      for (const line of body.split('\n')) {
        const t = line.trim();
        if (/^\[\s*\d+\]/.test(t) || t.includes('ALLOW') || t.includes('DENY')) {
          numberedRules.push(t);
        }
      }
    } catch {
      /* ignore */
    }
  }

  return {
    installed,
    active,
    statusText: statusText.slice(0, 4000),
    numberedRules: numberedRules.slice(0, 80),
    executeEnabled: host.executeEnabled(),
    isRoot: host.isRoot(),
  };
}

/** Live fail2ban status for panel. */
export async function probeFail2banStatus(host: HostExecutor): Promise<{
  installed: boolean;
  active: string;
  enabled: string;
  jails: Array<{ name: string; currentlyBanned?: number; totalBanned?: number; raw?: string }>;
  executeEnabled: boolean;
  isRoot: boolean;
  defaultJails: string[];
}> {
  const defaultJails = planFirewall({}).fail2banJails;
  const installed =
    host.pathExists('/usr/bin/fail2ban-client') ||
    (await host
      .runCommand(['bash', '-c', 'command -v fail2ban-client >/dev/null && echo yes || echo no'], {
        timeoutMs: 3_000,
      })
      .then((r) => (r.stdout || '').trim() === 'yes')
      .catch(() => false));

  let active = 'unknown';
  let enabled = 'unknown';
  try {
    const a = await host.runCommand(['systemctl', 'is-active', 'fail2ban'], { timeoutMs: 4_000 });
    active = (a.stdout || a.stderr || 'unknown').trim().split(/\s+/)[0] || 'unknown';
  } catch {
    active = installed ? 'unknown' : 'not-found';
  }
  try {
    const e = await host.runCommand(['systemctl', 'is-enabled', 'fail2ban'], { timeoutMs: 4_000 });
    enabled = (e.stdout || e.stderr || 'unknown').trim().split(/\s+/)[0] || 'unknown';
  } catch {
    enabled = 'unknown';
  }

  const jails: Array<{
    name: string;
    currentlyBanned?: number;
    totalBanned?: number;
    raw?: string;
  }> = [];
  if (installed) {
    try {
      const list = await host.runCommand(['fail2ban-client', 'status'], { timeoutMs: 8_000 });
      const text = `${list.stdout || ''}\n${list.stderr || ''}`;
      const m = text.match(/Jail list:\s*(.+)/i);
      const names = m
        ? m[1]
            .split(/[,\s]+/)
            .map((s) => s.trim())
            .filter(Boolean)
        : [];
      for (const name of names.slice(0, 24)) {
        try {
          const js = await host.runCommand(['fail2ban-client', 'status', name], {
            timeoutMs: 5_000,
          });
          const raw = `${js.stdout || ''}`.trim();
          const cur = raw.match(/Currently banned:\s*(\d+)/i);
          const tot = raw.match(/Total banned:\s*(\d+)/i);
          jails.push({
            name,
            currentlyBanned: cur ? Number(cur[1]) : undefined,
            totalBanned: tot ? Number(tot[1]) : undefined,
            raw: raw.slice(0, 500),
          });
        } catch {
          jails.push({ name });
        }
      }
    } catch {
      /* ignore */
    }
  }

  return {
    installed,
    active,
    enabled,
    jails,
    executeEnabled: host.executeEnabled(),
    isRoot: host.isRoot(),
    defaultJails,
  };
}

/** List banned IPs for a jail (or all jails). Read is best-effort (no EXECUTE required). */
export async function fail2banBannedIps(
  host: HostExecutor,
  jail?: string,
): Promise<{
  ok: boolean;
  notes: string[];
  items: Array<{ jail: string; ip: string }>;
  requiresExecute: boolean;
  blocked?: boolean;
}> {
  const items: Array<{ jail: string; ip: string }> = [];
  const jails: string[] = [];
  if (jail) {
    jails.push(jail);
  } else {
    const st = await probeFail2banStatus(host);
    jails.push(...st.jails.map((j) => j.name));
  }
  if (!jails.length) {
    return {
      ok: true,
      requiresExecute: false,
      items: [],
      notes: ['無作用中 jail 或 fail2ban 未運行'],
    };
  }
  for (const j of jails.slice(0, 20)) {
    const r = await host.runCommand(['fail2ban-client', 'status', j], { timeoutMs: 8_000 });
    const text = `${r.stdout || ''}\n${r.stderr || ''}`;
    if (r.exitCode !== 0 && /permission|root|error/i.test(text)) {
      return {
        ok: false,
        blocked: !host.executeEnabled(),
        requiresExecute: !host.executeEnabled(),
        items: [],
        notes: [
          host.executeEnabled()
            ? '讀取 banned 失敗（權限或服務）'
            : '讀取 banned 可能需更高權限；unban／ban 仍需 YSK_EXECUTE',
        ],
      };
    }
    const m = text.match(/Banned IP list:\s*(.+)/i);
    if (!m) continue;
    const ips = m[1]
      .split(/[,\s]+/)
      .map((s) => s.trim())
      .filter((ip) => /^\d{1,3}(\.\d{1,3}){3}$/.test(ip) || ip.includes(':'));
    for (const ip of ips) items.push({ jail: j, ip });
  }
  return {
    ok: true,
    requiresExecute: false,
    items,
    notes: [`共 ${items.length} 個 banned IP`],
  };
}

export async function fail2banUnban(
  host: HostExecutor,
  jail: string,
  ip: string,
): Promise<{ ok: boolean; notes: string[]; requiresExecute: boolean; blocked?: boolean }> {
  if (!host.executeEnabled()) {
    return {
      ok: false,
      blocked: true,
      requiresExecute: true,
      notes: ['無法 unban：未開啟系統變更權限'],
    };
  }
  const safeJail = jail.replace(/[^a-zA-Z0-9._-]/g, '');
  const safeIp = ip.trim();
  const r = await host.runCommand(['fail2ban-client', 'set', safeJail, 'unbanip', safeIp], {
    timeoutMs: 10_000,
  });
  return {
    ok: r.exitCode === 0,
    requiresExecute: false,
    notes: [
      r.exitCode === 0
        ? `已 unban ${safeIp} @ ${safeJail}`
        : `unban 失敗: ${r.stderr || r.stdout}`,
    ],
  };
}

export async function fail2banIgnoreIp(
  host: HostExecutor,
  dataDir: string | undefined,
  ip: string,
  action: 'add' | 'remove' = 'add',
): Promise<{ ok: boolean; notes: string[]; written: string[]; requiresExecute: boolean; blocked?: boolean }> {
  const written: string[] = [];
  const notes: string[] = [];
  const safeIp = ip.trim();
  if (!/^\d{1,3}(\.\d{1,3}){3}$/.test(safeIp) && !safeIp.includes(':')) {
    return { ok: false, notes: ['無效 IP'], written, requiresExecute: false };
  }
  // Persist ignore list under dataDir
  if (dataDir) {
    const dir = join(dataDir, 'fail2ban');
    mkdirSync(dir, { recursive: true });
    const listPath = join(dir, 'ignoreip.txt');
    let list: string[] = [];
    if (existsSync(listPath)) {
      list = readFileSync(listPath, 'utf8')
        .split(/\n/)
        .map((s) => s.trim())
        .filter(Boolean);
    }
    if (action === 'add' && !list.includes(safeIp)) list.push(safeIp);
    if (action === 'remove') list = list.filter((x) => x !== safeIp);
    writeFileSync(listPath, list.join('\n') + (list.length ? '\n' : ''), 'utf8');
    written.push(listPath);
    notes.push(`管理白名單: ${listPath} (${list.length} 項)`);
  }
  if (!host.executeEnabled()) {
    return {
      ok: true,
      notes: [...notes, '僅寫入管理檔；套用到 fail2ban 需系統變更權限'],
      written,
      requiresExecute: true,
      blocked: true,
    };
  }
  // Best-effort: set ignoreip on sshd jail
  const r = await host.runCommand(
    ['fail2ban-client', 'set', 'sshd', action === 'add' ? 'addignoreip' : 'delignoreip', safeIp],
    { timeoutMs: 10_000 },
  );
  notes.push(
    r.exitCode === 0
      ? `sshd ignoreip ${action} ${safeIp}`
      : `fail2ban-client ignoreip: ${r.stderr || r.stdout || 'failed'}（管理檔已寫）`,
  );
  return { ok: true, notes, written, requiresExecute: false };
}

/**
 * Write ufw script under dataDir; apply only when EXECUTE+root.
 * Never fakes ok=true when apply was requested but skipped/failed.
 */
export async function applyFirewall(input: {
  host: HostExecutor;
  dataDir?: string;
  allowSmtp?: boolean;
  apply?: boolean;
  extraTcpPorts?: number[];
}): Promise<ApplyResult & { requiresExecute: boolean; requiresRoot: boolean }> {
  const plan = planFirewall({
    allowSmtp: input.allowSmtp,
    extraTcpPorts: input.extraTcpPorts,
  });
  const notes = ['Rules generated by planFirewall'];
  const written: string[] = [];
  if (input.dataDir) {
    const dir = join(input.dataDir, 'firewall');
    mkdirSync(dir, { recursive: true });
    const scriptPath = join(dir, 'ufw-apply.sh');
    const body = [
      '#!/usr/bin/env bash',
      '# Generated by YSK Server — review before running',
      'set -euo pipefail',
      ...plan.rules.map((r) => r),
      '',
    ].join('\n');
    writeFileSync(scriptPath, body, 'utf8');
    written.push(scriptPath);
    notes.push(`Script: ${scriptPath}`);
  }
  const commands = plan.commands.map((c) => ['bash', '-c', c]);
  const want = Boolean(input.apply);
  const execute = Boolean(want && input.host.executeEnabled() && input.host.isRoot());
  if (want && !execute) {
    const reason: BlockReason = !input.host.executeEnabled() ? 'no_execute' : 'no_root';
    notes.push(panelBlockMessage(reason));
    return {
      ok: false,
      executed: false,
      blocked: true,
      blockReason: reason,
      blockMessage: panelBlockMessage(reason),
      written,
      commands: plan.commands,
      commandResults: [],
      notes,
      requiresExecute: !input.host.executeEnabled(),
      requiresRoot: !input.host.isRoot(),
    };
  }
  const commandResults = await runAll(input.host, commands, execute);
  const ranOk = commandResults.every((c) => c.exitCode === 0);
  if (want && !ranOk) notes.push('ufw 指令執行失敗');
  else if (want) notes.push('已套用防火牆規則');
  return {
    ok: want ? execute && ranOk : true,
    executed: execute,
    written,
    commands: plan.commands,
    commandResults,
    notes: [...notes, `建議 fail2ban jails: ${plan.fail2banJails.join(', ')}`],
    requiresExecute: !input.host.executeEnabled(),
    requiresRoot: !input.host.isRoot(),
  };
}

/**
 * Write fail2ban jail.local under dataDir; optional apt install + enable.
 * Never reports ok=true for skipped system mutations when apply=true.
 */
export async function applyFail2ban(input: {
  dataDir: string;
  host: HostExecutor;
  /** When true, attempt apt install + systemctl (needs root + YSK_EXECUTE) */
  apply?: boolean;
  jails?: string[];
  bantime?: string;
  findtime?: string;
  maxretry?: number;
}): Promise<ApplyResult & { requiresExecute: boolean; requiresRoot: boolean; serviceActive?: string }> {
  const plan = planFirewall({});
  const jails = input.jails ?? plan.fail2banJails;
  // Prefer deep writer (ignoreip + policy)
  const { writeFail2banJailLocal } = await import('./fail2ban-ops.js');
  const { path: jailPath } = writeFail2banJailLocal(input.dataDir, {
    bantime: input.bantime ?? '1h',
    findtime: input.findtime ?? '10m',
    maxretry: input.maxretry ?? 5,
    jails,
  });
  const notes = [`Wrote ${jailPath}`, `Jails: ${jails.join(', ')}`];
  const commands: string[][] = [];
  if (input.apply) {
    commands.push([
      'bash',
      '-c',
      'command -v fail2ban-client >/dev/null || (apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y fail2ban)',
    ]);
    commands.push(['cp', jailPath, '/etc/fail2ban/jail.local']);
    commands.push(['systemctl', 'enable', '--now', 'fail2ban']);
    commands.push(['systemctl', 'reload', 'fail2ban']);
  }
  const execute = Boolean(input.apply && input.host.executeEnabled() && input.host.isRoot());
  if (input.apply && !execute) {
    const reason: BlockReason = !input.host.executeEnabled() ? 'no_execute' : 'no_root';
    notes.push(panelBlockMessage(reason));
    return {
      ok: false,
      executed: false,
      blocked: true,
      blockReason: reason,
      blockMessage: panelBlockMessage(reason),
      written: [jailPath],
      commands: commands.map((c) => c.join(' ')),
      commandResults: [],
      notes,
      requiresExecute: !input.host.executeEnabled(),
      requiresRoot: !input.host.isRoot(),
    };
  }
  const commandResults = await runAll(input.host, commands, execute);
  let serviceActive: string | undefined;
  if (execute || input.host.pathExists('/usr/bin/fail2ban-client')) {
    try {
      const st = await input.host.runCommand(['systemctl', 'is-active', 'fail2ban'], {
        timeoutMs: 5_000,
      });
      serviceActive = (st.stdout || st.stderr || '').trim();
      notes.push(`fail2ban is-active: ${serviceActive}`);
    } catch {
      serviceActive = 'unknown';
    }
  }
  const ranOk = commandResults.every((c) => c.exitCode === 0);
  if (input.apply && !ranOk) notes.push('fail2ban 套用指令失敗');
  else if (input.apply) notes.push('已套用 fail2ban');
  else notes.push('已寫入管理 jail.local（未要求套用系統）');
  return {
    ok: input.apply ? execute && ranOk : true,
    executed: execute,
    written: [jailPath],
    commands: commands.map((c) => c.join(' ')),
    commandResults,
    notes,
    requiresExecute: !input.host.executeEnabled(),
    requiresRoot: !input.host.isRoot(),
    serviceActive,
  };
}

/**
 * Write nginx proxy conf and optionally sync + reload.
 */
export async function applyNginxSite(input: {
  dataDir: string;
  serverName: string;
  upstream: string;
  ssl?: boolean;
  host: HostExecutor;
  reload?: boolean;
}): Promise<ApplyResult> {
  const conf = renderNginxProxy({
    serverName: input.serverName,
    upstream: input.upstream,
    ssl: Boolean(input.ssl),
    cloudflareRealIp: true,
  });
  const dir = join(input.dataDir, 'nginx', 'conf.d');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, `${input.serverName.replace(/[^a-z0-9.-]+/gi, '_')}.conf`);
  writeFileSync(path, conf, 'utf8');
  const notes = [`已寫入管理檔 ${path}`];
  const commands: string[][] = [];
  if (input.reload) {
    commands.push(['nginx', '-t']);
    commands.push(['systemctl', 'reload', 'nginx']);
  }
  const execute = Boolean(input.reload && input.host.executeEnabled());
  if (input.reload && !input.host.executeEnabled()) {
    notes.push('無法重載 Nginx：需要系統變更權限');
    return {
      ok: false,
      executed: false,
      blocked: true,
      blockReason: 'no_execute',
      blockMessage: panelBlockMessage('no_execute'),
      written: [path],
      commands: commands.map((c) => c.join(' ')),
      commandResults: [],
      notes,
    };
  }
  const commandResults = await runAll(input.host, commands, execute);
  const failed = commandResults.some((r) => r.exitCode !== 0);
  if (input.reload && failed) {
    notes.push('nginx -t 或 reload 失敗');
  } else if (input.reload && execute) {
    notes.push('已重載 Nginx');
  } else if (!input.reload) {
    notes.push('僅寫入管理檔（未要求重載）');
  }
  return {
    ok: !failed,
    executed: execute,
    written: [path],
    commands: commands.map((c) => c.join(' ')),
    commandResults,
    notes,
  };
}

/**
 * Install systemd unit for control plane from template.
 */
export function writeControlPlaneSystemdUnit(input: {
  dataDir: string;
  nodePath?: string;
  cliPath: string;
  user?: string;
}): { unitPath: string; content: string } {
  const dir = join(input.dataDir, 'systemd');
  mkdirSync(dir, { recursive: true });
  const unitPath = join(dir, 'ysk-server.service');
  const node = input.nodePath ?? process.execPath;
  const user = input.user ?? 'root';
  const content = `[Unit]
Description=YSK Server control plane
After=network.target

[Service]
Type=simple
User=${user}
WorkingDirectory=${input.dataDir}
Environment=NODE_ENV=production
ExecStart=${node} ${input.cliPath} serve --config ${join(input.dataDir, 'config.json')}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
`;
  writeFileSync(unitPath, content, 'utf8');
  return { unitPath, content };
}

export async function installControlPlaneSystemd(input: {
  dataDir: string;
  cliPath: string;
  host: HostExecutor;
  enable?: boolean;
}): Promise<ApplyResult> {
  const { unitPath } = writeControlPlaneSystemdUnit({
    dataDir: input.dataDir,
    cliPath: input.cliPath,
  });
  const notes = [`已寫入 unit 範本 ${unitPath}`];
  const commands: string[][] = [];
  if (input.enable) {
    commands.push(['cp', unitPath, '/etc/systemd/system/ysk-server.service']);
    commands.push(['systemctl', 'daemon-reload']);
    commands.push(['systemctl', 'enable', '--now', 'ysk-server']);
  }
  const canExecute = Boolean(input.host.executeEnabled() && input.host.isRoot());
  const execute = Boolean(input.enable && canExecute);
  if (input.enable && !execute) {
    const reason: BlockReason = !input.host.executeEnabled() ? 'no_execute' : 'no_root';
    notes.push('systemd 啟用未能執行：需要系統變更權限與管理員');
    return {
      ok: false,
      executed: false,
      blocked: true,
      blockReason: reason,
      blockMessage: panelBlockMessage(reason),
      written: [unitPath],
      commands: commands.map((c) => c.join(' ')),
      commandResults: [],
      notes,
    };
  }
  const commandResults = await runAll(input.host, commands, execute);
  const failed = commandResults.some((r) => r.exitCode !== 0);
  if (input.enable && failed) notes.push('systemctl 指令失敗');
  else if (input.enable) notes.push('已安裝並嘗試啟用 ysk-server.service');
  else notes.push('僅寫入範本（未要求 enable）');
  return {
    ok: !failed,
    executed: execute,
    written: [unitPath],
    commands: commands.map((c) => c.join(' ')),
    commandResults,
    notes,
  };
}

/** Probe control-plane unit active/enabled state (honest status for panel). */
export async function probeControlPlaneSystemd(
  host: HostExecutor,
  dataDir?: string,
): Promise<{
  unit: string;
  unitPathHint: string;
  active: string;
  enabled: string;
  executeEnabled: boolean;
  isRoot: boolean;
  /** True when process can install+enable (EXECUTE + root) */
  canInstall: boolean;
  /** /etc/systemd unit file present */
  systemUnitExists: boolean;
  /** dataDir managed template path if dataDir provided */
  managedUnitPath: string | null;
  managedUnitExists: boolean;
  /** systemctl show subset (best-effort) */
  show: {
    mainPid: string | null;
    activeEnterTimestamp: string | null;
    fragmentPath: string | null;
    description: string | null;
  };
}> {
  const unit = 'ysk-server';
  const unitPathHint = '/etc/systemd/system/ysk-server.service';
  let active = 'unknown';
  let enabled = 'unknown';
  try {
    const a = await host.runCommand(['systemctl', 'is-active', unit], { timeoutMs: 5_000 });
    active = (a.stdout || a.stderr || 'unknown').trim().split('\n')[0] || 'unknown';
  } catch {
    active = 'unknown';
  }
  try {
    const e = await host.runCommand(['systemctl', 'is-enabled', unit], { timeoutMs: 5_000 });
    enabled = (e.stdout || e.stderr || 'unknown').trim().split('\n')[0] || 'unknown';
  } catch {
    enabled = 'unknown';
  }

  let systemUnitExists = false;
  try {
    systemUnitExists = host.pathExists(unitPathHint);
  } catch {
    systemUnitExists = false;
  }

  const managedUnitPath = dataDir ? join(dataDir, 'systemd', 'ysk-server.service') : null;
  let managedUnitExists = false;
  if (managedUnitPath) {
    try {
      managedUnitExists = host.pathExists(managedUnitPath) || existsSync(managedUnitPath);
    } catch {
      managedUnitExists = false;
    }
  }

  const show = {
    mainPid: null as string | null,
    activeEnterTimestamp: null as string | null,
    fragmentPath: null as string | null,
    description: null as string | null,
  };
  try {
    const s = await host.runCommand(
      [
        'systemctl',
        'show',
        unit,
        '-p',
        'MainPID',
        '-p',
        'ActiveEnterTimestamp',
        '-p',
        'FragmentPath',
        '-p',
        'Description',
        '--no-page',
      ],
      { timeoutMs: 5_000 },
    );
    if (s.exitCode === 0 && s.stdout) {
      for (const line of s.stdout.split('\n')) {
        const i = line.indexOf('=');
        if (i <= 0) continue;
        const k = line.slice(0, i).trim();
        const v = line.slice(i + 1).trim();
        if (k === 'MainPID' && v && v !== '0') show.mainPid = v;
        if (k === 'ActiveEnterTimestamp' && v && v !== 'n/a') show.activeEnterTimestamp = v;
        if (k === 'FragmentPath' && v) show.fragmentPath = v;
        if (k === 'Description' && v) show.description = v;
      }
    }
  } catch {
    /* best-effort */
  }

  const executeEnabled = host.executeEnabled();
  const isRoot = host.isRoot();
  return {
    unit,
    unitPathHint,
    active,
    enabled,
    executeEnabled,
    isRoot,
    canInstall: executeEnabled && isRoot,
    systemUnitExists,
    managedUnitPath,
    managedUnitExists,
    show,
  };
}

// silence unused import if any
void copyFileSync;
