/**
 * System-level apply orchestrators: write configs under dataDir, optionally install/copy with YSK_EXECUTE.
 */

import { mkdirSync, writeFileSync, existsSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';
import type { HostExecutor } from '../host/executor.js';
import { planEmailStackInstall } from '../email/dns-records.js';
import { planLetsEncrypt, renderNginxProxy } from './nginx-ssl.js';
import { renderPhpVhost, selectPhpRuntime } from './runtime.js';
import { planFtps, planFirewall } from './extras.js';
import { ErrorCodes, YskError } from '@ysk/shared';

export interface ApplyResult {
  ok: boolean;
  written: string[];
  commands: string[];
  commandResults: Array<{ argv: string[]; exitCode: number; stderr: string }>;
  notes: string[];
}

async function runAll(
  host: HostExecutor,
  commands: string[][],
  execute: boolean,
): Promise<ApplyResult['commandResults']> {
  const out: ApplyResult['commandResults'] = [];
  if (!execute) return out;
  for (const argv of commands) {
    const r = await host.runCommand(argv, { timeoutMs: 180_000 });
    out.push({ argv, exitCode: r.exitCode, stderr: r.stderr });
  }
  return out;
}

/**
 * Write Postfix/Dovecot/OpenDKIM managed configs + install helper;
 * optionally apt-install when root+EXECUTE. Never fakes ok when install requested but skipped.
 */
export async function applyEmailStack(input: {
  dataDir: string;
  domain: string;
  mailHostname?: string;
  host: HostExecutor;
  installPackages?: boolean;
}): Promise<
  ApplyResult & {
    serviceStatus?: Record<string, string>;
    requiresExecute: boolean;
    requiresRoot: boolean;
  }
> {
  const domain = input.domain.trim().toLowerCase();
  if (!domain) throw new YskError(ErrorCodes.VALIDATION, 'domain required', { httpStatus: 400 });
  const mailHost = input.mailHostname ?? `mail.${domain}`;
  const dir = join(input.dataDir, 'email', domain);
  mkdirSync(join(dir, 'postfix'), { recursive: true });
  mkdirSync(join(dir, 'dovecot'), { recursive: true });
  mkdirSync(join(dir, 'opendkim'), { recursive: true });

  const certBase = `/etc/letsencrypt/live/${mailHost}`;
  const mainCf = [
    `# Generated by YSK Server for ${domain}`,
    `myhostname = ${mailHost}`,
    `myorigin = ${domain}`,
    'inet_interfaces = all',
    'inet_protocols = ipv4',
    'smtpd_banner = $myhostname ESMTP YSK',
    'smtpd_tls_security_level = may',
    `smtpd_tls_cert_file = ${certBase}/fullchain.pem`,
    `smtpd_tls_key_file = ${certBase}/privkey.pem`,
    'smtp_tls_security_level = may',
    'smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination',
    'smtpd_recipient_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination',
    'mynetworks = 127.0.0.0/8 [::1]/128',
    'home_mailbox = Maildir/',
    'milter_default_action = accept',
    'milter_protocol = 6',
    'smtpd_milters = inet:localhost:8891',
    'non_smtpd_milters = inet:localhost:8891',
    '',
  ].join('\n');
  const masterCfSnippet = [
    '# YSK snippet — ensure submission/smtps (merge carefully into /etc/postfix/master.cf)',
    'submission inet n       -       y       -       -       smtpd',
    '  -o syslog_name=postfix/submission',
    '  -o smtpd_tls_security_level=encrypt',
    '  -o smtpd_sasl_auth_enable=yes',
    'smtps     inet n       -       y       -       -       smtpd',
    '  -o syslog_name=postfix/smtps',
    '  -o smtpd_tls_wrappermode=yes',
    '  -o smtpd_sasl_auth_enable=yes',
    '',
  ].join('\n');
  const dovecot = [
    '# Generated by YSK Server',
    'protocols = imap lmtp',
    'mail_location = maildir:~/Maildir',
    'ssl = required',
    `ssl_cert = <${certBase}/fullchain.pem`,
    `ssl_key = <${certBase}/privkey.pem`,
    'auth_mechanisms = plain login',
    'disable_plaintext_auth = yes',
    '',
  ].join('\n');
  const opendkim = [
    'Syslog yes',
    'Mode sv',
    'Canonicalization relaxed/simple',
    `Domain ${domain}`,
    'Selector default',
    `KeyFile ${dir}/opendkim/default.private`,
    'Socket inet:8891@localhost',
    'PidFile /run/opendkim/opendkim.pid',
    '',
  ].join('\n');
  const keyTable = `default._domainkey.${domain} ${domain}:default:${dir}/opendkim/default.private\n`;
  const signingTable = `*@${domain} default._domainkey.${domain}\n`;

  const written = [
    join(dir, 'postfix', 'main.cf'),
    join(dir, 'postfix', 'master.cf.ysk-snippet'),
    join(dir, 'dovecot', 'dovecot.conf'),
    join(dir, 'opendkim', 'opendkim.conf'),
    join(dir, 'opendkim', 'KeyTable'),
    join(dir, 'opendkim', 'SigningTable'),
    join(dir, 'install-mta.sh'),
    join(dir, 'README.txt'),
  ];
  writeFileSync(written[0], mainCf, 'utf8');
  writeFileSync(written[1], masterCfSnippet, 'utf8');
  writeFileSync(written[2], dovecot, 'utf8');
  writeFileSync(written[3], opendkim, 'utf8');
  writeFileSync(written[4], keyTable, 'utf8');
  writeFileSync(written[5], signingTable, 'utf8');

  const plan = planEmailStackInstall(domain);
  const installScript = [
    '#!/usr/bin/env bash',
    `# YSK Server MTA install helper for ${domain}`,
    'set -euo pipefail',
    `DOMAIN=${JSON.stringify(domain)}`,
    `MAILHOST=${JSON.stringify(mailHost)}`,
    `DIR=${JSON.stringify(dir)}`,
    'export DEBIAN_FRONTEND=noninteractive',
    `apt-get update`,
    `apt-get install -y ${plan.packages.join(' ')}`,
    'cp "$DIR/postfix/main.cf" /etc/postfix/main.cf',
    'cp "$DIR/dovecot/dovecot.conf" /etc/dovecot/dovecot.conf',
    'cp "$DIR/opendkim/opendkim.conf" /etc/opendkim.conf || true',
    'systemctl enable --now postfix dovecot opendkim || true',
    'systemctl reload postfix || systemctl restart postfix',
    'echo "MTA configs applied for $DOMAIN — still need DNS/PTR/Port25"',
    '',
  ].join('\n');
  writeFileSync(written[6], installScript, 'utf8');
  writeFileSync(
    written[7],
    [
      `YSK Server managed mail configs for ${domain}`,
      `Mail host: ${mailHost}`,
      'Always review before copy to /etc.',
      'System apply install needs: root + YSK_EXECUTE=1',
      `Helper: ${written[6]}`,
      `Ports: ${plan.ports.join(', ')}`,
      'External: SPF/DKIM/DMARC/PTR + Port 25 or SMTP relay',
      '',
    ].join('\n'),
    'utf8',
  );

  const notes = [...plan.notes, `Configs under ${dir}`, `Install helper: ${written[6]}`];
  const commands: string[][] = [];
  if (input.installPackages) {
    commands.push(['apt-get', 'update']);
    commands.push([
      'bash',
      '-c',
      `DEBIAN_FRONTEND=noninteractive apt-get install -y ${plan.packages.join(' ')}`,
    ]);
    commands.push(['cp', written[0], '/etc/postfix/main.cf']);
    commands.push(['cp', written[2], '/etc/dovecot/dovecot.conf']);
    commands.push(['systemctl', 'enable', '--now', 'postfix']);
    commands.push(['systemctl', 'enable', '--now', 'dovecot']);
    commands.push(['systemctl', 'reload', 'postfix']);
  }

  const wantInstall = Boolean(input.installPackages);
  const execute = Boolean(wantInstall && input.host.executeEnabled() && input.host.isRoot());
  if (wantInstall && !execute) {
    notes.push('Package install skipped: need root + YSK_EXECUTE=1 (never fake success)');
  }
  const commandResults = await runAll(input.host, commands, execute);
  const ranOk = commandResults.every((c) => c.exitCode === 0);
  const serviceStatus: Record<string, string> = {};
  for (const svc of ['postfix', 'dovecot', 'opendkim']) {
    try {
      const st = await input.host.runCommand(['systemctl', 'is-active', svc], { timeoutMs: 5_000 });
      serviceStatus[svc] = (st.stdout || st.stderr || `exit_${st.exitCode}`).trim();
    } catch {
      serviceStatus[svc] = 'unknown';
    }
  }
  notes.push(`services: ${JSON.stringify(serviceStatus)}`);
  return {
    ok: wantInstall ? execute && ranOk : true,
    written,
    commands: commands.map((a) => a.join(' ')),
    commandResults,
    notes,
    serviceStatus,
    requiresExecute: !input.host.executeEnabled(),
    requiresRoot: !input.host.isRoot(),
  };
}

/**
 * Certbot plan + optional run for a domain.
 */
export async function applyLetsEncrypt(input: {
  domain: string;
  email: string;
  host: HostExecutor;
  run?: boolean;
}): Promise<ApplyResult> {
  const plan = planLetsEncrypt({
    domain: input.domain,
    email: input.email,
    provider: 'letsencrypt',
    challenge: 'http-01',
  });
  const notes = [...plan.notes];
  const commands = plan.commands.map((c) => ['bash', '-c', c]);
  const want = Boolean(input.run);
  const execute = Boolean(want && input.host.executeEnabled() && input.host.isRoot());
  if (want && !execute) {
    notes.push('certbot run skipped: need root + YSK_EXECUTE=1 (never fake success)');
  }
  const commandResults = await runAll(input.host, commands, execute);
  const ranOk = commandResults.every((c) => c.exitCode === 0);
  return {
    ok: want ? execute && ranOk : true,
    written: [],
    commands: plan.commands,
    commandResults,
    notes,
  };
}

/**
 * Write PHP vhost under dataDir; optional copy to Apache sites-available.
 */
export async function applyPhpHosting(input: {
  dataDir: string;
  domain: string;
  docRoot: string;
  phpVersion: string;
  poolName: string;
  host: HostExecutor;
  enableSite?: boolean;
}): Promise<ApplyResult> {
  const rt = selectPhpRuntime(input.phpVersion);
  const dir = join(input.dataDir, 'apache', 'sites');
  mkdirSync(dir, { recursive: true });
  mkdirSync(input.docRoot, { recursive: true });
  const conf = renderPhpVhost({
    domain: input.domain,
    docRoot: input.docRoot,
    phpVersion: rt.version,
    poolName: input.poolName,
  });
  const path = join(dir, `${input.poolName}.conf`);
  writeFileSync(path, conf, 'utf8');
  const index = join(input.docRoot, 'index.php');
  if (!existsSync(index)) {
    writeFileSync(index, '<?php echo "YSK PHP OK\\n";\n', 'utf8');
  }
  const notes = [`PHP ${rt.version} vhost at ${path}`, `binary ${rt.binaryPath}`];
  const commands: string[][] = [];
  if (input.enableSite) {
    commands.push(['cp', path, `/etc/apache2/sites-available/${input.poolName}.conf`]);
    commands.push(['a2ensite', input.poolName]);
    commands.push(['systemctl', 'reload', 'apache2']);
  }
  const execute = Boolean(input.enableSite && input.host.executeEnabled() && input.host.isRoot());
  if (input.enableSite && !execute) notes.push('Apache enable skipped: need root + YSK_EXECUTE=1');
  const commandResults = await runAll(input.host, commands, execute);
  const ranOk = commandResults.every((c) => c.exitCode === 0);
  let phpActive: string | undefined;
  if (execute) {
    const st = await input.host.runCommand(['systemctl', 'is-active', `php${rt.version}-fpm`], {
      timeoutMs: 5_000,
    });
    phpActive = (st.stdout || st.stderr || '').trim();
    notes.push(`php-fpm is-active: ${phpActive}`);
  }
  return {
    ok: execute ? ranOk : true,
    written: [path, index],
    commands: commands.map((c) => c.join(' ')),
    commandResults,
    notes: phpActive ? [...notes, `php_fpm=${phpActive}`] : notes,
  };
}

/**
 * Write FTPS (vsftpd) snippet under dataDir; optional install.
 */
export async function applyFtps(input: {
  dataDir: string;
  domain: string;
  host: HostExecutor;
  install?: boolean;
}): Promise<ApplyResult> {
  const plan = planFtps({ domain: input.domain });
  const dir = join(input.dataDir, 'ftps');
  mkdirSync(dir, { recursive: true });
  const confPath = join(dir, 'vsftpd.conf');
  writeFileSync(confPath, plan.configSnippet + '\n', 'utf8');
  const notes = [`Config ${confPath}`, `PASV ${plan.pasvMin}-${plan.pasvMax}`];
  const commands: string[][] = input.install
    ? plan.commands.map((c) => ['bash', '-c', c])
    : [];
  if (input.install) {
    commands.push(['cp', confPath, '/etc/vsftpd.conf']);
  }
  const execute = Boolean(input.install && input.host.executeEnabled() && input.host.isRoot());
  if (input.install && !execute) notes.push('FTPS install skipped: need root + YSK_EXECUTE=1');
  const commandResults = await runAll(input.host, commands, execute);
  return {
    ok: true,
    written: [confPath],
    commands: commands.map((c) => c.join(' ')),
    commandResults,
    notes,
  };
}

/**
 * Write ufw script under dataDir; apply only when EXECUTE+root.
 * Never fakes ok=true when apply was requested but skipped/failed.
 */
export async function applyFirewall(input: {
  host: HostExecutor;
  dataDir?: string;
  allowSmtp?: boolean;
  apply?: boolean;
  extraTcpPorts?: number[];
}): Promise<ApplyResult & { requiresExecute: boolean; requiresRoot: boolean }> {
  const plan = planFirewall({
    allowSmtp: input.allowSmtp,
    extraTcpPorts: input.extraTcpPorts,
  });
  const notes = ['Rules generated by planFirewall'];
  const written: string[] = [];
  if (input.dataDir) {
    const dir = join(input.dataDir, 'firewall');
    mkdirSync(dir, { recursive: true });
    const scriptPath = join(dir, 'ufw-apply.sh');
    const body = [
      '#!/usr/bin/env bash',
      '# Generated by YSK Server — review before running',
      'set -euo pipefail',
      ...plan.rules.map((r) => r),
      '',
    ].join('\n');
    writeFileSync(scriptPath, body, 'utf8');
    written.push(scriptPath);
    notes.push(`Script: ${scriptPath}`);
  }
  const commands = plan.commands.map((c) => ['bash', '-c', c]);
  const want = Boolean(input.apply);
  const execute = Boolean(want && input.host.executeEnabled() && input.host.isRoot());
  if (want && !execute) {
    notes.push('Firewall apply skipped: need root + YSK_EXECUTE=1 (never fake success)');
  }
  const commandResults = await runAll(input.host, commands, execute);
  const ranOk = commandResults.every((c) => c.exitCode === 0);
  return {
    ok: want ? execute && ranOk : true,
    written,
    commands: plan.commands,
    commandResults,
    notes: [...notes, `fail2ban jails: ${plan.fail2banJails.join(', ')}`],
    requiresExecute: !input.host.executeEnabled(),
    requiresRoot: !input.host.isRoot(),
  };
}

/**
 * Write fail2ban jail.local under dataDir; optional apt install + enable.
 * Never reports ok=true for skipped system mutations when apply=true.
 */
export async function applyFail2ban(input: {
  dataDir: string;
  host: HostExecutor;
  /** When true, attempt apt install + systemctl (needs root + YSK_EXECUTE) */
  apply?: boolean;
  jails?: string[];
}): Promise<ApplyResult & { requiresExecute: boolean; requiresRoot: boolean; serviceActive?: string }> {
  const plan = planFirewall({});
  const jails = input.jails ?? plan.fail2banJails;
  const dir = join(input.dataDir, 'fail2ban');
  mkdirSync(dir, { recursive: true });
  const jailPath = join(dir, 'jail.local');
  const jailBody = [
    '# Generated by YSK Server',
    '[DEFAULT]',
    'bantime = 1h',
    'findtime = 10m',
    'maxretry = 5',
    'backend = systemd',
    '',
    ...jails.flatMap((j) => [`[${j}]`, 'enabled = true', '']),
  ].join('\n');
  writeFileSync(jailPath, jailBody, 'utf8');
  const notes = [`Wrote ${jailPath}`, `Jails: ${jails.join(', ')}`];
  const commands: string[][] = [];
  if (input.apply) {
    commands.push(['apt-get', 'update']);
    commands.push([
      'bash',
      '-c',
      'DEBIAN_FRONTEND=noninteractive apt-get install -y fail2ban',
    ]);
    commands.push(['cp', jailPath, '/etc/fail2ban/jail.local']);
    commands.push(['systemctl', 'enable', '--now', 'fail2ban']);
    commands.push(['systemctl', 'reload', 'fail2ban']);
  }
  const execute = Boolean(input.apply && input.host.executeEnabled() && input.host.isRoot());
  if (input.apply && !execute) {
    notes.push('fail2ban install skipped: need root + YSK_EXECUTE=1');
  }
  const commandResults = await runAll(input.host, commands, execute);
  let serviceActive: string | undefined;
  if (execute || input.host.pathExists('/usr/bin/fail2ban-client')) {
    try {
      const st = await input.host.runCommand(['systemctl', 'is-active', 'fail2ban'], {
        timeoutMs: 5_000,
      });
      serviceActive = (st.stdout || st.stderr || '').trim();
      notes.push(`fail2ban is-active: ${serviceActive}`);
    } catch {
      serviceActive = 'unknown';
    }
  }
  const ranOk = commandResults.every((c) => c.exitCode === 0);
  return {
    ok: input.apply ? execute && ranOk : true,
    written: [jailPath],
    commands: commands.map((c) => c.join(' ')),
    commandResults,
    notes,
    requiresExecute: !input.host.executeEnabled(),
    requiresRoot: !input.host.isRoot(),
    serviceActive,
  };
}

/**
 * Write nginx proxy conf and optionally sync + reload.
 */
export async function applyNginxSite(input: {
  dataDir: string;
  serverName: string;
  upstream: string;
  ssl?: boolean;
  host: HostExecutor;
  reload?: boolean;
}): Promise<ApplyResult> {
  const conf = renderNginxProxy({
    serverName: input.serverName,
    upstream: input.upstream,
    ssl: Boolean(input.ssl),
    cloudflareRealIp: true,
  });
  const dir = join(input.dataDir, 'nginx', 'conf.d');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, `${input.serverName.replace(/[^a-z0-9.-]+/gi, '_')}.conf`);
  writeFileSync(path, conf, 'utf8');
  const notes = [`Wrote ${path}`];
  const commands: string[][] = [];
  if (input.reload) {
    commands.push(['nginx', '-t']);
    commands.push(['systemctl', 'reload', 'nginx']);
  }
  const execute = Boolean(input.reload && input.host.executeEnabled());
  if (input.reload && !input.host.executeEnabled()) {
    notes.push('nginx reload skipped: set YSK_EXECUTE=1');
  }
  const commandResults = await runAll(input.host, commands, execute);
  return {
    ok: true,
    written: [path],
    commands: commands.map((c) => c.join(' ')),
    commandResults,
    notes,
  };
}

/**
 * Install systemd unit for control plane from template.
 */
export function writeControlPlaneSystemdUnit(input: {
  dataDir: string;
  nodePath?: string;
  cliPath: string;
  user?: string;
}): { unitPath: string; content: string } {
  const dir = join(input.dataDir, 'systemd');
  mkdirSync(dir, { recursive: true });
  const unitPath = join(dir, 'ysk-server.service');
  const node = input.nodePath ?? process.execPath;
  const user = input.user ?? 'root';
  const content = `[Unit]
Description=YSK Server control plane
After=network.target

[Service]
Type=simple
User=${user}
WorkingDirectory=${input.dataDir}
Environment=NODE_ENV=production
ExecStart=${node} ${input.cliPath} serve --config ${join(input.dataDir, 'config.json')}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
`;
  writeFileSync(unitPath, content, 'utf8');
  return { unitPath, content };
}

export async function installControlPlaneSystemd(input: {
  dataDir: string;
  cliPath: string;
  host: HostExecutor;
  enable?: boolean;
}): Promise<ApplyResult> {
  const { unitPath } = writeControlPlaneSystemdUnit({
    dataDir: input.dataDir,
    cliPath: input.cliPath,
  });
  const notes = [`Unit template at ${unitPath}`];
  const commands: string[][] = [];
  if (input.enable) {
    commands.push(['cp', unitPath, '/etc/systemd/system/ysk-server.service']);
    commands.push(['systemctl', 'daemon-reload']);
    commands.push(['systemctl', 'enable', '--now', 'ysk-server']);
  }
  const execute = Boolean(input.enable && input.host.executeEnabled() && input.host.isRoot());
  if (input.enable && !execute) notes.push('systemd install skipped: need root + YSK_EXECUTE=1');
  const commandResults = await runAll(input.host, commands, execute);
  return {
    ok: true,
    written: [unitPath],
    commands: commands.map((c) => c.join(' ')),
    commandResults,
    notes,
  };
}

// silence unused import if any
void copyFileSync;
