/**
 * Write ~/.google_authenticator + plan/apply PAM/sshd notes.
 * Honest: dry-run default; apply needs execute.
 */

import {
  chmodSync,
  existsSync,
  mkdirSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { randomInt } from 'node:crypto';
import { join } from 'node:path';
import type { HostExecutor } from '../../host/executor.js';
import { shellQuote } from '../../hosting/project-user-run.js';
import { decryptPrivateKey, resolveMasterKey, secretsSshDir } from '../ssh-identity/crypto.js';
import {
  getSsh2faInternal,
  updateSsh2faStatus,
} from './store.js';
import type { Ssh2faPublic } from './types.js';
import { toPublicSsh2fa } from './types.js';

/**
 * google-authenticator file format (libpam-google-authenticator).
 * First line: base32 secret; " lines are options; trailing digits = scratch codes (optional).
 */
/**
 * @param scratchCodes optional emergency 8-digit codes (pam consumes once)
 */
export function buildGoogleAuthenticatorFile(
  secret: string,
  scratchCodes?: string[],
): string {
  const lines = [
    secret.trim(),
    '" RATE_LIMIT 3 30',
    '" WINDOW_SIZE 17',
    '" DISALLOW_REUSE',
    '" TOTP_AUTH',
  ];
  for (const c of scratchCodes ?? []) {
    const dig = c.replace(/\D/g, '').slice(0, 8);
    if (dig.length >= 6) lines.push(dig.padStart(8, '0').slice(0, 8));
  }
  lines.push('');
  return lines.join('\n');
}

export function generateScratchCodes(count = 5): string[] {
  const out: string[] = [];
  for (let i = 0; i < count; i++) {
    out.push(String(randomInt(0, 100_000_000)).padStart(8, '0'));
  }
  return out;
}

export function buildPamSshSnippet(): string {
  return [
    '# YSK Server — SSH TOTP (pam_google_authenticator)',
    '# Include from /etc/pam.d/sshd (after common-auth or at end of auth stack).',
    '# nullok: users without ~/.google_authenticator still login (key-only).',
    '# Remove nullok only when every interactive user has a file + recovery path.',
    'auth required pam_google_authenticator.so nullok',
    '',
  ].join('\n');
}

export function buildSshdTotpHints(): string {
  return [
    '# YSK Server — hints for SSH + TOTP (do not blindly paste on production)',
    '# OpenSSH 8.2+ often uses KbdInteractiveAuthentication instead of ChallengeResponseAuthentication',
    'UsePAM yes',
    'KbdInteractiveAuthentication yes',
    '# Prefer per-user Match (see buildSshdStrictMatchSnippet) — NOT global AuthenticationMethods',
    '# Keep at least one console / key-only recovery admin without 2FA file',
    '',
  ].join('\n');
}

/**
 * Per-user strict Match: publickey then TOTP; password off.
 * Only list users that already have .google_authenticator written.
 */
export function buildSshdStrictMatchSnippet(linuxUsers: string[]): string {
  const users = [...new Set(linuxUsers.map((u) => u.trim()).filter(Boolean))];
  if (!users.length) {
    return [
      '# YSK Server — no strict 2FA users yet',
      '# After install .google_authenticator, regenerate this Match block',
      '',
    ].join('\n');
  }
  // OpenSSH Match User: comma-separated patterns
  const pattern = users.join(',');
  return [
    '# Generated by YSK Server — Include from sshd_config.d/',
    '# Strict: publickey THEN keyboard-interactive (PAM TOTP)',
    '# WARNING: ensure recovery user is NOT in this list',
    `Match User ${pattern}`,
    '    PasswordAuthentication no',
    '    KbdInteractiveAuthentication yes',
    '    AuthenticationMethods publickey,keyboard-interactive',
    '    PubkeyAuthentication yes',
    '',
  ].join('\n');
}

export const SSHD_STRICT_SNIPPET_NAME = '98-ysk-ssh-2fa-strict.conf';

/** Project SFTP-style users (ysks_ or ysk_ prefix) — exclude from strict Match by default. */
export function isSftpOnlyStyleUser(linuxUser: string): boolean {
  return /^(ysks_|ysk_)/.test(linuxUser.trim());
}

export function planSsh2faStrictSnippet(input: {
  linuxUsers: string[];
  /** must remain outside Match for rescue */
  recoveryUsers?: string[];
  /** include project SFTP users (default false) */
  includeSftpUsers?: boolean;
}): {
  ok: boolean;
  snippet: string;
  users: string[];
  notes: string[];
  blocked?: boolean;
} {
  const recovery = new Set((input.recoveryUsers ?? []).map((u) => u.trim()).filter(Boolean));
  let users = [...new Set(input.linuxUsers.map((u) => u.trim()).filter(Boolean))].filter(
    (u) => !recovery.has(u),
  );
  const droppedSftp: string[] = [];
  if (!input.includeSftpUsers) {
    for (const u of users) {
      if (isSftpOnlyStyleUser(u)) droppedSftp.push(u);
    }
    users = users.filter((u) => !isSftpOnlyStyleUser(u));
  }
  const notes: string[] = [];
  if (recovery.size) {
    notes.push(`救援用戶排除：${[...recovery].join(', ')}`);
  }
  if (droppedSftp.length) {
    notes.push(
      `已排除專案 SFTP 風格用戶（ysks_/ysk_，internal-sftp 不適合 kbd-interactive）：${droppedSftp.join(', ')}`,
    );
  }
  const overlap = input.linuxUsers.filter((u) => recovery.has(u.trim()));
  if (overlap.length) {
    notes.push(`已從 strict 列表移除救援用戶：${overlap.join(', ')}`);
  }
  if (!users.length) {
    return {
      ok: false,
      snippet: buildSshdStrictMatchSnippet([]),
      users: [],
      notes: [...notes, '無可用 strict 用戶（全部是救援或未登記）'],
      blocked: true,
    };
  }
  notes.push(`${users.length} 個用戶將要求 publickey+TOTP、關閉 password`);
  notes.push('apply 後需 reload sshd；錯誤 Match 可能鎖死 — 先 dry-run');
  return {
    ok: true,
    snippet: buildSshdStrictMatchSnippet(users),
    users,
    notes,
  };
}

export async function applySshdStrictSnippet(input: {
  dataDir: string;
  host: HostExecutor;
  linuxUsers: string[];
  recoveryUsers?: string[];
  apply?: boolean;
  executeEnabled?: boolean;
}): Promise<{
  ok: boolean;
  dryRun: boolean;
  applied: boolean;
  blocked: boolean;
  snippet: string;
  notes: string[];
  written?: string[];
}> {
  const plan = planSsh2faStrictSnippet({
    linuxUsers: input.linuxUsers,
    recoveryUsers: input.recoveryUsers,
  });
  const notes = [...plan.notes];
  const managed = join(secretsSshDir(input.dataDir), SSHD_STRICT_SNIPPET_NAME);
  mkdirSync(secretsSshDir(input.dataDir), { recursive: true });
  writeFileSync(managed, plan.snippet, 'utf8');
  notes.push(`管理檔：${managed}`);

  if (!input.apply) {
    return {
      ok: plan.ok,
      dryRun: true,
      applied: false,
      blocked: Boolean(plan.blocked),
      snippet: plan.snippet,
      notes: [...notes, 'dry-run — 未寫入 /etc'],
      written: [managed],
    };
  }
  if (plan.blocked || !plan.ok) {
    return {
      ok: false,
      dryRun: false,
      applied: false,
      blocked: true,
      snippet: plan.snippet,
      notes,
      written: [managed],
    };
  }
  if (!input.executeEnabled) {
    return {
      ok: false,
      dryRun: false,
      applied: false,
      blocked: true,
      snippet: plan.snippet,
      notes: [...notes, 'blocked: 需要 YSK_EXECUTE=1'],
      written: [managed],
    };
  }
  const systemPath = `/etc/ssh/sshd_config.d/${SSHD_STRICT_SNIPPET_NAME}`;
  const r = await input.host.runCommand(
    [
      'bash',
      '-c',
      `cp ${JSON.stringify(managed)} ${JSON.stringify(systemPath)} && chmod 644 ${JSON.stringify(systemPath)} && (sshd -t 2>&1) && (systemctl reload sshd 2>/dev/null || systemctl reload ssh 2>/dev/null)`,
    ],
    { timeoutMs: 15_000 },
  );
  const ok = r.exitCode === 0;
  notes.push(
    ok
      ? `已安裝 ${systemPath} 並嘗試 reload sshd`
      : `安裝／sshd -t 失敗：${(r.stderr || r.stdout).slice(0, 200)}`,
  );
  return {
    ok,
    dryRun: false,
    applied: ok,
    blocked: false,
    snippet: plan.snippet,
    notes,
    written: [managed, systemPath],
  };
}

export type InstallSsh2faResult = {
  ok: boolean;
  dryRun: boolean;
  applied: boolean;
  blocked: boolean;
  requiresRoot: boolean;
  requiresExecute: boolean;
  plannedPath?: string;
  record?: Ssh2faPublic;
  notes: string[];
  pamSnippet?: string;
  sshdHints?: string;
  /** one-time on successful apply */
  scratchCodes?: string[];
};

export async function installSsh2faFile(input: {
  dataDir: string;
  id: string;
  apply?: boolean;
  host?: HostExecutor;
  executeEnabled?: boolean;
}): Promise<InstallSsh2faResult> {
  const notes: string[] = [];
  const row = getSsh2faInternal(input.dataDir, input.id);
  if (!row) {
    return {
      ok: false,
      dryRun: !input.apply,
      applied: false,
      blocked: false,
      requiresRoot: true,
      requiresExecute: true,
      notes: ['找不到登記'],
    };
  }

  const filePath = join(row.homeDir, '.google_authenticator');
  notes.push(`planned: ${filePath} mode 0400 owner ${row.linuxUser}`);
  notes.push('file written ≠ PAM active ≠ sshd requires TOTP');
  notes.push('專案 internal-sftp Match 用戶通常唔走 interactive shell — TOTP 主要影響 SSH shell/scp');

  const pamSnippet = buildPamSshSnippet();
  const sshdHints = buildSshdTotpHints();
  const managedPam = join(secretsSshDir(input.dataDir), 'pam-sshd-ysk-totp');
  const managedSshd = join(secretsSshDir(input.dataDir), 'sshd-totp-hints.conf');

  if (!input.apply) {
    notes.push('dry-run — pass apply/execute 才寫 home 檔');
    notes.push(`PAM 預覽會寫管理檔：${managedPam}`);
    return {
      ok: true,
      dryRun: true,
      applied: false,
      blocked: false,
      requiresRoot: true,
      requiresExecute: true,
      plannedPath: filePath,
      record: toPublicSsh2fa(row),
      notes,
      pamSnippet,
      sshdHints,
    };
  }

  if (!input.executeEnabled) {
    notes.push('blocked: 需要 YSK_EXECUTE=1');
    return {
      ok: false,
      dryRun: false,
      applied: false,
      blocked: true,
      requiresRoot: true,
      requiresExecute: true,
      plannedPath: filePath,
      record: toPublicSsh2fa(row),
      notes,
      pamSnippet,
      sshdHints,
    };
  }

  let secret: string;
  try {
    const master = resolveMasterKey(input.dataDir);
    secret = decryptPrivateKey(master.key, row.id, row.secretEnc);
  } catch (e) {
    return {
      ok: false,
      dryRun: false,
      applied: false,
      blocked: false,
      requiresRoot: true,
      requiresExecute: true,
      notes: [e instanceof Error ? e.message : 'decrypt failed'],
    };
  }

  const scratch = generateScratchCodes(5);
  const body = buildGoogleAuthenticatorFile(secret, scratch);
  try {
    mkdirSync(row.homeDir, { recursive: true });
    writeFileSync(filePath, body, { mode: 0o400 });
    try {
      chmodSync(filePath, 0o400);
    } catch {
      /* ignore */
    }
  } catch (e) {
    return {
      ok: false,
      dryRun: false,
      applied: false,
      blocked: false,
      requiresRoot: true,
      requiresExecute: true,
      plannedPath: filePath,
      notes: [`write failed: ${e instanceof Error ? e.message : String(e)}`],
    };
  }

  if (input.host) {
    const ch = await input.host.runCommand(
      [
        'bash',
        '-c',
        `chown ${shellQuote(row.linuxUser)}:${shellQuote(row.linuxUser)} ${shellQuote(filePath)} 2>&1; chmod 400 ${shellQuote(filePath)} 2>&1; stat -c '%a %U %G' ${shellQuote(filePath)} 2>&1 || true`,
      ],
      { timeoutMs: 10_000 },
    );
    const st = (ch.stdout || '').trim().split(/\n/).pop() || '';
    notes.push(
      ch.exitCode === 0
        ? `chown/chmod ok · ${st}`
        : `chown 可能失敗：${(ch.stderr || st).slice(0, 120)}`,
    );
    if (st && !/^400\b/.test(st)) {
      notes.push(`警告：期望 mode 400（stat: ${st}）`);
    }
  } else {
    notes.push('無 HostExecutor — 請手動 chown 檔案');
  }

  // Always write managed PAM/sshd docs under dataDir (safe)
  try {
    mkdirSync(secretsSshDir(input.dataDir), { recursive: true });
    writeFileSync(managedPam, pamSnippet, { mode: 0o644 });
    writeFileSync(managedSshd, sshdHints, { mode: 0o644 });
    notes.push(`PAM 片段（管理檔）：${managedPam}`);
    notes.push(`sshd 提示（管理檔）：${managedSshd}`);
  } catch {
    /* ignore */
  }

  const record = updateSsh2faStatus(input.dataDir, row.id, {
    status: 'file_written',
    filePath,
    writtenAt: new Date().toISOString(),
    notes: [...row.notes, `written ${filePath}`, '下一步：將 PAM 片段併入 /etc/pam.d/sshd（nullok）'],
  });

  notes.push('已寫入 .google_authenticator（含 5 組 scratch codes）');
  notes.push('下一步：系統安裝 libpam-google-authenticator + 合併 PAM 片段（見下方）');
  notes.push(
    `scratch（只此一次回應）：${scratch.join(' ')} — 請離線保存`,
  );

  return {
    ok: true,
    dryRun: false,
    applied: true,
    blocked: false,
    requiresRoot: true,
    requiresExecute: false,
    plannedPath: filePath,
    record: record ?? undefined,
    notes,
    pamSnippet,
    sshdHints,
    scratchCodes: scratch,
  };
}

export async function uninstallSsh2faFile(input: {
  dataDir: string;
  id: string;
  apply?: boolean;
  retire?: boolean;
}): Promise<InstallSsh2faResult> {
  const notes: string[] = [];
  const row = getSsh2faInternal(input.dataDir, input.id);
  if (!row) {
    return {
      ok: false,
      dryRun: !input.apply,
      applied: false,
      blocked: false,
      requiresRoot: false,
      requiresExecute: false,
      notes: ['找不到登記'],
    };
  }
  const path = row.filePath || join(row.homeDir, '.google_authenticator');
  notes.push(`will remove ${path}`);

  if (!input.apply) {
    return {
      ok: true,
      dryRun: true,
      applied: false,
      blocked: false,
      requiresRoot: false,
      requiresExecute: false,
      plannedPath: path,
      record: toPublicSsh2fa(row),
      notes: [...notes, 'dry-run'],
    };
  }

  if (existsSync(path)) {
    try {
      unlinkSync(path);
      notes.push('removed file');
    } catch (e) {
      notes.push(`remove failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  } else {
    notes.push('file already absent');
  }

  if (input.retire !== false) {
    updateSsh2faStatus(input.dataDir, row.id, {
      status: 'retired',
      notes: [...row.notes, 'uninstalled'],
    });
  } else {
    updateSsh2faStatus(input.dataDir, row.id, {
      status: 'confirmed',
      filePath: undefined,
      writtenAt: undefined,
    });
  }

  return {
    ok: true,
    dryRun: false,
    applied: true,
    blocked: false,
    requiresRoot: false,
    requiresExecute: false,
    plannedPath: path,
    notes,
  };
}

/** Host probe: package + pam file presence (read-only hints). */
export type Ssh2faHostHealth = {
  notes: string[];
  /** traffic light for UI */
  lights: {
    package: 'green' | 'yellow' | 'red';
    pam: 'green' | 'yellow' | 'red';
    kbdInteractive: 'green' | 'yellow' | 'red';
  };
  pamModule?: boolean;
  pamConfigured?: boolean;
  kbdInteractive?: boolean;
};

export async function probeSsh2faHost(host: HostExecutor): Promise<Ssh2faHostHealth> {
  const notes: string[] = [];
  const mod = await host.runCommand(
    [
      'bash',
      '-c',
      'ls /lib/x86_64-linux-gnu/security/pam_google_authenticator.so /usr/lib/x86_64-linux-gnu/security/pam_google_authenticator.so 2>/dev/null | head -1; dpkg -l libpam-google-authenticator 2>/dev/null | grep -E "^ii" || true',
    ],
    { timeoutMs: 8_000 },
  );
  const pamModule =
    (mod.stdout || '').includes('pam_google_authenticator.so') ||
    (mod.stdout || '').includes('libpam-google-authenticator');
  notes.push(
    pamModule
      ? '偵測到 pam_google_authenticator 模組'
      : '未偵測到 pam_google_authenticator — apt install libpam-google-authenticator',
  );
  const pam = await host.runCommand(
    ['bash', '-c', 'grep -E "pam_google_authenticator" /etc/pam.d/sshd 2>/dev/null | head -3 || true'],
    { timeoutMs: 5_000 },
  );
  const pamConfigured = Boolean((pam.stdout || '').trim());
  if (pamConfigured) {
    notes.push(`pam.d/sshd 已引用：${pam.stdout.trim().slice(0, 120)}`);
  } else {
    notes.push('pam.d/sshd 尚未引用 pam_google_authenticator（檔寫了也未 enforce）');
  }
  const kbd = await host.runCommand(
    [
      'bash',
      '-c',
      'sshd -T 2>/dev/null | grep -iE "kbdinteractiveauthentication|challengeresponseauthentication|usepam" || grep -iE "KbdInteractive|ChallengeResponse|UsePAM" /etc/ssh/sshd_config 2>/dev/null | head -5 || true',
    ],
    { timeoutMs: 8_000 },
  );
  const kbdOut = (kbd.stdout || '').toLowerCase();
  const kbdInteractive =
    kbdOut.includes('kbdinteractiveauthentication yes') ||
    kbdOut.includes('challengeresponseauthentication yes');
  if (kbdInteractive) {
    notes.push('sshd keyboard-interactive / challenge-response 似已開啟');
  } else {
    notes.push('sshd 可能未開 KbdInteractiveAuthentication — TOTP 無法在 SSH 提示');
  }
  return {
    notes,
    lights: {
      package: pamModule ? 'green' : 'red',
      pam: pamConfigured ? 'green' : pamModule ? 'yellow' : 'red',
      kbdInteractive: kbdInteractive ? 'green' : 'yellow',
    },
    pamModule,
    pamConfigured,
    kbdInteractive,
  };
}
